//! From documents to a generated file: parse + transform (the sequence of
//! the run-time loader) + emit, and the file that holds the build functions
//! of the eligible documents with the table that registers them as the
//! compiled markup of an assembly (docs/porting/xaml.md, 9.7).
//!
//! # Interim integration
//!
//! The host of the emitter links the framework (the transform runs against
//! the run-time type system), so a build script would have to take the
//! framework as a build dependency and compile it twice. Until the source
//! scanner of section 9.5 exists, a crate keeps the generated file CHECKED
//! IN: a test calls [`generate_file`] and compares the result with the file
//! (and an ignored test rewrites it). The test crate of the XAML stack does
//! exactly that (`tests/FerroUI.Markup.Xaml.UnitTests/emitter`).

use ::ferroui_markup_xaml::RuntimeXamlLoaderConfiguration;

use crate::FerroXamlIlRuntimeCompiler;

use super::emitter::emit_document;
use super::source::{function_name_of, rust_string_literal};

/// The result of compiling one document.
pub struct CompiledDocument {
    /// The name of the document (its path below the root URI of the assembly).
    pub name: String,
    /// The name of the generated build function.
    pub function_name: String,
    /// The Rust source of the build function, or why the document is not eligible.
    pub source: Result<String, String>,
}

/// A generated file and what it holds.
pub struct GeneratedFile {
    /// The complete text of the file.
    pub source: String,
    /// For every document, in order: its name and, when it is not eligible, why.
    pub documents: Vec<(String, Option<String>)>,
}

/// Parses, transforms and emits each document (`(name, xaml)`) on its own,
/// with the configuration of the run-time loader. A document that fails to
/// transform or contains an unsupported node is reported with the reason;
/// the others are not affected. A document whose generated functions would
/// have the name of a function generated for an earlier document (names
/// that differ only in case or in characters that are not letters or
/// digits, or a name that ends in `_untyped`) is reported as well, instead
/// of becoming a duplicate definition rustc rejects.
pub fn compile_documents(
    documents: &[(&str, &str)],
    configuration: &RuntimeXamlLoaderConfiguration,
) -> Vec<CompiledDocument> {
    let mut compiled = Vec::with_capacity(documents.len());
    // The items of the file each document defines, with the document that defines them.
    let mut items: Vec<(String, &str)> = Vec::with_capacity(documents.len() * 2);
    for (name, xaml) in documents {
        let function_name = function_name_of(name);
        let defined = [function_name.clone(), untyped_function_name(&function_name)];
        let collision = defined
            .iter()
            .find_map(|item| items.iter().find(|(known, _)| known == item).map(|(_, other)| (item.clone(), *other)));
        items.extend(defined.into_iter().map(|item| (item, *name)));
        if let Some((item, other)) = collision {
            let reason = format!("the generated function `{item}` would also be defined for the document `{other}`; rename one of them");
            compiled.push(CompiledDocument { name: name.to_string(), function_name, source: Err(reason) });
            continue;
        }
        let source = match FerroXamlIlRuntimeCompiler::transform_document(xaml, name, configuration) {
            Ok((root, transformer_configuration, _type_system)) => {
                emit_document(&root, &transformer_configuration, &function_name, name).map_err(|e| e.to_string())
            }
            Err(error) => Err(format!("the document does not transform: {}", error.message())),
        };
        compiled.push(CompiledDocument { name: name.to_string(), function_name, source });
    }
    compiled
}

/// The generated file of an assembly: the build function of every eligible
/// document, the table `DOCUMENTS` (document name, untyped build function),
/// `try_load` (the `CompiledXamlLoader` of the assembly: the document whose
/// URI is `<root_uri><name>`, compared without regard to case; a failed build
/// is its error, as it is the error of the run-time loader) and
/// `register_compiled_xaml()`.
///
/// `root_uri` ends with `/` (`ferres://MyApp/`). The text is deterministic:
/// the same documents give the same file.
pub fn generate_file(
    assembly_name: &str,
    root_uri: &str,
    documents: &[(&str, &str)],
    configuration: &RuntimeXamlLoaderConfiguration,
) -> GeneratedFile {
    let compiled = compile_documents(documents, configuration);
    let mut source = String::new();
    source.push_str("// @generated by the Rust emitter of ferroui-markup-xaml-loader (rust_emitter::generate_file).\n");
    source.push_str("// Do not edit: regenerate it (see the header of the module that includes this file).\n");
    source.push('\n');
    source.push_str("#[allow(unused_imports)]\n");
    source.push_str("use ::ferroui_markup_xaml::xaml_il::runtime::compiled as rt;\n");
    source.push('\n');
    source.push_str("/// The assembly the documents of this file belong to.\n");
    source.push_str(&format!("pub const ASSEMBLY_NAME: &str = {};\n", rust_string_literal(assembly_name)));
    source.push('\n');
    source.push_str("/// The URI of a document is this followed by its name.\n");
    source.push_str(&format!("pub const ROOT_URI: &str = {};\n", rust_string_literal(root_uri)));
    source.push('\n');
    source.push_str("/// An untyped build function: the root object as the loader returns it.\n");
    source.push_str("pub type BuildDocument = fn(\n");
    source.push_str("    ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,\n");
    source.push_str(") -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException>;\n");

    let mut report = Vec::with_capacity(compiled.len());
    let mut table = Vec::new();
    for document in &compiled {
        match &document.source {
            Ok(function) => {
                source.push('\n');
                source.push_str(function);
                source.push('\n');
                source.push_str(&format!("fn {}(\n", untyped_function_name(&document.function_name)));
                source.push_str("    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,\n");
                source.push_str(") -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException> {\n");
                source.push_str(&format!("    let root = {}(service_provider)?;\n", document.function_name));
                source.push_str("    ::core::result::Result::Ok(::std::rc::Rc::new(root) as ::ferroui_base::BoxedValue)\n");
                source.push_str("}\n");
                table.push(format!(
                    "    ({}, {} as BuildDocument),\n",
                    rust_string_literal(&document.name),
                    untyped_function_name(&document.function_name)
                ));
                report.push((document.name.clone(), None));
            }
            Err(reason) => report.push((document.name.clone(), Some(reason.clone()))),
        }
    }

    source.push('\n');
    source.push_str("/// The build function of every eligible document, by document name.\n");
    source.push_str("pub const DOCUMENTS: &[(&str, BuildDocument)] = &[\n");
    for entry in &table {
        source.push_str(entry);
    }
    source.push_str("];\n");
    source.push('\n');
    source.push_str("/// The loader of the compiled markup of the assembly: builds the document with the URI\n");
    source.push_str("/// `uri` (compared without regard to case); `Ok(None)` if this file has no such document,\n");
    source.push_str("/// the load error of the build if it fails.\n");
    source.push_str("pub fn try_load(\n");
    source.push_str("    service_provider: ::core::option::Option<&::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,\n");
    source.push_str("    uri: &str,\n");
    source.push_str(") -> ::core::result::Result<::core::option::Option<::ferroui_base::BoxedValue>, ::ferroui_markup_xaml::XamlLoadException> {\n");
    source.push_str("    let name = match uri.get(..ROOT_URI.len()) {\n");
    source.push_str("        ::core::option::Option::Some(root) if root.eq_ignore_ascii_case(ROOT_URI) => &uri[ROOT_URI.len()..],\n");
    source.push_str("        _ => return ::core::result::Result::Ok(::core::option::Option::None),\n");
    source.push_str("    };\n");
    source.push_str("    let ::core::option::Option::Some((_, build)) = ::core::iter::Iterator::find(&mut DOCUMENTS.iter(), |(document, _)| document.eq_ignore_ascii_case(name)) else {\n");
    source.push_str("        return ::core::result::Result::Ok(::core::option::Option::None);\n");
    source.push_str("    };\n");
    source.push_str("    let provider = ::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(\n");
    source.push_str("        service_provider.cloned(),\n");
    source.push_str("    );\n");
    source.push_str("    build(::core::option::Option::Some(provider)).map(::core::option::Option::Some)\n");
    source.push_str("}\n");
    source.push('\n');
    source.push_str("/// Registers the documents of this file as the compiled markup of the assembly.\n");
    source.push_str("pub fn register_compiled_xaml() {\n");
    source.push_str("    ::ferroui_markup_xaml::FerroXamlLoader::register_compiled_xaml(ASSEMBLY_NAME, try_load);\n");
    source.push_str("}\n");
    GeneratedFile { source, documents: report }
}

/// The name of the untyped build function that wraps the build function `function_name`.
fn untyped_function_name(function_name: &str) -> String {
    format!("{function_name}_untyped")
}

/// The transformed tree of one document as text (the AST dump of
/// [`crate::testing::objects::dump_tree`]): what the emitter walks, for diagnosing
/// why a document is not eligible. With the `testing` feature.
#[cfg(any(test, feature = "testing"))]
pub fn transformed_tree(name: &str, xaml: &str, configuration: &RuntimeXamlLoaderConfiguration) -> Result<String, String> {
    FerroXamlIlRuntimeCompiler::transform_document(xaml, name, configuration)
        .map(|(root, _, _)| crate::testing::objects::dump_tree(&root))
        .map_err(|error| error.message())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn reason(compiled: &[CompiledDocument], name: &str) -> Option<String> {
        compiled.iter().find(|document| document.name == name).and_then(|document| document.source.clone().err())
    }

    /// Not from upstream: documents whose build functions would have the same name are
    /// reported as a diagnostic of the later document, not left to rustc.
    #[test]
    fn colliding_function_names_are_reported() {
        let xaml = "<Border xmlns='https://github.com/ferroui'/>";
        let documents = [
            ("a-b.xaml", xaml),
            ("a_b.xaml", xaml),
            ("Case.xaml", xaml),
            ("case.xaml", xaml),
            ("x.xaml", xaml),
            ("x.xaml_untyped", xaml),
        ];
        let compiled = compile_documents(&documents, &RuntimeXamlLoaderConfiguration::new());
        for (name, other, item) in [
            ("a_b.xaml", "a-b.xaml", "build_a_b_xaml"),
            ("case.xaml", "Case.xaml", "build_case_xaml"),
            ("x.xaml_untyped", "x.xaml", "build_x_xaml_untyped"),
        ] {
            let reason = reason(&compiled, name).unwrap_or_else(|| panic!("{name} is not reported"));
            assert_eq!(
                reason,
                format!("the generated function `{item}` would also be defined for the document `{other}`; rename one of them")
            );
        }
        for name in ["a-b.xaml", "Case.xaml", "x.xaml"] {
            let reason = reason(&compiled, name).unwrap_or_default();
            assert!(!reason.contains("would also be defined"), "{name}: {reason}");
        }
    }
}
