//! From documents to a generated file: parse + transform (the sequence of
//! the run-time loader) + emit, and the file that holds the build functions
//! of the eligible documents with the table that registers them as the
//! compiled markup of an assembly (docs/porting/xaml.md, 9.7).
//!
//! # Interim integration
//!
//! The host of the emitter links the framework (the transform runs against
//! the run-time type system), so a build script would have to take the
//! framework as a build dependency and compile it twice. Until the source
//! scanner of section 9.5 exists, a crate keeps the generated file CHECKED
//! IN: a test calls [`generate_file`] and compares the result with the file
//! (and an ignored test rewrites it). The test crate of the XAML stack does
//! exactly that (`tests/FerroUI.Markup.Xaml.UnitTests/emitter`).

use ferroui_markup_xaml::RuntimeXamlLoaderConfiguration;

use crate::FerroXamlIlRuntimeCompiler;

use super::emitter::emit_document;
use super::source::{function_name_of, rust_string_literal};

/// The result of compiling one document.
pub struct CompiledDocument {
    /// The name of the document (its path below the root URI of the assembly).
    pub name: String,
    /// The name of the generated build function.
    pub function_name: String,
    /// The Rust source of the build function, or why the document is not eligible.
    pub source: Result<String, String>,
}

/// A generated file and what it holds.
pub struct GeneratedFile {
    /// The complete text of the file.
    pub source: String,
    /// For every document, in order: its name and, when it is not eligible, why.
    pub documents: Vec<(String, Option<String>)>,
}

/// Parses, transforms and emits each document (`(name, xaml)`) on its own,
/// with the configuration of the run-time loader. A document that fails to
/// transform or contains an unsupported node is reported with the reason;
/// the others are not affected.
pub fn compile_documents(
    documents: &[(&str, &str)],
    configuration: &RuntimeXamlLoaderConfiguration,
) -> Vec<CompiledDocument> {
    let mut compiled = Vec::with_capacity(documents.len());
    for (name, xaml) in documents {
        let function_name = function_name_of(name);
        let source = match FerroXamlIlRuntimeCompiler::transform_document(xaml, name, configuration) {
            Ok((root, transformer_configuration, _type_system)) => {
                emit_document(&root, &transformer_configuration, &function_name, name).map_err(|e| e.to_string())
            }
            Err(error) => Err(format!("the document does not transform: {}", error.message())),
        };
        compiled.push(CompiledDocument { name: name.to_string(), function_name, source });
    }
    compiled
}

/// The generated file of an assembly: the build function of every eligible
/// document, the table `DOCUMENTS` (document name, untyped build function),
/// `try_load` (the `CompiledXamlLoader` of the assembly: the document whose
/// URI is `<root_uri><name>`, compared without regard to case) and
/// `register_compiled_xaml()`.
///
/// `root_uri` ends with `/` (`ferres://MyApp/`). The text is deterministic:
/// the same documents give the same file.
pub fn generate_file(
    assembly_name: &str,
    root_uri: &str,
    documents: &[(&str, &str)],
    configuration: &RuntimeXamlLoaderConfiguration,
) -> GeneratedFile {
    let compiled = compile_documents(documents, configuration);
    let mut source = String::new();
    source.push_str("// @generated by the Rust emitter of ferroui-markup-xaml-loader (rust_emitter::generate_file).\n");
    source.push_str("// Do not edit: regenerate it (see the header of the module that includes this file).\n");
    source.push('\n');
    source.push_str("/// The assembly the documents of this file belong to.\n");
    source.push_str(&format!("pub const ASSEMBLY_NAME: &str = {};\n", rust_string_literal(assembly_name)));
    source.push('\n');
    source.push_str("/// The URI of a document is this followed by its name.\n");
    source.push_str(&format!("pub const ROOT_URI: &str = {};\n", rust_string_literal(root_uri)));
    source.push('\n');
    source.push_str("/// An untyped build function: the root object as the loader returns it.\n");
    source.push_str("pub type BuildDocument = fn(\n");
    source.push_str("    Option<std::rc::Rc<dyn ferroui_base::metadata::IServiceProvider>>,\n");
    source.push_str(") -> Result<ferroui_base::BoxedValue, ferroui_markup_xaml::XamlLoadException>;\n");

    let mut report = Vec::with_capacity(compiled.len());
    let mut table = Vec::new();
    for document in &compiled {
        match &document.source {
            Ok(function) => {
                source.push('\n');
                source.push_str(function);
                source.push('\n');
                source.push_str(&format!("fn {}_untyped(\n", document.function_name));
                source.push_str("    service_provider: Option<std::rc::Rc<dyn ferroui_base::metadata::IServiceProvider>>,\n");
                source.push_str(") -> Result<ferroui_base::BoxedValue, ferroui_markup_xaml::XamlLoadException> {\n");
                source.push_str(&format!("    let root = {}(service_provider)?;\n", document.function_name));
                source.push_str("    Ok(std::rc::Rc::new(root) as ferroui_base::BoxedValue)\n");
                source.push_str("}\n");
                table.push(format!(
                    "    ({}, {}_untyped as BuildDocument),\n",
                    rust_string_literal(&document.name),
                    document.function_name
                ));
                report.push((document.name.clone(), None));
            }
            Err(reason) => report.push((document.name.clone(), Some(reason.clone()))),
        }
    }

    source.push('\n');
    source.push_str("/// The build function of every eligible document, by document name.\n");
    source.push_str("pub const DOCUMENTS: &[(&str, BuildDocument)] = &[\n");
    for entry in &table {
        source.push_str(entry);
    }
    source.push_str("];\n");
    source.push('\n');
    source.push_str("/// The loader of the compiled markup of the assembly: builds the document with the URI\n");
    source.push_str("/// `uri` (compared without regard to case), `None` if this file has no such document.\n");
    source.push_str("/// The loader type has no error channel: a document that fails to build panics with\n");
    source.push_str("/// the message of the load error.\n");
    source.push_str("pub fn try_load(\n");
    source.push_str("    service_provider: Option<&std::rc::Rc<dyn ferroui_base::metadata::IServiceProvider>>,\n");
    source.push_str("    uri: &str,\n");
    source.push_str(") -> Option<ferroui_base::BoxedValue> {\n");
    source.push_str("    let name = uri.get(..ROOT_URI.len()).filter(|root| root.eq_ignore_ascii_case(ROOT_URI)).map(|_| &uri[ROOT_URI.len()..])?;\n");
    source.push_str("    let (_, build) = DOCUMENTS.iter().find(|(document, _)| document.eq_ignore_ascii_case(name))?;\n");
    source.push_str("    let provider = ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(\n");
    source.push_str("        service_provider.cloned(),\n");
    source.push_str("    );\n");
    source.push_str("    match build(Some(provider)) {\n");
    source.push_str("        Ok(root) => Some(root),\n");
    source.push_str("        Err(error) => panic!(\"{}\", error.message()),\n");
    source.push_str("    }\n");
    source.push_str("}\n");
    source.push('\n');
    source.push_str("/// Registers the documents of this file as the compiled markup of the assembly.\n");
    source.push_str("pub fn register_compiled_xaml() {\n");
    source.push_str("    ferroui_markup_xaml::FerroXamlLoader::register_compiled_xaml(ASSEMBLY_NAME, try_load);\n");
    source.push_str("}\n");
    GeneratedFile { source, documents: report }
}
