//! Easing functions: curves that map the linear progress of an animation or
//! transition to the progress that is actually applied.

mod easing;
mod i_easing;
mod back_ease_in;
mod back_ease_in_out;
mod back_ease_out;
mod bounce_ease_in;
mod bounce_ease_in_out;
mod bounce_ease_out;
mod circular_ease_in;
mod circular_ease_in_out;
mod circular_ease_out;
mod cubic_ease_in;
mod cubic_ease_in_out;
mod cubic_ease_out;
mod elastic_ease_in;
mod elastic_ease_in_out;
mod elastic_ease_out;
mod exponential_ease_in;
mod exponential_ease_in_out;
mod exponential_ease_out;
mod linear_easing;
mod quadratic_ease_in;
mod quadratic_ease_in_out;
mod quadratic_ease_out;
mod quartic_ease_in;
mod quartic_ease_in_out;
mod quartic_ease_out;
mod quintic_ease_in;
mod quintic_ease_in_out;
mod quintic_ease_out;
mod sine_ease_in;
mod sine_ease_in_out;
mod sine_ease_out;
mod spline_easing;
mod spring_easing;

pub use easing::Easing;
pub use i_easing::IEasing;
pub use back_ease_in::BackEaseIn;
pub use back_ease_in_out::BackEaseInOut;
pub use back_ease_out::BackEaseOut;
pub use bounce_ease_in::BounceEaseIn;
pub use bounce_ease_in_out::BounceEaseInOut;
pub use bounce_ease_out::BounceEaseOut;
pub use circular_ease_in::CircularEaseIn;
pub use circular_ease_in_out::CircularEaseInOut;
pub use circular_ease_out::CircularEaseOut;
pub use cubic_ease_in::CubicEaseIn;
pub use cubic_ease_in_out::CubicEaseInOut;
pub use cubic_ease_out::CubicEaseOut;
pub use elastic_ease_in::ElasticEaseIn;
pub use elastic_ease_in_out::ElasticEaseInOut;
pub use elastic_ease_out::ElasticEaseOut;
pub use exponential_ease_in::ExponentialEaseIn;
pub use exponential_ease_in_out::ExponentialEaseInOut;
pub use exponential_ease_out::ExponentialEaseOut;
pub use linear_easing::LinearEasing;
pub use quadratic_ease_in::QuadraticEaseIn;
pub use quadratic_ease_in_out::QuadraticEaseInOut;
pub use quadratic_ease_out::QuadraticEaseOut;
pub use quartic_ease_in::QuarticEaseIn;
pub use quartic_ease_in_out::QuarticEaseInOut;
pub use quartic_ease_out::QuarticEaseOut;
pub use quintic_ease_in::QuinticEaseIn;
pub use quintic_ease_in_out::QuinticEaseInOut;
pub use quintic_ease_out::QuinticEaseOut;
pub use sine_ease_in::SineEaseIn;
pub use sine_ease_in_out::SineEaseInOut;
pub use sine_ease_out::SineEaseOut;
pub use spline_easing::SplineEasing;
pub use spring_easing::SpringEasing;
