//! ferroui-themes-fluent
//!
//! The Fluent theme: the control themes of the control set, the colour
//! palettes and the resources they use, in a light and a dark variant and
//! in a normal and a compact density.
//!
//! The theme is markup: `FluentTheme.xaml` (the document of the
//! [`FluentTheme`] class), `Accents/*.xaml` (palette, resources and
//! brushes), `DensityStyles/Compact.xaml`, `Strings/InvariantResources.xaml`,
//! `Controls/FluentControls.xaml` (the list of the control themes) and one
//! document per control under `Controls/`. The documents
//! belong to the assembly `FerroUI.Themes.Fluent`, with the URIs
//! `ferres://FerroUI.Themes.Fluent/<path>`. They are compiled into the crate,
//! as upstream's compiler compiles them, and are not embedded as assets: a
//! load by URI goes to the loader table of the compiled markup, which
//! answers the public document `FluentTheme.xaml` (see `build.rs`).
//!
//! ```ignore
//! application.styles().add(FluentTheme::new().as_style());
//! ```

#[path = "Accents/mod.rs"]
pub mod accents;
mod assets;
mod color_palette_resources;
mod color_palette_resources_collection;
// `compiled_xaml`, the compiled markup of the theme: generated by the build script of the
// crate from the documents of [`FluentTheme`], against the type models of this crate and of
// the crates it is built on (docs/porting/xaml.md, 9.5.13). The checked-in `compiled_xaml.rs`
// is the reference `tests/compiled_xaml_tests.rs` compares the output of the build with, byte
// for byte; it is not a module of the crate. (`compiled_markup`, which the same file declares,
// is not used: the theme registers its assets and its loader table itself.)
ferroui_markup_xaml::include_compiled_xaml!();
mod fluent_theme;
mod register_types;
mod rust_paths;

pub use assets::{excluded_documents, ExcludedDocument};
pub use color_palette_resources::ColorPaletteResources;
pub use color_palette_resources_collection::ColorPaletteResourcesCollection;
pub use fluent_theme::{DensityStyle, FluentTheme};
pub use register_types::{register_types, ASSEMBLY};

#[cfg(test)]
mod tests;
