//! Colors, brushes, geometry, text and drawing.

mod color;
#[cfg(test)]
mod color_tests;
mod colors;
mod drawing_context;
#[cfg(test)]
mod drawing_context_tests;
mod immediate_drawing_context;
mod platform_drawing_context;
mod flow_direction;
mod hsl_color;
mod hsv_color;
mod known_colors;
mod media_context;
mod media_context_clock;
#[cfg(test)]
mod media_context_tests;

pub use color::Color;
pub use colors::Colors;
pub use drawing_context::{DrawingContext, IDrawingContextCore, PushedScope, PushedState};
pub use immediate_drawing_context::{ImmediateDrawingContext, ImmediatePushedState};
pub use platform_drawing_context::PlatformDrawingContext;
pub use flow_direction::FlowDirection;
pub use hsl_color::HslColor;
pub use hsv_color::HsvColor;
pub use known_colors::{KnownColor, KnownColors};
pub use media_context::MediaContext;
pub use media_context_clock::MediaContextClock;

// --- brushes, pens, transforms and geometry ---

pub mod effects;
pub mod imaging;
pub mod immutable;
pub mod transformation;

mod alignment_x;
mod alignment_y;
mod arc_segment;
mod bezier_segment;
mod box_shadow;
mod box_shadows;
mod brush;
mod brush_extensions;
mod brush_mapping_mode;
mod brushes;
mod conic_gradient_brush;
mod dash_style;
mod edge_mode;
mod ellipse_geometry;
mod fill_rule;
mod geometry;
mod geometry_builder;
mod geometry_collection;
mod geometry_group;
mod gradient_brush;
mod gradient_spread_method;
mod gradient_stop;
mod gradient_stops;
mod i_brush;
mod shared_brush;
mod i_conic_gradient_brush;
mod i_dash_style;
mod i_gradient_brush;
mod i_gradient_stop;
mod i_immutable_brush;
mod i_linear_gradient_brush;
mod i_mutable_brush;
mod i_mutable_transform;
mod i_pen;
mod i_radial_gradient_brush;
mod i_solid_color_brush;
mod i_transform;
mod immutable_geometry;
mod immutable_geometry_impl;
mod intersection_result;
mod known_color_brushes;
mod line_geometry;
mod line_segment;
mod linear_gradient_brush;
mod matrix_transform;
mod media_collection;
mod path_figure;
mod path_geometry;
mod path_geometry_collections;
mod path_markup_parser;
mod path_segment;
mod pen;
mod pen_line_cap;
mod pen_line_join;
mod platform_geometry;
mod points;
mod poly_bezier_segment;
mod poly_line_segment;
mod polyline_geometry;
mod quadratic_bezier_segment;
mod radial_gradient_brush;
mod rectangle_geometry;
mod ref_adapter;
mod render_options;
mod rotate_transform;
mod scale_transform;
mod skew_transform;
mod solid_color_brush;
mod stream_geometry;
mod stream_geometry_context;
mod stretch;
mod stretch_direction;
mod string_splitter;
mod sweep_direction;
mod text_rendering_mode;
mod tile_mode;
mod transform;
mod transform_extensions;
mod transform_group;
mod translate_transform;

pub use alignment_x::AlignmentX;
pub use alignment_y::AlignmentY;
pub use arc_segment::ArcSegment;
pub use bezier_segment::BezierSegment;
pub use box_shadow::BoxShadow;
pub use box_shadows::BoxShadows;
pub use brush::{Brush, BrushImpl, BrushImplExt, BrushVTable, ServerBrushFactory};
pub use brush_extensions::BrushExtensions;
pub use brush_mapping_mode::BrushMappingMode;
pub use brushes::Brushes;
pub use conic_gradient_brush::ConicGradientBrush;
pub use dash_style::DashStyle;
pub use edge_mode::EdgeMode;
pub use ellipse_geometry::EllipseGeometry;
pub use fill_rule::FillRule;
pub use geometry::{Geometry, GeometryImpl, GeometryImplExt, GeometryVTable};
pub use geometry_builder::{GeometryBuilder, RoundedRectKeypoints};
pub use geometry_collection::GeometryCollection;
pub use geometry_group::GeometryGroup;
pub use gradient_brush::{GradientBrush, GradientBrushImpl, GradientBrushImplExt, GradientBrushVTable};
pub use gradient_spread_method::GradientSpreadMethod;
pub use gradient_stop::GradientStop;
pub use gradient_stops::GradientStops;
pub use i_brush::IBrush;
pub use shared_brush::{shared_brush_of, shared_pen_of, SharedBrush, SharedPen};
pub use i_conic_gradient_brush::IConicGradientBrush;
pub use i_dash_style::IDashStyle;
pub use i_gradient_brush::IGradientBrush;
pub use i_gradient_stop::IGradientStop;
pub use i_immutable_brush::IImmutableBrush;
pub use i_linear_gradient_brush::ILinearGradientBrush;
pub use i_mutable_brush::IMutableBrush;
pub use i_mutable_transform::IMutableTransform;
pub use i_pen::IPen;
pub use i_radial_gradient_brush::IRadialGradientBrush;
pub use i_solid_color_brush::{IImmutableSolidColorBrush, ISolidColorBrush};
pub use i_transform::ITransform;
pub use immutable_geometry::ImmutableGeometry;
pub use intersection_result::IntersectionResult;
pub use line_geometry::LineGeometry;
pub use line_segment::LineSegment;
pub use linear_gradient_brush::LinearGradientBrush;
pub use matrix_transform::MatrixTransform;
pub use media_collection::{track_item_property_changed, MediaCollection, ResetBehavior};
pub use path_figure::PathFigure;
pub use path_geometry::PathGeometry;
pub use path_geometry_collections::{PathFigures, PathSegments};
pub use path_markup_parser::PathMarkupParser;
pub use path_segment::{PathSegment, PathSegmentImpl, PathSegmentImplExt, PathSegmentVTable};
pub use pen::{Pen, StrokeDashArray};
pub use pen_line_cap::PenLineCap;
pub use pen_line_join::PenLineJoin;
pub use platform_geometry::PlatformGeometry;
pub use points::Points;
pub use poly_bezier_segment::PolyBezierSegment;
pub use poly_line_segment::PolyLineSegment;
pub use polyline_geometry::PolylineGeometry;
pub use quadratic_bezier_segment::QuadraticBezierSegment;
pub use radial_gradient_brush::RadialGradientBrush;
pub use rectangle_geometry::RectangleGeometry;
pub use render_options::RenderOptions;
pub use rotate_transform::RotateTransform;
pub use scale_transform::ScaleTransform;
pub use skew_transform::SkewTransform;
pub use solid_color_brush::SolidColorBrush;
pub use stream_geometry::StreamGeometry;
pub use stream_geometry_context::StreamGeometryContext;
pub use stretch::Stretch;
pub use stretch_direction::StretchDirection;
pub use string_splitter::{split_respecting_brackets, StringSplitOptions};
pub use sweep_direction::SweepDirection;
pub use text_rendering_mode::TextRenderingMode;
pub use tile_mode::TileMode;
pub use transform::{Transform, TransformImpl, TransformImplExt, TransformVTable};
pub use transform_extensions::TransformExtensions;
pub use transform_group::{TransformGroup, Transforms};
pub use translate_transform::TranslateTransform;

pub use crate::combined_geometry::{CombinedGeometry, GeometryCombineMode};
pub use crate::rotate_3d_transform::Rotate3DTransform;

// --- imaging, tile brushes, effects, drawings, materials ---

mod acrylic_background_source;
mod background_sizing;
mod bitmap_cache;
mod cache_mode;
mod drawing;
mod drawing_brush;
mod drawing_collection;
mod drawing_group;
mod drawing_image;
mod experimental_acrylic_material;
mod geometry_drawing;
mod glyph_run_drawing;
mod geometry_hit_test_result;
mod i_affects_render;
mod i_experimental_acrylic_material;
mod i_image;
mod i_image_brush;
mod i_mutable_experimental_acrylic_material;
mod i_scene_brush;
mod i_tile_brush;
mod image_brush;
mod image_drawing;
mod immutable_experimental_acrylic_material;
mod material_extensions;
mod media_extensions;
mod precise_elliptic_arc_helper;
mod tile_brush;
mod visual_brush;

pub use acrylic_background_source::AcrylicBackgroundSource;
pub use background_sizing::BackgroundSizing;
pub use bitmap_cache::BitmapCache;
pub use cache_mode::{CacheMode, CacheModeImpl, CacheModeImplExt};
pub use drawing::{Drawing, DrawingImpl, DrawingImplExt, DrawingVTable};
pub use drawing_brush::DrawingBrush;
pub use drawing_collection::DrawingCollection;
pub use drawing_group::DrawingGroup;
pub use drawing_image::DrawingImage;
pub use effects::{
    BlurEffect, DropShadowDirectionEffect, DropShadowEffect, DropShadowEffectBase, Effect, EffectExtensions,
    IBlurEffect, IDirectionDropShadowEffect, IDropShadowEffect, IEffect, IImmutableEffect, IMutableEffect,
    ImmutableBlurEffect, ImmutableDropShadowDirectionEffect, ImmutableDropShadowEffect,
};
pub use experimental_acrylic_material::ExperimentalAcrylicMaterial;
pub use geometry_drawing::GeometryDrawing;
pub use glyph_run_drawing::GlyphRunDrawing;
pub use geometry_hit_test_result::GeometryHitTestResult;
pub use i_affects_render::{can_value_affect_render, subscribe_invalidated, IAffectsRender};
pub use i_experimental_acrylic_material::IExperimentalAcrylicMaterial;
pub use i_image::IImage;
pub use i_image_brush::{IImageBrush, IImageBrushSource};
pub use i_mutable_experimental_acrylic_material::IMutableExperimentalAcrylicMaterial;
pub use i_scene_brush::{ISceneBrush, ISceneBrushContent, ImmutableSceneBrush};
pub use i_tile_brush::ITileBrush;
pub use image_brush::ImageBrush;
pub use image_drawing::ImageDrawing;
pub use immutable_experimental_acrylic_material::ImmutableExperimentalAcrylicMaterial;
pub use material_extensions::MaterialExtensions;
pub use media_extensions::MediaExtensions;
pub use tile_brush::TileBrush;
pub use visual_brush::VisualBrush;

// --- fonts and text ---

pub mod fonts;
pub mod text_formatting;

mod baseline_alignment;
mod baseline_pixel_alignment;
mod character_hit;
mod composite_font_family_key;
mod font_fallback;
mod font_family;
mod font_feature;
mod font_feature_collection;
mod font_manager;
#[cfg(test)]
mod font_manager_tests;
#[cfg(test)]
mod glyph_run_tests;
mod font_manager_options;
mod font_metrics;
mod font_simulations;
mod font_source_identifier;
mod font_stretch;
mod font_style;
mod font_variation_settings;
mod font_weight;
mod glyph_bounds;
mod glyph_drawing_options;
mod glyph_drawing_type;
mod glyph_metrics;
mod glyph_run;
mod glyph_run_metrics;
mod glyph_typeface;
#[cfg(test)]
mod glyph_typeface_tests;
mod i_font_memory;
mod i_glyph_drawing;
mod i_immutable_glyph_run_reference;
mod i_platform_typeface;
mod i_text_shaper_typeface;
mod normalized_variation_position;
mod text_alignment;
mod text_decoration;
mod text_decoration_collection;
mod text_decoration_location;
mod text_decoration_unit;
mod text_decorations;
mod text_hinting_mode;
mod text_hit_test_result;
mod text_options;
mod text_wrapping;
mod typeface;
mod unicode_range;

pub use baseline_alignment::BaselineAlignment;
pub use baseline_pixel_alignment::BaselinePixelAlignment;
pub use character_hit::CharacterHit;
pub use font_fallback::FontFallback;
pub use font_family::FontFamily;
pub use font_feature::FontFeature;
pub use font_feature_collection::FontFeatureCollection;
pub use font_manager::FontManager;
pub use font_manager_options::FontManagerOptions;
pub use font_metrics::FontMetrics;
pub use font_simulations::FontSimulations;
pub use font_stretch::FontStretch;
pub use font_style::FontStyle;
pub use font_variation_settings::{FontVariation, FontVariationSettings};
pub use font_weight::FontWeight;
pub(crate) use glyph_bounds::GlyphBounds;
pub use glyph_drawing_options::GlyphDrawingOptions;
pub use glyph_drawing_type::GlyphDrawingType;
pub use glyph_metrics::GlyphMetrics;
pub use glyph_run::{GlyphInfoList, GlyphInfosRef, GlyphRun};
pub use glyph_run_metrics::GlyphRunMetrics;
pub use glyph_typeface::GlyphTypeface;
pub use i_font_memory::IFontMemory;
pub use i_glyph_drawing::IGlyphDrawing;
pub use i_immutable_glyph_run_reference::IImmutableGlyphRunReference;
pub use i_platform_typeface::IPlatformTypeface;
pub use i_text_shaper_typeface::ITextShaperTypeface;
#[allow(unused_imports)] // used by the variable font support, which is not ported yet
pub(crate) use normalized_variation_position::{
    NormalizedVariationCoordinate, NormalizedVariationPosition, NormalizedVariationPositionError,
};
pub use text_alignment::TextAlignment;
pub use text_decoration::TextDecoration;
pub use text_decoration_collection::TextDecorationCollection;
pub use text_decoration_location::TextDecorationLocation;
pub use text_decoration_unit::TextDecorationUnit;
pub use text_decorations::TextDecorations;
pub use text_hinting_mode::TextHintingMode;
pub use text_hit_test_result::TextHitTestResult;
pub use text_options::TextOptions;
pub use text_wrapping::TextWrapping;
pub use typeface::Typeface;
pub use unicode_range::{UnicodeRange, UnicodeRangeSegment};

mod text_collapsing_create_info;
mod text_leading_prefix_trimming;
mod text_none_trimming;
mod text_path_segment_ellipsis;
mod text_path_segment_trimming;
mod text_trailing_trimming;
pub(crate) mod text_trimming;

pub use text_collapsing_create_info::TextCollapsingCreateInfo;
pub use text_leading_prefix_trimming::TextLeadingPrefixTrimming;
pub(crate) use text_none_trimming::TextNoneTrimming;
pub use text_path_segment_ellipsis::TextPathSegmentEllipsis;
pub use text_path_segment_trimming::TextPathSegmentTrimming;
pub use text_trailing_trimming::TextTrailingTrimming;
pub use text_trimming::{TextTrimming, DEFAULT_ELLIPSIS_CHAR};

mod formatted_text;

pub use formatted_text::FormattedText;
