#!/usr/bin/env python3
"""The crates of a release, derived from `cargo metadata` (docs/release.md).

A crate of the workspace is published unless its manifest says `publish = false`. Nothing here
names a crate: the lists, their order, the checks and the table of the README follow that rule,
so a new crate joins by being a member of the workspace.

    crates.py order                  the published crates, in the order they are published
    crates.py unpublished            the crates that are never published
    crates.py version                the version of the workspace
    crates.py check                  what a published crate has to state (metadata, versions, notices)
    crates.py set-version <version>  write the version of the workspace and of its dependency pins
    crates.py readme [--check]       regenerate the crate table of README.md (or fail if it is stale)
    crates.py published <crate> <version>
                                     exit 0 if crates.io has that version, 1 if not, 2 if unknown

Only the standard library and the `cargo` on PATH. This script publishes nothing.
"""

import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(ROOT, "Cargo.toml")
README = os.path.join(ROOT, "README.md")

# The files that travel with every package beside its sources: the licence of the project and the
# project-wide notice with the attributions (symbolic links to the files at the root of the
# repository, which `cargo package` follows).
LICENSE_FILE = "LICENSE"
PROJECT_NOTICE_FILE = "NOTICE-PROJECT.md"

# crates.io refuses a package above this size (compressed).
SIZE_LIMIT = 10 * 1024 * 1024

# The groups of the table of the README, in the order of the table. A crate states its group in
# its manifest: `[package.metadata.release] group = "<key>"`.
GROUPS = [
    ("core", "Core"),
    ("controls", "Controls and themes"),
    ("markup", "Markup and build"),
    ("rendering", "Render backends and text"),
    ("platforms", "Platforms"),
    ("tools", "Tools and designer support"),
]

TABLE_BEGIN = "<!-- crates-table:begin (generated by scripts/release/readme-crates-table.sh; do not edit) -->"
TABLE_END = "<!-- crates-table:end -->"

# Semantic versioning 2.0.0, as crates.io accepts it.
VERSION = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(-(0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*)?$"
)


def fail(message):
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def metadata():
    output = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--no-deps"],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
    ).stdout
    return json.loads(output)


def is_published(package):
    # `publish = false` is an empty list of registries; no key is `None`.
    return package["publish"] is None


def workspace_version(packages):
    versions = sorted({package["version"] for package in packages})
    if len(versions) != 1:
        fail(f"the crates of the workspace have more than one version: {', '.join(versions)}")
    return versions[0]


def internal_dependencies(package, names, kinds):
    """The dependencies of a package on crates of the workspace, of the given kinds."""
    found = []
    for dependency in package["dependencies"]:
        kind = dependency["kind"] or "normal"
        if dependency["name"] in names and kind in kinds and dependency.get("path"):
            found.append(dependency)
    return found


def stays_in_package(dependency):
    """Whether a dependency is in the manifest of the package that is uploaded.

    Cargo removes a development dependency that has a path and no version from the manifest it
    uploads; `cargo metadata` shows the missing version as the requirement `*`.
    """
    return (dependency["kind"] or "normal") != "dev" or dependency["req"] != "*"


def publish_order(packages):
    """The published crates, each after the crates of the workspace its package depends on.

    A development dependency with a version counts: Cargo resolves it when it packages the crate,
    so it has to be in the registry first. Ties are broken by name, so the order is stable.
    """
    published = {package["name"]: package for package in packages if is_published(package)}
    waiting = {}
    for name, package in published.items():
        dependencies = internal_dependencies(package, published, ("normal", "build", "dev"))
        waiting[name] = {d["name"] for d in dependencies if stays_in_package(d) and d["name"] != name}
    order = []
    while waiting:
        ready = sorted(name for name, dependencies in waiting.items() if not dependencies)
        if not ready:
            cycle = ", ".join(f"{name} (waits for {', '.join(sorted(d))})" for name, d in sorted(waiting.items()))
            fail(
                "the published crates depend on one another in a cycle, so no order publishes them: "
                f"{cycle}. A cycle can only go through a development dependency: give that one a path "
                "and no version (not `workspace = true`), and Cargo leaves it out of the package."
            )
        name = ready[0]
        order.append(name)
        del waiting[name]
        for dependencies in waiting.values():
            dependencies.discard(name)
    return [published[name] for name in order]


def check(packages):
    problems = []
    names = {package["name"] for package in packages}
    published = {package["name"] for package in packages if is_published(package)}
    version = workspace_version(packages)
    if not VERSION.match(version):
        problems.append(f"the version of the workspace, {version}, is not a semantic version")

    links = {}
    for package in packages:
        if package.get("links"):
            links.setdefault(package["links"], []).append(package["name"])
    for key, owners in sorted(links.items()):
        if len(owners) > 1:
            problems.append(f"the `links` key {key} is stated by more than one crate: {', '.join(owners)}")

    for package in packages:
        if not is_published(package):
            continue
        name = package["name"]
        directory = os.path.dirname(package["manifest_path"])
        for key in ("description", "license", "repository", "readme"):
            if not package.get(key):
                problems.append(f"{name}: the manifest has no `{key}`")
        for key in ("keywords", "categories"):
            if not package.get(key):
                problems.append(f"{name}: the manifest has no `{key}`")
        if len(package.get("keywords") or []) > 5:
            problems.append(f"{name}: more than five keywords (crates.io accepts five)")
        description = package.get("description") or ""
        if "\n" in description.strip():
            problems.append(f"{name}: the description is more than one line")
        group = ((package.get("metadata") or {}).get("release") or {}).get("group")
        if group not in dict(GROUPS):
            problems.append(
                f"{name}: `[package.metadata.release] group` is {group!r}; one of "
                f"{', '.join(key for key, _ in GROUPS)} is expected (the table of the README)"
            )
        for file in (LICENSE_FILE, PROJECT_NOTICE_FILE):
            if not os.path.isfile(os.path.join(directory, file)):
                problems.append(
                    f"{name}: no {file} in {os.path.relpath(directory, ROOT)} "
                    "(a symbolic link to the file at the root of the repository; docs/release.md, \"Licence and notices\")"
                )

        for dependency in package["dependencies"]:
            kind = dependency["kind"] or "normal"
            label = f"{name}: the {kind} dependency {dependency['name']}"
            source = dependency.get("source") or ""
            if source.startswith("git+"):
                problems.append(f"{label} is a git dependency, which crates.io does not accept")
            if dependency["name"] not in names or not dependency.get("path"):
                continue
            if not stays_in_package(dependency):
                continue
            if dependency["name"] not in published:
                problems.append(f"{label} is a crate that is not published (`publish = false`)")
            if dependency["req"] != f"={version}":
                problems.append(
                    f"{label} has the requirement {dependency['req']!r}; a crate of the workspace is "
                    f"pinned to \"={version}\" (`workspace = true`, or a path alone for a development "
                    "dependency that is left out of the package)"
                )
    return problems


def set_version(version):
    if not VERSION.match(version):
        fail(f"{version!r} is not a semantic version (for example 0.1.0-preview.2 or 0.1.0)")
    with open(MANIFEST, encoding="utf-8") as file:
        lines = file.read().split("\n")

    section = None
    package_versions = 0
    pins = 0
    for index, line in enumerate(lines):
        header = re.match(r"^\[([^\]]+)\]\s*$", line)
        if header:
            section = header.group(1)
            continue
        if section == "workspace.package" and re.match(r"^version\s*=", line):
            lines[index] = f'version = "{version}"'
            package_versions += 1
        elif section == "workspace.dependencies":
            # A crate of the workspace: an inline table with a path.
            entry = re.match(r"^([A-Za-z0-9_-]+)\s*=\s*\{(.*)\}\s*$", line)
            if not entry or not re.search(r'\bpath\s*=\s*"', entry.group(2)):
                continue
            body = re.sub(r'\s*\bversion\s*=\s*"[^"]*"\s*,?', "", entry.group(2)).strip()
            lines[index] = f'{entry.group(1)} = {{ version = "={version}", {body} }}'
            pins += 1
    if package_versions != 1:
        fail(f"expected one `version` key in [workspace.package] of {MANIFEST}, found {package_versions}")
    if pins == 0:
        fail(f"found no path dependency in [workspace.dependencies] of {MANIFEST}")
    with open(MANIFEST, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))

    # `cargo metadata` resolves the workspace again, which also writes the new versions to Cargo.lock.
    packages = metadata()["packages"]
    wrong = sorted(package["name"] for package in packages if package["version"] != version)
    if wrong:
        fail(
            f"these crates do not have the version {version} after the change (a manifest that states "
            f"its own version instead of `version.workspace = true`): {', '.join(wrong)}"
        )
    problems = [problem for problem in check(packages) if "requirement" in problem or "semantic" in problem]
    if problems:
        fail("the workspace is not consistent after the change:\n  " + "\n  ".join(problems))
    print(f"{len(packages)} crates at {version}; {pins} dependency pins at ={version}")


def badge_row(package):
    name = package["name"]
    description = " ".join((package.get("description") or "").split()).replace("|", "\\|")
    crate = f"https://crates.io/crates/{name}"
    return (
        f"| [`{name}`]({crate}) | {description} "
        f"| [![version](https://img.shields.io/crates/v/{name}.svg)]({crate}) "
        f"| [![downloads](https://img.shields.io/crates/d/{name}.svg)]({crate}) "
        f"| [![docs.rs](https://img.shields.io/docsrs/{name})](https://docs.rs/{name}) |"
    )


def table(packages):
    titles = dict(GROUPS)
    grouped = {key: [] for key, _ in GROUPS}
    other = []
    # Within a group in the order of publication, which is the order of the layers.
    for package in publish_order(packages):
        group = ((package.get("metadata") or {}).get("release") or {}).get("group")
        (grouped[group] if group in grouped else other).append(package)
    lines = []
    sections = [(titles[key], grouped[key]) for key, _ in GROUPS] + [("Other", other)]
    for title, members in sections:
        if not members:
            continue
        lines += [f"**{title}**", "", "| Crate | Description | Version | Downloads | Documentation |", "|---|---|---|---|---|"]
        lines += [badge_row(package) for package in members]
        lines.append("")
    return "\n".join(lines).rstrip("\n")


def readme(packages, check_only):
    with open(README, encoding="utf-8") as file:
        text = file.read()
    begin = text.find(TABLE_BEGIN)
    end = text.find(TABLE_END)
    if begin < 0 or end < begin:
        fail(f"README.md has no crate table markers ({TABLE_BEGIN} ... {TABLE_END})")
    updated = text[: begin + len(TABLE_BEGIN)] + "\n\n" + table(packages) + "\n\n" + text[end:]
    if updated == text:
        print("the crate table of README.md is current")
        return
    if check_only:
        fail("the crate table of README.md is stale: run scripts/release/readme-crates-table.sh and commit the result")
    with open(README, "w", encoding="utf-8") as file:
        file.write(updated)
    print("README.md: the crate table was regenerated")


def index_path(name):
    name = name.lower()
    if len(name) <= 2:
        return f"{len(name)}/{name}"
    if len(name) == 3:
        return f"3/{name[0]}/{name}"
    return f"{name[:2]}/{name[2:4]}/{name}"


def is_on_crates_io(name, version):
    """Asks the sparse index of crates.io, which needs no token: True, False, or None if unknown."""
    request = urllib.request.Request(
        f"https://index.crates.io/{index_path(name)}",
        headers={"User-Agent": "ferroui-release-scripts (https://github.com/wieslawsoltes/FerroUI)"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        # No crate of that name.
        return False if error.code in (404, 410) else None
    except (urllib.error.URLError, TimeoutError):
        return None
    for line in body.splitlines():
        if line.strip() and json.loads(line).get("vers") == version:
            return True
    return False


def main(arguments):
    if not arguments or arguments[0] in ("-h", "--help", "help"):
        print(__doc__)
        return 0
    command, rest = arguments[0], arguments[1:]
    if command == "set-version":
        if len(rest) != 1:
            fail("usage: crates.py set-version <version>")
        set_version(rest[0])
        return 0
    if command == "published":
        if len(rest) != 2:
            fail("usage: crates.py published <crate> <version>")
        answer = is_on_crates_io(rest[0], rest[1])
        return 2 if answer is None else (0 if answer else 1)

    packages = metadata()["packages"]
    if command == "order":
        for package in publish_order(packages):
            print(package["name"])
    elif command == "unpublished":
        for package in sorted(packages, key=lambda package: package["name"]):
            if not is_published(package):
                print(package["name"])
    elif command == "version":
        print(workspace_version(packages))
    elif command == "check":
        publish_order(packages)
        problems = check(packages)
        if problems:
            fail(f"{len(problems)} problems:\n  " + "\n  ".join(problems))
        count = sum(1 for package in packages if is_published(package))
        print(f"{count} published crates at {workspace_version(packages)}: metadata, versions and notices are in order")
    elif command == "readme":
        readme(packages, "--check" in rest)
    else:
        fail(f"unknown command {command!r}; see crates.py --help")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
