// Generated by scripts/convert-unicode-enums.py from the upstream file
// `EastAsianWidthClass.cs`. Do not edit.

/// The Unicode `EastAsianWidthClass` property values, numbered as the generated tries store them.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum EastAsianWidthClass {
    /// Property value alias: `A`
    #[default]
    Ambiguous = 0,
    /// Property value alias: `F`
    Fullwidth = 1,
    /// Property value alias: `H`
    Halfwidth = 2,
    /// Property value alias: `N`
    Neutral = 3,
    /// Property value alias: `Na`
    Narrow = 4,
    /// Property value alias: `W`
    Wide = 5,
}

impl EastAsianWidthClass {
    /// The number of values.
    pub const COUNT: usize = 6;

    /// Converts the numeric value stored in the generated tries (the cast upstream performs).
    /// Values outside of the enum map to `Ambiguous` (value 0).
    #[inline]
    pub const fn from_u32(value: u32) -> Self {
        match value {
            1 => Self::Fullwidth,
            2 => Self::Halfwidth,
            3 => Self::Neutral,
            4 => Self::Narrow,
            5 => Self::Wide,
            _ => Self::Ambiguous,
        }
    }
}
