// Generated by scripts/convert-unicode-enums.py from the upstream file
// `WordBreakClass.cs`. Do not edit.

/// The Unicode `WordBreakClass` property values, numbered as the generated tries store them.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum WordBreakClass {
    /// Property value alias: `XX`
    #[default]
    Other = 0,
    /// Property value alias: `CR`
    CarriageReturn = 1,
    /// Property value alias: `LF`
    LineFeed = 2,
    /// Property value alias: `NL`
    Newline = 3,
    /// Property value alias: `Extend`
    Extend = 4,
    /// Property value alias: `ZWJ`
    ZWJ = 5,
    /// Property value alias: `RI`
    RegionalIndicator = 6,
    /// Property value alias: `FO`
    Format = 7,
    /// Property value alias: `KA`
    Katakana = 8,
    /// Property value alias: `HL`
    HebrewLetter = 9,
    /// Property value alias: `LE`
    ALetter = 10,
    /// Property value alias: `SQ`
    SingleQuote = 11,
    /// Property value alias: `DQ`
    DoubleQuote = 12,
    /// Property value alias: `MB`
    MidNumLet = 13,
    /// Property value alias: `ML`
    MidLetter = 14,
    /// Property value alias: `MN`
    MidNum = 15,
    /// Property value alias: `NU`
    Numeric = 16,
    /// Property value alias: `EX`
    ExtendNumLet = 17,
    /// Property value alias: `WSegSpace`
    WSegSpace = 18,
}

impl WordBreakClass {
    /// The number of values.
    pub const COUNT: usize = 19;

    /// Converts the numeric value stored in the generated tries (the cast upstream performs).
    /// Values outside of the enum map to `Other` (value 0).
    #[inline]
    pub const fn from_u32(value: u32) -> Self {
        match value {
            1 => Self::CarriageReturn,
            2 => Self::LineFeed,
            3 => Self::Newline,
            4 => Self::Extend,
            5 => Self::ZWJ,
            6 => Self::RegionalIndicator,
            7 => Self::Format,
            8 => Self::Katakana,
            9 => Self::HebrewLetter,
            10 => Self::ALetter,
            11 => Self::SingleQuote,
            12 => Self::DoubleQuote,
            13 => Self::MidNumLet,
            14 => Self::MidLetter,
            15 => Self::MidNum,
            16 => Self::Numeric,
            17 => Self::ExtendNumLet,
            18 => Self::WSegSpace,
            _ => Self::Other,
        }
    }
}
