// @generated by the Rust emitter of ferroui-markup-xaml-loader (rust_emitter::generate_file).
// Do not edit: regenerate it (see the header of the module that includes this file).

#[allow(unused_imports)]
use ::ferroui_markup_xaml::xaml_il::runtime::compiled as rt;

/// The assembly the documents of this file belong to.
pub const ASSEMBLY_NAME: &str = "\u{30a2}\u{30bb}\u{30f3}\u{30d6}\u{30ea}";

/// The URI of a document is this followed by its name.
pub const ROOT_URI: &str = "ferres://\u{30a2}\u{30bb}\u{30f3}\u{30d6}\u{30ea}/";

/// An untyped build function: the root object as the loader returns it.
pub type BuildDocument = fn(
    ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException>;

/// The XML namespaces of documents of this file, as the compiler resolved them.
const XML_NAMESPACES_0: rt::XmlNamespaceTable = &[
    ("", &[("FerroUI", "FerroUI.Base"), ("FerroUI.Animation", "FerroUI.Base"), ("FerroUI.Animation.Easings", "FerroUI.Base"), ("FerroUI.Controls", "FerroUI.Base"), ("FerroUI.Data", "FerroUI.Base"), ("FerroUI.Data.Converters", "FerroUI.Base"), ("FerroUI.Input", "FerroUI.Base"), ("FerroUI.Input.GestureRecognizers", "FerroUI.Base"), ("FerroUI.Input.TextInput", "FerroUI.Base"), ("FerroUI.Layout", "FerroUI.Base"), ("FerroUI.LogicalTree", "FerroUI.Base"), ("FerroUI.Media", "FerroUI.Base"), ("FerroUI.Media.Imaging", "FerroUI.Base"), ("FerroUI.Media.Transformation", "FerroUI.Base"), ("FerroUI.Styling", "FerroUI.Base"), ("FerroUI", "FerroUI.Controls"), ("FerroUI.Automation", "FerroUI.Controls"), ("FerroUI.Controls", "FerroUI.Controls"), ("FerroUI.Controls.Embedding", "FerroUI.Controls"), ("FerroUI.Controls.Presenters", "FerroUI.Controls"), ("FerroUI.Controls.Primitives", "FerroUI.Controls"), ("FerroUI.Controls.Shapes", "FerroUI.Controls"), ("FerroUI.Controls.Templates", "FerroUI.Controls"), ("FerroUI.Controls.Notifications", "FerroUI.Controls"), ("FerroUI.Controls.Chrome", "FerroUI.Controls"), ("FerroUI.Controls.Documents", "FerroUI.Controls"), ("FerroUI.Markup.Xaml.MarkupExtensions", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Styling", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Templates", "FerroUI.Markup.Xaml"), ("FerroUI.Themes.Simple", "FerroUI.Themes.Simple"), ("FerroUI.Themes.Fluent", "FerroUI.Themes.Fluent")]),
    ("x", &[]),
];

/// The base URI and the XML namespaces of `ResourceInclude_Loads_ResourceDictionary.xaml`.
static BUILD_RESOURCEINCLUDE_LOADS_RESOURCEDICTIONARY_XAML_DOCUMENT: rt::DocumentInfo = rt::DocumentInfo { base_uri: ::core::option::Option::Some("ferres://\u{30a2}\u{30bb}\u{30f3}\u{30d6}\u{30ea}/ResourceInclude_Loads_ResourceDictionary.xaml"), namespaces: XML_NAMESPACES_0 };

/// Generated from `ResourceInclude_Loads_ResourceDictionary.xaml`.
pub fn build_resourceinclude_loads_resourcedictionary_xaml(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::Ref<::ferroui_controls::UserControl>, ::ferroui_markup_xaml::XamlLoadException> {
    // ResourceInclude_Loads_ResourceDictionary.xaml(2,2) UserControl
    let user_control_0 = ::ferroui_controls::UserControl::new();
    let source_info_0 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(2_i32, 2_i32, ::core::option::Option::Some(::std::string::String::from("ResourceInclude_Loads_ResourceDictionary.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&user_control_0)), rt::cast(::core::clone::Clone::clone(&source_info_0), 2, 2)?), 2, 2)?;
    let context = rt::populate_context(service_provider, &BUILD_RESOURCEINCLUDE_LOADS_RESOURCEDICTIONARY_XAML_DOCUMENT, rt::to_value(user_control_0.clone()));
    let name_scope = context.name_scope_field();
    user_control_0.begin_init();
    context.push_parent(rt::to_value(user_control_0.clone()));
    // ResourceInclude_Loads_ResourceDictionary.xaml(5,6) Resources
    // ResourceInclude_Loads_ResourceDictionary.xaml(5,6) ResourceDictionary
    let resource_dictionary_0 = ::ferroui_base::controls::ResourceDictionary::new();
    let source_info_1 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(5_i32, 6_i32, ::core::option::Option::Some(::std::string::String::from("ResourceInclude_Loads_ResourceDictionary.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&resource_dictionary_0)), rt::cast(::core::clone::Clone::clone(&source_info_1), 5, 6)?), 5, 6)?;
    context.push_parent(rt::to_value(resource_dictionary_0.clone()));
    // ResourceInclude_Loads_ResourceDictionary.xaml(7,14) MergedDictionaries
    let merged_dictionaries_collection_0 = ::ferroui_base::controls::ResourceDictionary::__markup_get_MergedDictionaries(&resource_dictionary_0);
    let service_provider_0 = ::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::__markup_CreateRootServiceProviderV3_7(::core::option::Option::Some(rt::service_provider(&context)));
    let value_0 = ::xaml_include_fixture_theme::compiled_xaml::build_resource_xaml(rt::cast(service_provider_0.clone(), 7, 30)?)?;
    <::ferroui_base::collections::FerroList<::std::rc::Rc<dyn ::ferroui_base::controls::IResourceProvider>>>::__markup_Add_0(&merged_dictionaries_collection_0, rt::cast(value_0.clone(), 7, 14)?);
    context.pop_parent();
    rt::invoked(::ferroui_base::StyledElement::__markup_set_Resources(user_control_0.upcast_ref::<::ferroui_base::StyledElement>(), rt::cast(resource_dictionary_0.clone(), 5, 6)?), 5, 6)?;
    // ResourceInclude_Loads_ResourceDictionary.xaml(12,2) Content
    // ResourceInclude_Loads_ResourceDictionary.xaml(12,2) Border
    let border_0 = ::ferroui_controls::Border::new();
    let source_info_2 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(12_i32, 2_i32, ::core::option::Option::Some(::std::string::String::from("ResourceInclude_Loads_ResourceDictionary.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&border_0)), rt::cast(::core::clone::Clone::clone(&source_info_2), 12, 2)?), 12, 2)?;
    border_0.begin_init();
    user_control_0.set_value(::ferroui_controls::ContentControl::content_property(), rt::to_object(::core::clone::Clone::clone(&border_0)));
    context.push_parent(rt::to_value(border_0.clone()));
    // ResourceInclude_Loads_ResourceDictionary.xaml(12,9) Name
    border_0.set_direct_value(::ferroui_base::StyledElement::name_property(), ::core::option::Option::Some(::std::string::String::from("border")));
    rt::register_name(name_scope.as_ref(), "border", ::core::clone::Clone::clone(&border_0).upcast::<::ferroui_base::FerroObject>(), 12, 9)?;
    // ResourceInclude_Loads_ResourceDictionary.xaml(12,23) Background (setter chosen at run time)
    let static_resource_extension_0 = ::ferroui_markup_xaml::markup_extensions::StaticResourceExtension::__markup_new_1(rt::to_object(::std::string::String::from("brush")));
    let source_info_3 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(12_i32, 23_i32, ::core::option::Option::Some(::std::string::String::from("ResourceInclude_Loads_ResourceDictionary.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&static_resource_extension_0)), rt::cast(::core::clone::Clone::clone(&source_info_3), 12, 23)?), 12, 23)?;
    let provided_0 = rt::provide_value_invoked(&context, rt::property_value(::ferroui_controls::Border::background_property()), &static_resource_extension_0, ::ferroui_markup_xaml::markup_extensions::StaticResourceExtension::__markup_ProvideValue_0, 12, 23)?;
    let value_1: ::ferroui_base::metadata::MarkupValue = rt::to_value(provided_0);
    if rt::is_instance(&value_1, rt::markup_handle(<::ferroui_base::UnsetValueType as ::ferroui_base::metadata::MarkupTyped>::MARKUP)) {
        rt::unset_value(border_0.upcast_ref::<::ferroui_base::FerroObject>(), ::ferroui_controls::Border::background_property());
    } else if rt::is_instance(&value_1, rt::markup_handle(<dyn ::ferroui_base::data::BindingBase as ::ferroui_base::metadata::MarkupTyped>::MARKUP)) {
        rt::bind(border_0.upcast_ref::<::ferroui_base::FerroObject>(), ::ferroui_controls::Border::background_property(), value_1.clone(), 12, 23)?;
    } else if rt::is_instance(&value_1, rt::markup_handle(<dyn ::ferroui_base::media::IBrush as ::ferroui_base::metadata::MarkupTyped>::MARKUP)) {
        border_0.set_value(::ferroui_controls::Border::background_property(), rt::exact(value_1.clone(), "FerroUI.Controls.Border.set_Background", 0, 12, 23)?);
    } else if value_1.is_none() {
        border_0.set_value(::ferroui_controls::Border::background_property(), rt::exact(value_1.clone(), "FerroUI.Controls.Border.set_Background", 0, 12, 23)?);
    } else {
        return ::core::result::Result::Err(rt::no_setter("Background", &value_1, 12, 23));
    }
    context.pop_parent();
    rt::invoked(border_0.try_end_init(), 12, 2)?;
    context.pop_parent();
    rt::invoked(user_control_0.try_end_init(), 2, 2)?;
    rt::complete_root_name_scope(::core::option::Option::Some(&user_control_0), name_scope.as_ref(), 2, 2)?;
    ::core::result::Result::Ok(user_control_0)
}

fn build_resourceinclude_loads_resourcedictionary_xaml_untyped(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException> {
    let root = build_resourceinclude_loads_resourcedictionary_xaml(service_provider)?;
    ::core::result::Result::Ok(::std::rc::Rc::new(root) as ::ferroui_base::BoxedValue)
}

/// The build function of every eligible public document, by document name.
pub const DOCUMENTS: &[(&str, BuildDocument)] = &[
    ("ResourceInclude_Loads_ResourceDictionary.xaml", build_resourceinclude_loads_resourcedictionary_xaml_untyped as BuildDocument),
];

/// The loader of the compiled markup of the assembly: builds the document with the URI
/// `uri` (compared as upstream's `OrdinalIgnoreCase`, `rt::uri_equals`); `Ok(None)` if this
/// file has no such document,
/// the load error of the build if it fails.
pub fn try_load(
    service_provider: ::core::option::Option<&::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    uri: &str,
) -> ::core::result::Result<::core::option::Option<::ferroui_base::BoxedValue>, ::ferroui_markup_xaml::XamlLoadException> {
    let ::core::option::Option::Some((_, build)) = ::core::iter::Iterator::find(&mut DOCUMENTS.iter(), |(document, _)| rt::uri_equals(uri, ROOT_URI, document)) else {
        return ::core::result::Result::Ok(::core::option::Option::None);
    };
    let provider = ::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(
        service_provider.cloned(),
    );
    build(::core::option::Option::Some(provider)).map(::core::option::Option::Some)
}

/// Registers the documents of this file as the compiled markup of the assembly.
pub fn register_compiled_xaml() {
    ::ferroui_markup_xaml::FerroXamlLoader::register_compiled_xaml(ASSEMBLY_NAME, try_load);
}
