//! Test fixture of the XAML compiler (docs/porting/xaml.md, 9.7.3 and 9.10.1,
//! stage E5): an application, the assembly `アセンブリ`, whose compiled
//! documents include documents of other crates with compiled markup (the
//! crate `xaml-include-fixture-theme`, the assembly `Tests`, and the Simple
//! theme), as upstream's build links an include of a document of a
//! referenced assembly. Not a port of an upstream project: the tests of the
//! crate are upstream's `ResourceIncludeTests`, `StyleIncludeTests` and
//! `MergeResourceIncludeTests`, run against compiled documents.
//!
//! The compiled markup is generated by the emitter of Rust source from
//! [`documents`] and the `.xamlmeta` files of the two crates, and checked in
//! (`tests/compiled_xaml_tests.rs`):
//!
//! ```text
//! cargo test -p xaml-include-fixture-application --lib tests::compiled_xaml_tests::regenerate_compiled_xaml -- --ignored
//! ```

// Generated code names the types of this crate by their absolute paths.
extern crate self as xaml_include_fixture_application;

pub mod documents;
mod locale_collection;

/// The documents of [`documents::DOCUMENTS`], compiled as one group.
#[doc(hidden)]
#[rustfmt::skip]
pub mod compiled_xaml;
/// The documents of [`documents::SOURCE_INFO_DOCUMENTS`], compiled as one group with
/// `CreateSourceInfo`.
#[doc(hidden)]
#[rustfmt::skip]
pub mod compiled_xaml_source_info;

pub use locale_collection::LocaleCollection;

use ferroui_base::metadata::MarkupAssembly;
use ferroui_base::TypeInfo;
use ferroui_markup_xaml::FerroXamlLoader;

/// The dotted namespaces of the modules of this crate.
const NAMESPACES: &[(&str, &str)] = &[("xaml_include_fixture_application", "XamlIncludeFixture.Application")];

/// What this crate states about itself for markup: the assembly `アセンブリ` of upstream's
/// `NonLatin_StyleInclude_Is_Resolved_With_Two_Files`.
pub static ASSEMBLY: MarkupAssembly = MarkupAssembly {
    name: "\u{30a2}\u{30bb}\u{30f3}\u{30d6}\u{30ea}",
    crate_name: "xaml_include_fixture_application",
    xmlns_definitions: &[],
    xmlns_prefixes: &[],
    metadata: &[],
};

const TYPES: &[&TypeInfo] = &[LocaleCollection::TYPE];

/// Registers the namespaces, the types, the assembly and the compiled markup of this
/// crate (and of the crates it is built on). Cheap and idempotent.
pub fn register_types() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        ferroui_markup_xaml::register_types();
        xaml_include_fixture_theme::register_types();
        ferroui_themes_simple::register_types();
        TypeInfo::register_namespaces(NAMESPACES);
        TypeInfo::register_all(TYPES);
        MarkupAssembly::register(&ASSEMBLY);
        // The assembly has no assets; registering the empty table makes it known to the
        // asset loader, which a load by URI asks for the assembly of the document.
        ferroui_base::platform::register_assets(ASSEMBLY.name, &[]);
        FerroXamlLoader::register_compiled_xaml(ASSEMBLY.name, compiled_xaml::try_load);
    });
}

#[cfg(test)]
mod tests;
