//! Test fixture of the XAML compiler (docs/porting/xaml.md, 9.6, 9.7.3 and
//! 9.10.1, stage E5): an application, the assembly `アセンブリ`, whose compiled
//! documents include documents of other crates with compiled markup (the
//! crate `xaml-include-fixture-theme`, the assembly `Tests`, and the Simple and
//! Fluent themes), as upstream's build links an include of a document of a
//! referenced assembly. Not a port of an upstream project: the tests of the
//! crate are upstream's `ResourceIncludeTests`, `StyleIncludeTests` and
//! `MergeResourceIncludeTests`, run against compiled documents.
//!
//! The compiled markup is generated by the build script of the crate
//! (`build.rs`, `ferroui-build`) into `OUT_DIR`, from [`documents`] and the
//! `.xamlmeta` files of the three crates and of the framework crates, which
//! Cargo hands to the script through their `links` keys: the compiled
//! documents an include is linked to, and the type models the compiler reads
//! the types from, with nothing linked for them. `tests/compiled_xaml_tests.rs`
//! compares the output with the one of the emitter run in the tests against
//! the run-time type system.

// Generated code names the types of this crate by their absolute paths.
extern crate self as xaml_include_fixture_application;

pub mod documents;

// `compiled_xaml` (the documents of [`documents::DOCUMENTS`], compiled as one group),
// `compiled_xaml_source_info` (the documents of [`documents::SOURCE_INFO_DOCUMENTS`],
// compiled as one group with `CreateSourceInfo`) and `compiled_markup` (the loader
// table of the crate and `register()`).
ferroui_markup_xaml::include_compiled_xaml!();

use ferroui_base::metadata::MarkupAssembly;
use ferroui_base::TypeInfo;

/// The dotted namespaces of the modules of this crate.
const NAMESPACES: &[(&str, &str)] = &[("xaml_include_fixture_application", "XamlIncludeFixture.Application")];

/// What this crate states about itself for markup: the assembly `アセンブリ` of upstream's
/// `NonLatin_StyleInclude_Is_Resolved_With_Two_Files`. The build script reads it from this
/// file.
pub static ASSEMBLY: MarkupAssembly = MarkupAssembly {
    name: "\u{30a2}\u{30bb}\u{30f3}\u{30d6}\u{30ea}",
    crate_name: "xaml_include_fixture_application",
    xmlns_definitions: &[],
    xmlns_prefixes: &[],
    metadata: &[],
};

/// Registers the namespaces, the assembly and the compiled markup of this crate (and
/// of the crates it is built on). Cheap and idempotent.
pub fn register_types() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        ferroui_markup_xaml::register_types();
        // The crates in the order the build script reads their type models in (the order of
        // the names of the `DEP_<CRATE>_XAML_XAMLMETA` variables): the namespace table a
        // compiled document carries lists the assemblies in the order of the type system
        // it was compiled against, which is the order of registration for the emitter run
        // in the tests of this crate.
        ferroui_themes_fluent::register_types();
        ferroui_themes_simple::register_types();
        xaml_include_fixture_theme::register_types();
        TypeInfo::register_namespaces(NAMESPACES);
        MarkupAssembly::register(&ASSEMBLY);
        // The assembly has no assets; the registration makes it known to the asset loader,
        // which a load by URI asks for the assembly of the document.
        compiled_markup::register();
    });
}

#[cfg(test)]
mod tests;
