//! Test fixture of the XAML compiler (docs/porting/xaml.md, 9.6, 9.7.3 and
//! 9.10.1, stage E5): an application, the assembly `アセンブリ`, whose compiled
//! documents include documents of other crates with compiled markup (the
//! crate `xaml-include-fixture-theme`, the assembly `Tests`, and the Simple and
//! Fluent themes), as upstream's build links an include of a document of a
//! referenced assembly. Not a port of an upstream project: the tests of the
//! crate are upstream's `ResourceIncludeTests`, `StyleIncludeTests` and
//! `MergeResourceIncludeTests`, run against compiled documents.
//!
//! The compiled markup is generated by the build script of the crate
//! (`build.rs`, `ferroui-build`) into `OUT_DIR`, from [`documents`] and the
//! `.xamlmeta` files of the three crates, which Cargo hands to the script
//! through their `links` keys. `tests/compiled_xaml_tests.rs` compares it with
//! the output of the emitter run in the tests.

// Generated code names the types of this crate by their absolute paths.
extern crate self as xaml_include_fixture_application;

pub mod documents;

// `compiled_xaml` (the documents of [`documents::DOCUMENTS`], compiled as one group),
// `compiled_xaml_source_info` (the documents of [`documents::SOURCE_INFO_DOCUMENTS`],
// compiled as one group with `CreateSourceInfo`) and `compiled_markup` (the loader
// table of the crate and `register()`).
ferroui_markup_xaml::include_compiled_xaml!();

use ferroui_base::metadata::MarkupAssembly;
use ferroui_base::TypeInfo;

/// The dotted namespaces of the modules of this crate.
const NAMESPACES: &[(&str, &str)] = &[("xaml_include_fixture_application", "XamlIncludeFixture.Application")];

include!("assembly.rs");

/// Registers the namespaces, the assembly and the compiled markup of this crate (and
/// of the crates it is built on). Cheap and idempotent.
pub fn register_types() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        ferroui_markup_xaml::register_types();
        xaml_include_fixture_theme::register_types();
        ferroui_themes_simple::register_types();
        ferroui_themes_fluent::register_types();
        TypeInfo::register_namespaces(NAMESPACES);
        MarkupAssembly::register(&ASSEMBLY);
        // The assembly has no assets; the registration makes it known to the asset loader,
        // which a load by URI asks for the assembly of the document.
        compiled_markup::register();
    });
}

#[cfg(test)]
mod tests;
