//! The compiled markup of the theme (the module `compiled_xaml`, which the
//! theme is loaded from) is generated by the build script of the crate against
//! the build-time type system: the type models of this crate and of the
//! crates it is built on, with none of them linked for its types
//! (docs/porting/xaml.md, 9.5.13). It is the document of [`SimpleTheme`] and
//! every document it includes, compiled as one group.
//!
//! The checked-in `compiled_xaml.rs` and `compiled_xaml.xamlmeta` are the
//! reference. Two tests hold the three texts together: the output of the build
//! is the checked-in file, byte for byte, and the checked-in file is the output
//! of the emitter run here against the run-time type system, where every type
//! is linked and registered and the documents are read as the run-time loader
//! reads them. Not a test of upstream.
//!
//! ```text
//! cargo test -p ferroui-themes-simple --lib tests::compiled_xaml_tests::regenerate_compiled_xaml -- --ignored
//! ```

use ferroui_base::StaticType;
use ferroui_markup_xaml_loader::rust_emitter::{generate_class_file, ClassConstructor, ClassFile, XamlMetadata};
use ferroui_markup_xaml_loader::FerroRuntimeXamlLoader;

use super::support::start_application;
use crate::SimpleTheme;

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/compiled_xaml.rs");
const METADATA_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/compiled_xaml.xamlmeta");

fn generate() -> ClassFile {
    let _app = start_application();
    crate::register_types();
    // The emitter reads the documents of the class as the run-time loader does.
    FerroRuntimeXamlLoader::register_class_document(<SimpleTheme as StaticType>::TYPE, SimpleTheme::DOCUMENT_URI);
    // The constructor is stated: the markup metadata of the theme declares `new()` next to the
    // constructor that takes the service provider, so the compiler would pick `new()`.
    // Upstream's class has the one constructor `SimpleTheme(IServiceProvider? sp = null)`.
    generate_class_file(
        <SimpleTheme as StaticType>::TYPE,
        Some(ClassConstructor::ServiceProvider("with_service_provider")),
        "::ferroui_themes_simple::compiled_xaml",
        &[],
    )
    .unwrap_or_else(|reasons| panic!("the documents of the theme are not eligible:\n{reasons}"))
}

#[test]
fn compiled_xaml_is_up_to_date() {
    let file = generate();
    let metadata = std::fs::read_to_string(METADATA_PATH).expect("compiled_xaml.xamlmeta can be read");
    assert!(
        file.metadata(&[]).to_json() == metadata,
        "compiled_xaml.xamlmeta is out of date; regenerate it with \
         `cargo test -p ferroui-themes-simple --lib tests::compiled_xaml_tests::regenerate_compiled_xaml -- --ignored`"
    );
    let generated = file.source;
    let checked_in = std::fs::read_to_string(PATH).expect("compiled_xaml.rs can be read");
    if generated != checked_in {
        let line = generated.lines().zip(checked_in.lines()).position(|(a, b)| a != b).map_or_else(
            || generated.lines().count().min(checked_in.lines().count()),
            |index| index,
        );
        panic!(
            "compiled_xaml.rs is out of date (first difference at line {}); regenerate it with \
             `cargo test -p ferroui-themes-simple --lib tests::compiled_xaml_tests::regenerate_compiled_xaml -- --ignored`",
            line + 1
        );
    }
}

/// The build script, which compiles against the type models, wrote the checked-in text:
/// every document of the theme is compiled the same by both hosts, and none is refused (a
/// refused document fails the build of the crate).
#[test]
fn build_script_output_is_the_checked_in_reference() {
    let built = include_str!(concat!(env!("OUT_DIR"), "/xaml/compiled_xaml.rs"));
    let checked_in = std::fs::read_to_string(PATH).expect("compiled_xaml.rs can be read");
    if built != checked_in {
        let line = built.lines().zip(checked_in.lines()).position(|(a, b)| a != b).unwrap_or_else(|| built.lines().count().min(checked_in.lines().count()));
        panic!("compiled_xaml.rs of the build script differs from the checked-in reference (first difference at line {})", line + 1);
    }
    // The `.xamlmeta` of the build has the same documents, next to the type model of the crate
    // and the files of the crates it is built on.
    let read = |path: &str| {
        let text = std::fs::read_to_string(path).unwrap_or_else(|error| panic!("{path} cannot be read: {error}"));
        XamlMetadata::parse(&text).unwrap_or_else(|error| panic!("{path}: {error}"))
    };
    let (built, checked_in) = (read(env!("FERROUI_XAMLMETA")), read(METADATA_PATH));
    assert_eq!((&built.name, &built.crate_name), (&checked_in.name, &checked_in.crate_name));
    assert!(built.documents == checked_in.documents, "the documents of the .xamlmeta of the build script differ from the checked-in reference");
}

#[test]
#[ignore = "writes compiled_xaml.rs and compiled_xaml.xamlmeta; run it to regenerate the checked-in output"]
fn regenerate_compiled_xaml() {
    let file = generate();
    std::fs::write(PATH, &file.source).expect("compiled_xaml.rs can be written");
    std::fs::write(METADATA_PATH, file.metadata(&[]).to_json()).expect("compiled_xaml.xamlmeta can be written");
}
