// @generated by scripts/generate_markup_types.py — do not edit
//! Markup metadata of the named colors and brushes: the static values of
//! `Colors` and `Brushes`, with the names of the managed original.

use crate::ferro_markup_type;
use crate::media::{Brushes, Color, Colors, IImmutableSolidColorBrush};
use crate::metadata::{MarkupType, MarkupTyped};
use std::rc::Rc;

// The named values are static properties in the managed original.
ferro_markup_type!(static Colors {
    namespace: "FerroUI.Media",
    static_properties: [
        AliceBlue: Color { get: || Colors::ALICE_BLUE },
        AntiqueWhite: Color { get: || Colors::ANTIQUE_WHITE },
        Aqua: Color { get: || Colors::AQUA },
        Aquamarine: Color { get: || Colors::AQUAMARINE },
        Azure: Color { get: || Colors::AZURE },
        Beige: Color { get: || Colors::BEIGE },
        Bisque: Color { get: || Colors::BISQUE },
        Black: Color { get: || Colors::BLACK },
        BlanchedAlmond: Color { get: || Colors::BLANCHED_ALMOND },
        Blue: Color { get: || Colors::BLUE },
        BlueViolet: Color { get: || Colors::BLUE_VIOLET },
        Brown: Color { get: || Colors::BROWN },
        BurlyWood: Color { get: || Colors::BURLY_WOOD },
        CadetBlue: Color { get: || Colors::CADET_BLUE },
        Chartreuse: Color { get: || Colors::CHARTREUSE },
        Chocolate: Color { get: || Colors::CHOCOLATE },
        Coral: Color { get: || Colors::CORAL },
        CornflowerBlue: Color { get: || Colors::CORNFLOWER_BLUE },
        Cornsilk: Color { get: || Colors::CORNSILK },
        Crimson: Color { get: || Colors::CRIMSON },
        Cyan: Color { get: || Colors::CYAN },
        DarkBlue: Color { get: || Colors::DARK_BLUE },
        DarkCyan: Color { get: || Colors::DARK_CYAN },
        DarkGoldenrod: Color { get: || Colors::DARK_GOLDENROD },
        DarkGray: Color { get: || Colors::DARK_GRAY },
        DarkGreen: Color { get: || Colors::DARK_GREEN },
        DarkKhaki: Color { get: || Colors::DARK_KHAKI },
        DarkMagenta: Color { get: || Colors::DARK_MAGENTA },
        DarkOliveGreen: Color { get: || Colors::DARK_OLIVE_GREEN },
        DarkOrange: Color { get: || Colors::DARK_ORANGE },
        DarkOrchid: Color { get: || Colors::DARK_ORCHID },
        DarkRed: Color { get: || Colors::DARK_RED },
        DarkSalmon: Color { get: || Colors::DARK_SALMON },
        DarkSeaGreen: Color { get: || Colors::DARK_SEA_GREEN },
        DarkSlateBlue: Color { get: || Colors::DARK_SLATE_BLUE },
        DarkSlateGray: Color { get: || Colors::DARK_SLATE_GRAY },
        DarkTurquoise: Color { get: || Colors::DARK_TURQUOISE },
        DarkViolet: Color { get: || Colors::DARK_VIOLET },
        DeepPink: Color { get: || Colors::DEEP_PINK },
        DeepSkyBlue: Color { get: || Colors::DEEP_SKY_BLUE },
        DimGray: Color { get: || Colors::DIM_GRAY },
        DodgerBlue: Color { get: || Colors::DODGER_BLUE },
        Firebrick: Color { get: || Colors::FIREBRICK },
        FloralWhite: Color { get: || Colors::FLORAL_WHITE },
        ForestGreen: Color { get: || Colors::FOREST_GREEN },
        Fuchsia: Color { get: || Colors::FUCHSIA },
        Gainsboro: Color { get: || Colors::GAINSBORO },
        GhostWhite: Color { get: || Colors::GHOST_WHITE },
        Gold: Color { get: || Colors::GOLD },
        Goldenrod: Color { get: || Colors::GOLDENROD },
        Gray: Color { get: || Colors::GRAY },
        Green: Color { get: || Colors::GREEN },
        GreenYellow: Color { get: || Colors::GREEN_YELLOW },
        Honeydew: Color { get: || Colors::HONEYDEW },
        HotPink: Color { get: || Colors::HOT_PINK },
        IndianRed: Color { get: || Colors::INDIAN_RED },
        Indigo: Color { get: || Colors::INDIGO },
        Ivory: Color { get: || Colors::IVORY },
        Khaki: Color { get: || Colors::KHAKI },
        Lavender: Color { get: || Colors::LAVENDER },
        LavenderBlush: Color { get: || Colors::LAVENDER_BLUSH },
        LawnGreen: Color { get: || Colors::LAWN_GREEN },
        LemonChiffon: Color { get: || Colors::LEMON_CHIFFON },
        LightBlue: Color { get: || Colors::LIGHT_BLUE },
        LightCoral: Color { get: || Colors::LIGHT_CORAL },
        LightCyan: Color { get: || Colors::LIGHT_CYAN },
        LightGoldenrodYellow: Color { get: || Colors::LIGHT_GOLDENROD_YELLOW },
        LightGray: Color { get: || Colors::LIGHT_GRAY },
        LightGreen: Color { get: || Colors::LIGHT_GREEN },
        LightPink: Color { get: || Colors::LIGHT_PINK },
        LightSalmon: Color { get: || Colors::LIGHT_SALMON },
        LightSeaGreen: Color { get: || Colors::LIGHT_SEA_GREEN },
        LightSkyBlue: Color { get: || Colors::LIGHT_SKY_BLUE },
        LightSlateGray: Color { get: || Colors::LIGHT_SLATE_GRAY },
        LightSteelBlue: Color { get: || Colors::LIGHT_STEEL_BLUE },
        LightYellow: Color { get: || Colors::LIGHT_YELLOW },
        Lime: Color { get: || Colors::LIME },
        LimeGreen: Color { get: || Colors::LIME_GREEN },
        Linen: Color { get: || Colors::LINEN },
        Magenta: Color { get: || Colors::MAGENTA },
        Maroon: Color { get: || Colors::MAROON },
        MediumAquamarine: Color { get: || Colors::MEDIUM_AQUAMARINE },
        MediumBlue: Color { get: || Colors::MEDIUM_BLUE },
        MediumOrchid: Color { get: || Colors::MEDIUM_ORCHID },
        MediumPurple: Color { get: || Colors::MEDIUM_PURPLE },
        MediumSeaGreen: Color { get: || Colors::MEDIUM_SEA_GREEN },
        MediumSlateBlue: Color { get: || Colors::MEDIUM_SLATE_BLUE },
        MediumSpringGreen: Color { get: || Colors::MEDIUM_SPRING_GREEN },
        MediumTurquoise: Color { get: || Colors::MEDIUM_TURQUOISE },
        MediumVioletRed: Color { get: || Colors::MEDIUM_VIOLET_RED },
        MidnightBlue: Color { get: || Colors::MIDNIGHT_BLUE },
        MintCream: Color { get: || Colors::MINT_CREAM },
        MistyRose: Color { get: || Colors::MISTY_ROSE },
        Moccasin: Color { get: || Colors::MOCCASIN },
        NavajoWhite: Color { get: || Colors::NAVAJO_WHITE },
        Navy: Color { get: || Colors::NAVY },
        OldLace: Color { get: || Colors::OLD_LACE },
        Olive: Color { get: || Colors::OLIVE },
        OliveDrab: Color { get: || Colors::OLIVE_DRAB },
        Orange: Color { get: || Colors::ORANGE },
        OrangeRed: Color { get: || Colors::ORANGE_RED },
        Orchid: Color { get: || Colors::ORCHID },
        PaleGoldenrod: Color { get: || Colors::PALE_GOLDENROD },
        PaleGreen: Color { get: || Colors::PALE_GREEN },
        PaleTurquoise: Color { get: || Colors::PALE_TURQUOISE },
        PaleVioletRed: Color { get: || Colors::PALE_VIOLET_RED },
        PapayaWhip: Color { get: || Colors::PAPAYA_WHIP },
        PeachPuff: Color { get: || Colors::PEACH_PUFF },
        Peru: Color { get: || Colors::PERU },
        Pink: Color { get: || Colors::PINK },
        Plum: Color { get: || Colors::PLUM },
        PowderBlue: Color { get: || Colors::POWDER_BLUE },
        Purple: Color { get: || Colors::PURPLE },
        Red: Color { get: || Colors::RED },
        RosyBrown: Color { get: || Colors::ROSY_BROWN },
        RoyalBlue: Color { get: || Colors::ROYAL_BLUE },
        SaddleBrown: Color { get: || Colors::SADDLE_BROWN },
        Salmon: Color { get: || Colors::SALMON },
        SandyBrown: Color { get: || Colors::SANDY_BROWN },
        SeaGreen: Color { get: || Colors::SEA_GREEN },
        SeaShell: Color { get: || Colors::SEA_SHELL },
        Sienna: Color { get: || Colors::SIENNA },
        Silver: Color { get: || Colors::SILVER },
        SkyBlue: Color { get: || Colors::SKY_BLUE },
        SlateBlue: Color { get: || Colors::SLATE_BLUE },
        SlateGray: Color { get: || Colors::SLATE_GRAY },
        Snow: Color { get: || Colors::SNOW },
        SpringGreen: Color { get: || Colors::SPRING_GREEN },
        SteelBlue: Color { get: || Colors::STEEL_BLUE },
        Tan: Color { get: || Colors::TAN },
        Teal: Color { get: || Colors::TEAL },
        Thistle: Color { get: || Colors::THISTLE },
        Tomato: Color { get: || Colors::TOMATO },
        Transparent: Color { get: || Colors::TRANSPARENT },
        Turquoise: Color { get: || Colors::TURQUOISE },
        Violet: Color { get: || Colors::VIOLET },
        Wheat: Color { get: || Colors::WHEAT },
        White: Color { get: || Colors::WHITE },
        WhiteSmoke: Color { get: || Colors::WHITE_SMOKE },
        Yellow: Color { get: || Colors::YELLOW },
        YellowGreen: Color { get: || Colors::YELLOW_GREEN },
    ],
});

// A named brush is declared with the type the managed original declares (the contract of
// an immutable solid color brush, which has `Color`); it is assignable to the properties
// that take a brush through the registered casts of the brush contracts.
ferro_markup_type!(static Brushes {
    namespace: "FerroUI.Media",
    static_properties: [
        AliceBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::alice_blue() }
        },
        AntiqueWhite: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::antique_white() }
        },
        Aqua: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::aqua() }
        },
        Aquamarine: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::aquamarine() }
        },
        Azure: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::azure() }
        },
        Beige: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::beige() }
        },
        Bisque: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::bisque() }
        },
        Black: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::black() }
        },
        BlanchedAlmond: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::blanched_almond() }
        },
        Blue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::blue() }
        },
        BlueViolet: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::blue_violet() }
        },
        Brown: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::brown() }
        },
        BurlyWood: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::burly_wood() }
        },
        CadetBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::cadet_blue() }
        },
        Chartreuse: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::chartreuse() }
        },
        Chocolate: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::chocolate() }
        },
        Coral: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::coral() }
        },
        CornflowerBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::cornflower_blue() }
        },
        Cornsilk: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::cornsilk() }
        },
        Crimson: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::crimson() }
        },
        Cyan: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::cyan() }
        },
        DarkBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_blue() }
        },
        DarkCyan: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_cyan() }
        },
        DarkGoldenrod: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_goldenrod() }
        },
        DarkGray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_gray() }
        },
        DarkGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_green() }
        },
        DarkKhaki: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_khaki() }
        },
        DarkMagenta: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_magenta() }
        },
        DarkOliveGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_olive_green() }
        },
        DarkOrange: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_orange() }
        },
        DarkOrchid: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_orchid() }
        },
        DarkRed: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_red() }
        },
        DarkSalmon: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_salmon() }
        },
        DarkSeaGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_sea_green() }
        },
        DarkSlateBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_slate_blue() }
        },
        DarkSlateGray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_slate_gray() }
        },
        DarkTurquoise: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_turquoise() }
        },
        DarkViolet: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dark_violet() }
        },
        DeepPink: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::deep_pink() }
        },
        DeepSkyBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::deep_sky_blue() }
        },
        DimGray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dim_gray() }
        },
        DodgerBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::dodger_blue() }
        },
        Firebrick: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::firebrick() }
        },
        FloralWhite: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::floral_white() }
        },
        ForestGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::forest_green() }
        },
        Fuchsia: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::fuchsia() }
        },
        Gainsboro: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::gainsboro() }
        },
        GhostWhite: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::ghost_white() }
        },
        Gold: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::gold() }
        },
        Goldenrod: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::goldenrod() }
        },
        Gray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::gray() }
        },
        Green: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::green() }
        },
        GreenYellow: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::green_yellow() }
        },
        Honeydew: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::honeydew() }
        },
        HotPink: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::hot_pink() }
        },
        IndianRed: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::indian_red() }
        },
        Indigo: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::indigo() }
        },
        Ivory: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::ivory() }
        },
        Khaki: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::khaki() }
        },
        Lavender: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::lavender() }
        },
        LavenderBlush: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::lavender_blush() }
        },
        LawnGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::lawn_green() }
        },
        LemonChiffon: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::lemon_chiffon() }
        },
        LightBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_blue() }
        },
        LightCoral: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_coral() }
        },
        LightCyan: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_cyan() }
        },
        LightGoldenrodYellow: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_goldenrod_yellow() }
        },
        LightGray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_gray() }
        },
        LightGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_green() }
        },
        LightPink: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_pink() }
        },
        LightSalmon: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_salmon() }
        },
        LightSeaGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_sea_green() }
        },
        LightSkyBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_sky_blue() }
        },
        LightSlateGray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_slate_gray() }
        },
        LightSteelBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_steel_blue() }
        },
        LightYellow: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::light_yellow() }
        },
        Lime: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::lime() }
        },
        LimeGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::lime_green() }
        },
        Linen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::linen() }
        },
        Magenta: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::magenta() }
        },
        Maroon: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::maroon() }
        },
        MediumAquamarine: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_aquamarine() }
        },
        MediumBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_blue() }
        },
        MediumOrchid: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_orchid() }
        },
        MediumPurple: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_purple() }
        },
        MediumSeaGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_sea_green() }
        },
        MediumSlateBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_slate_blue() }
        },
        MediumSpringGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_spring_green() }
        },
        MediumTurquoise: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_turquoise() }
        },
        MediumVioletRed: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::medium_violet_red() }
        },
        MidnightBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::midnight_blue() }
        },
        MintCream: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::mint_cream() }
        },
        MistyRose: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::misty_rose() }
        },
        Moccasin: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::moccasin() }
        },
        NavajoWhite: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::navajo_white() }
        },
        Navy: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::navy() }
        },
        OldLace: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::old_lace() }
        },
        Olive: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::olive() }
        },
        OliveDrab: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::olive_drab() }
        },
        Orange: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::orange() }
        },
        OrangeRed: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::orange_red() }
        },
        Orchid: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::orchid() }
        },
        PaleGoldenrod: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::pale_goldenrod() }
        },
        PaleGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::pale_green() }
        },
        PaleTurquoise: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::pale_turquoise() }
        },
        PaleVioletRed: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::pale_violet_red() }
        },
        PapayaWhip: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::papaya_whip() }
        },
        PeachPuff: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::peach_puff() }
        },
        Peru: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::peru() }
        },
        Pink: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::pink() }
        },
        Plum: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::plum() }
        },
        PowderBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::powder_blue() }
        },
        Purple: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::purple() }
        },
        Red: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::red() }
        },
        RosyBrown: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::rosy_brown() }
        },
        RoyalBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::royal_blue() }
        },
        SaddleBrown: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::saddle_brown() }
        },
        Salmon: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::salmon() }
        },
        SandyBrown: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::sandy_brown() }
        },
        SeaGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::sea_green() }
        },
        SeaShell: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::sea_shell() }
        },
        Sienna: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::sienna() }
        },
        Silver: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::silver() }
        },
        SkyBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::sky_blue() }
        },
        SlateBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::slate_blue() }
        },
        SlateGray: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::slate_gray() }
        },
        Snow: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::snow() }
        },
        SpringGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::spring_green() }
        },
        SteelBlue: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::steel_blue() }
        },
        Tan: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::tan() }
        },
        Teal: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::teal() }
        },
        Thistle: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::thistle() }
        },
        Tomato: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::tomato() }
        },
        Transparent: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::transparent() }
        },
        Turquoise: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::turquoise() }
        },
        Violet: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::violet() }
        },
        Wheat: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::wheat() }
        },
        White: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::white() }
        },
        WhiteSmoke: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::white_smoke() }
        },
        Yellow: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::yellow() }
        },
        YellowGreen: Rc<dyn IImmutableSolidColorBrush> {
            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::yellow_green() }
        },
    ],
});

/// The types declared in this file.
pub(super) const TYPES: &[&MarkupType] = &[<Colors as MarkupTyped>::MARKUP, <Brushes as MarkupTyped>::MARKUP];
