#!/bin/bash
# Installs the pinned toolchain of the browser target next to the repository and prints how to
# use it. Works on Linux and macOS; nothing outside the tools directory is changed.
#
#   scripts/browser/setup.sh [<tools directory>]        default: <repository>/.tools
#   scripts/browser/setup.sh --threads [<tools directory>]   also the toolchain of the threaded mode
#   source <tools directory>/env.sh                      then: scripts/build-browser.sh <example>
#
# Installs: the Emscripten SDK (pinned version, from github.com/emscripten-core/emsdk), the Rust
# target wasm32-unknown-emscripten for the pinned Rust toolchain, and the wasm-bindgen command-line
# tool of the version the workspace uses (from crates.io). The pins are explained in
# docs/porting/browser-platform.md, section 3; change them there and here together. CI installs the
# toolchain with this script too (.github/actions/browser-toolchain), reading the pins from it.
#
# --threads also installs the nightly Rust toolchain that `scripts/build-browser.sh --threads` builds
# with, with the source of the standard library (the threaded build compiles it with atomics,
# -Zbuild-std) and the target, and builds the Skia binaries of the threaded mode: the published
# binaries with the bindings shim compiled again with threads (scripts/browser/skia-threads-shim.sh,
# which says why; the result is kept in <tools directory>/skia-threads and built once, and it needs
# python3 and about 200 MB of downloads). Everything else, env.sh included, is the same with and
# without the option: the build script selects the nightly itself and reads the pin from this file.
set -euo pipefail

EMSDK_VERSION="6.0.10"
# 1.93 or later: from 1.93 Rust unwinds with WebAssembly exceptions on wasm32-unknown-emscripten and
# links with -fwasm-exceptions; 1.98 removed the JavaScript variant (docs/porting/browser-platform.md,
# section 3). The browser build of ferroui-skia refuses older releases (src/Skia/FerroUI.Skia/build.rs).
# The desktop builds use the stable toolchain of rustup and do not read this pin.
RUST_VERSION="1.99.0"
# The toolchain of the threaded mode (--threads). A nightly, because -Zbuild-std is not available on
# a stable release. This date is in the last days of the 1.99 development cycle (1.99 left the main
# branch for beta in early July 2026), so the compiler is as close to the stable pin as a nightly
# gets and has the unwinding with WebAssembly exceptions that the stable pin exists for. The
# feasibility check of the mode (docs/porting/render-thread.md, stage B0) ran a plain program on
# nightly-2025-10-31, which reports 1.93.0 but precedes the change of the unwinding ABI (merged
# 2025-12-05) and cannot build the port's module. Not built with yet: if this date has no nightly
# or it lacks a component, take the nearest one that has them and change the date here.
RUST_NIGHTLY="nightly-2026-07-01"

# The one option; the tools directory stays the first argument that is left.
THREADS=""
for ARGUMENT in "$@"; do
  shift
  if [ "$ARGUMENT" = "--threads" ]; then THREADS="1"; else set -- "$@" "$ARGUMENT"; fi
done

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TOOLS="${1:-$ROOT/.tools}"
mkdir -p "$TOOLS"
TOOLS="$(cd "$TOOLS" && pwd)"

WASM_BINDGEN_VERSION="$(sed -n 's/^wasm-bindgen = "=\(.*\)"$/\1/p' "$ROOT/Cargo.toml")"
[ -n "$WASM_BINDGEN_VERSION" ] || { echo "cannot read the wasm-bindgen version from Cargo.toml" >&2; exit 1; }

echo "== Emscripten SDK $EMSDK_VERSION"
if [ ! -x "$TOOLS/emsdk/emsdk" ]; then
  git clone --depth 1 https://github.com/emscripten-core/emsdk "$TOOLS/emsdk"
fi
if ! "$TOOLS/emsdk/emsdk" list 2>/dev/null | grep -q "$EMSDK_VERSION.*INSTALLED"; then
  "$TOOLS/emsdk/emsdk" install "$EMSDK_VERSION" >/dev/null
fi
"$TOOLS/emsdk/emsdk" activate "$EMSDK_VERSION" >/dev/null

echo "== Rust $RUST_VERSION with wasm32-unknown-emscripten"
rustup toolchain install "$RUST_VERSION" --profile minimal --target wasm32-unknown-emscripten >/dev/null

if [ -n "$THREADS" ]; then
  echo "== Rust $RUST_NIGHTLY with rust-src and wasm32-unknown-emscripten (threaded mode)"
  rustup toolchain install "$RUST_NIGHTLY" --profile minimal --component rust-src \
    --target wasm32-unknown-emscripten >/dev/null
fi

echo "== wasm-bindgen $WASM_BINDGEN_VERSION"
if [ "$("$TOOLS/bin/wasm-bindgen" --version 2>/dev/null | awk '{print $2}')" != "$WASM_BINDGEN_VERSION" ]; then
  CARGO_TARGET_DIR="$TOOLS/target-install" cargo "+$RUST_VERSION" install wasm-bindgen-cli \
    --version "$WASM_BINDGEN_VERSION" --locked --root "$TOOLS" --force
  rm -rf "$TOOLS/target-install"
fi

cat > "$TOOLS/env.sh" <<ENV
# Environment of the browser build. Generated by scripts/browser/setup.sh; source it.
source "$TOOLS/emsdk/emsdk_env.sh" >/dev/null 2>&1
export PATH="$TOOLS/bin:\$PATH"
export RUSTUP_TOOLCHAIN="$RUST_VERSION"
# Skia's prebuilt binaries leave symbols to the linker of the application.
export EMCC_CFLAGS="-s ERROR_ON_UNDEFINED_SYMBOLS=0"
ENV

# shellcheck disable=SC1091
source "$TOOLS/env.sh"
emcc --version | head -1
wasm-bindgen --version
rustc --version
if [ -n "$THREADS" ]; then
  echo "== Skia bindings shim compiled for threads"
  "$ROOT/scripts/browser/skia-threads-shim.sh" "$TOOLS"
fi
echo
echo "ready: source $TOOLS/env.sh"
if [ -n "$THREADS" ]; then
  echo "threaded mode: $(rustc "+$RUST_NIGHTLY" --version); build with scripts/build-browser.sh <example> --threads"
fi
