// @generated by scripts/generate_markup_types.py — do not edit
//! The public Rust paths of the registered types of this crate: every class of
//! the type table and every non-generic markup type of the type lists, by the
//! shortest path another crate names it by (`scripts/rust_paths.py`). The emitter
//! of Rust source of the markup compiler reads them; nothing else does.

ferroui_base::ferro_rust_paths! {
    classes: [
        crate::ColorPicker,
        crate::ColorView,
        crate::automation::peers::ColorSpectrumAutomationPeer,
        crate::primitives::ColorPreviewer,
        crate::primitives::ColorSlider,
        crate::primitives::ColorSpectrum,
    ],
    types: [
        crate::AlphaComponentPosition,
        crate::ColorComponent,
        crate::ColorModel,
        crate::ColorSpectrumComponents,
        crate::ColorSpectrumShape,
        crate::ColorViewTab,
        crate::FlatColor,
        crate::FlatColorPalette,
        crate::FlatHalfColorPalette,
        crate::FluentColorPalette,
        crate::HsvComponent,
        crate::MaterialColor,
        crate::MaterialColorPalette,
        crate::MaterialHalfColorPalette,
        crate::RgbComponent,
        crate::SixteenColorPalette,
        crate::converters::ColorToDisplayNameConverter,
        crate::converters::ColorToHexConverter,
        crate::converters::DoNothingForNullConverter,
        crate::converters::ToBrushConverter,
        crate::converters::ToColorConverter,
        crate::primitives::ColorHelper,
        crate::primitives::converters::AccentColorConverter,
        crate::primitives::converters::ContrastBrushConverter,
    ],
    contracts: [
        crate::IColorPalette,
    ],
    generics: [
    ],
    generic_contracts: [
    ],
}
