//! Compiles the documents of the crate that name types of other crates only
//! (`documents::DOCUMENTS`, and `documents::SOURCE_INFO_DOCUMENTS` with
//! `CreateSourceInfo`) to `$OUT_DIR/xaml/`, and writes the `.xamlmeta` of the
//! crate for the crates that include its documents
//! (docs/porting/xaml.md, 9.6).
//!
//! The document of `StyleWithServiceProvider` is the document of a class of
//! this crate, which a build script cannot link: it stays generated by a test
//! and checked in (`compiled_style_with_service_provider.rs`), and its loader
//! table and its `.xamlmeta` join the ones of the build here.

use ferroui_build::{Build, XamlGroup};
use ferroui_controls::testing::{TestServices, UnitTestApplication};

include!("assembly.rs");

#[allow(dead_code)]
#[path = "documents.rs"]
mod documents;

fn main() {
    // The services the generator of the checked-in files runs with.
    let _app = UnitTestApplication::start(TestServices::styled_window());
    Build::from_env()
        .assembly(&ASSEMBLY)
        .input("assembly.rs")
        .input("documents.rs")
        .compile_group(XamlGroup::new("compiled_xaml").documents(documents::DOCUMENTS))
        .compile_group(
            XamlGroup::new("compiled_xaml_source_info")
                .documents(documents::SOURCE_INFO_DOCUMENTS)
                .create_source_info(true)
                .internal(),
        )
        .loader("crate::compiled_style_with_service_provider::try_load")
        .checked_in_metadata("compiled_style_with_service_provider.xamlmeta")
        .run();
}
