// @generated by the Rust emitter of ferroui-markup-xaml-loader (rust_emitter::generate_file).
// Do not edit: regenerate it (see the header of the module that includes this file).

#[allow(unused_imports)]
use ::ferroui_markup_xaml::xaml_il::runtime::compiled as rt;

/// The assembly the documents of this file belong to.
pub const ASSEMBLY_NAME: &str = "Tests";

/// The URI of a document is this followed by its name.
pub const ROOT_URI: &str = "ferres://Tests/";

/// An untyped build function: the root object as the loader returns it.
pub type BuildDocument = fn(
    ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException>;

/// The XML namespaces of documents of this file, as the compiler resolved them.
const XML_NAMESPACES_0: rt::XmlNamespaceTable = &[
    ("", &[("FerroUI", "FerroUI.Base"), ("FerroUI.Animation", "FerroUI.Base"), ("FerroUI.Animation.Easings", "FerroUI.Base"), ("FerroUI.Controls", "FerroUI.Base"), ("FerroUI.Data", "FerroUI.Base"), ("FerroUI.Data.Converters", "FerroUI.Base"), ("FerroUI.Input", "FerroUI.Base"), ("FerroUI.Input.GestureRecognizers", "FerroUI.Base"), ("FerroUI.Input.TextInput", "FerroUI.Base"), ("FerroUI.Layout", "FerroUI.Base"), ("FerroUI.LogicalTree", "FerroUI.Base"), ("FerroUI.Media", "FerroUI.Base"), ("FerroUI.Media.Imaging", "FerroUI.Base"), ("FerroUI.Media.Transformation", "FerroUI.Base"), ("FerroUI.Styling", "FerroUI.Base"), ("FerroUI", "FerroUI.Controls"), ("FerroUI.Automation", "FerroUI.Controls"), ("FerroUI.Controls", "FerroUI.Controls"), ("FerroUI.Controls.Embedding", "FerroUI.Controls"), ("FerroUI.Controls.Presenters", "FerroUI.Controls"), ("FerroUI.Controls.Primitives", "FerroUI.Controls"), ("FerroUI.Controls.Shapes", "FerroUI.Controls"), ("FerroUI.Controls.Templates", "FerroUI.Controls"), ("FerroUI.Controls.Notifications", "FerroUI.Controls"), ("FerroUI.Controls.Chrome", "FerroUI.Controls"), ("FerroUI.Controls.Documents", "FerroUI.Controls"), ("FerroUI.Markup.Xaml.MarkupExtensions", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Styling", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Templates", "FerroUI.Markup.Xaml")]),
    ("x", &[]),
];

/// The base URI and the XML namespaces of `Resources.xaml`.
static BUILD_RESOURCES_XAML_DOCUMENT: rt::DocumentInfo = rt::DocumentInfo { base_uri: ::core::option::Option::Some("ferres://Tests/Resources.xaml"), namespaces: XML_NAMESPACES_0 };

/// Generated from `Resources.xaml`.
pub fn build_resources_xaml(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::Ref<::ferroui_base::controls::ResourceDictionary>, ::ferroui_markup_xaml::XamlLoadException> {
    // Resources.xaml(2,2) ResourceDictionary
    let resource_dictionary_0 = ::ferroui_base::controls::ResourceDictionary::new();
    let source_info_0 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(2_i32, 2_i32, ::core::option::Option::Some(::std::string::String::from("Resources.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&resource_dictionary_0)), rt::cast(::core::clone::Clone::clone(&source_info_0), 2, 2)?), 2, 2)?;
    let context = rt::populate_context(service_provider, &BUILD_RESOURCES_XAML_DOCUMENT, rt::to_value(resource_dictionary_0.clone()));
    let name_scope = context.name_scope_field();
    // Resources.xaml(4,37) Content (resource)
    let deferred_0 = rt::defer(::ferroui_base::data::core::ValueType::object(), &context, build_resources_xaml_deferred_0, 4, 37)?;
    let key_0 = ::std::string::String::from("brush2");
    rt::invoked(::ferroui_base::controls::ResourceDictionary::__markup_AddDeferred_1(&resource_dictionary_0, rt::to_object(::core::clone::Clone::clone(&key_0)), ::core::clone::Clone::clone(&deferred_0) as ::std::rc::Rc<dyn ::ferroui_base::controls::IDeferredContent>), 4, 37)?;
    let source_info_1 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(4_i32, 37_i32, ::core::option::Option::Some(::std::string::String::from("Resources.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_1(rt::cast(resource_dictionary_0.clone(), 4, 37)?, rt::to_object(::core::clone::Clone::clone(&key_0)), rt::cast(::core::clone::Clone::clone(&source_info_1), 4, 37)?), 4, 37)?;
    rt::complete_root_name_scope(::core::option::Option::None, name_scope.as_ref(), 2, 2)?;
    ::core::result::Result::Ok(resource_dictionary_0)
}

/// Builds the deferred content at `Resources.xaml(4,37)` (a template or a deferred resource).
fn build_resources_xaml_deferred_0(
    service_provider: &::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>,
) -> ::core::result::Result<::ferroui_base::metadata::MarkupValue, ::ferroui_markup_xaml::XamlLoadException> {
    let _context = rt::deferred_context(service_provider, &BUILD_RESOURCES_XAML_DOCUMENT);
    let immutable_solid_color_brush_0 = ::ferroui_base::media::immutable::ImmutableSolidColorBrush::__markup_new_0(4294901760_u32);
    let source_info_0 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(4_i32, 37_i32, ::core::option::Option::Some(::std::string::String::from("Resources.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&immutable_solid_color_brush_0)), rt::cast(::core::clone::Clone::clone(&source_info_0), 4, 37)?), 4, 37)?;
    ::core::result::Result::Ok(rt::to_value(immutable_solid_color_brush_0))
}

fn build_resources_xaml_untyped(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException> {
    let root = build_resources_xaml(service_provider)?;
    ::core::result::Result::Ok(::std::rc::Rc::new(root) as ::ferroui_base::BoxedValue)
}

/// The base URI and the XML namespaces of `MergeResourceInclude_Works_With_Single_Resource.xaml`.
static BUILD_MERGERESOURCEINCLUDE_WORKS_WITH_SINGLE_RESOURCE_XAML_DOCUMENT: rt::DocumentInfo = rt::DocumentInfo { base_uri: ::core::option::Option::Some("ferres://Tests/MergeResourceInclude_Works_With_Single_Resource.xaml"), namespaces: XML_NAMESPACES_0 };

/// Generated from `MergeResourceInclude_Works_With_Single_Resource.xaml`.
pub fn build_mergeresourceinclude_works_with_single_resource_xaml(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::Ref<::ferroui_controls::UserControl>, ::ferroui_markup_xaml::XamlLoadException> {
    // MergeResourceInclude_Works_With_Single_Resource.xaml(2,2) UserControl
    let user_control_0 = ::ferroui_controls::UserControl::new();
    let source_info_0 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(2_i32, 2_i32, ::core::option::Option::Some(::std::string::String::from("MergeResourceInclude_Works_With_Single_Resource.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&user_control_0)), rt::cast(::core::clone::Clone::clone(&source_info_0), 2, 2)?), 2, 2)?;
    let context = rt::populate_context(service_provider, &BUILD_MERGERESOURCEINCLUDE_WORKS_WITH_SINGLE_RESOURCE_XAML_DOCUMENT, rt::to_value(user_control_0.clone()));
    let name_scope = context.name_scope_field();
    user_control_0.begin_init();
    // MergeResourceInclude_Works_With_Single_Resource.xaml(5,10) Resources
    // MergeResourceInclude_Works_With_Single_Resource.xaml(5,10) ResourceDictionary
    let resource_dictionary_0 = ::ferroui_base::controls::ResourceDictionary::new();
    let source_info_1 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(5_i32, 10_i32, ::core::option::Option::Some(::std::string::String::from("MergeResourceInclude_Works_With_Single_Resource.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&resource_dictionary_0)), rt::cast(::core::clone::Clone::clone(&source_info_1), 5, 10)?), 5, 10)?;
    let resources_0: ::ferroui_base::metadata::MarkupValue = rt::to_value(resource_dictionary_0.clone());
    if rt::is_instance(&resources_0, rt::class_handle(<::ferroui_base::controls::ResourceDictionary as ::ferroui_base::StaticType>::TYPE)) {
        let count_0: i32 = ::ferroui_base::controls::ResourceDictionary::__markup_get_Count(&rt::exact(resources_0.clone(), "FerroUI.Controls.ResourceDictionary.get_Count", 0, 5, 10)?);
        ::ferroui_base::controls::ResourceDictionary::__markup_EnsureCapacity_3(&rt::exact(resources_0.clone(), "FerroUI.Controls.ResourceDictionary.EnsureCapacity", 0, 5, 10)?, count_0.wrapping_add(2_i32));
    }
    // MergeResourceInclude_Works_With_Single_Resource.xaml(4,37) Content (resource)
    let deferred_0 = rt::defer(::ferroui_base::data::core::ValueType::object(), &context, build_mergeresourceinclude_works_with_single_resource_xaml_deferred_0, 4, 37)?;
    let key_0 = ::std::string::String::from("brush2");
    rt::invoked(::ferroui_base::controls::ResourceDictionary::__markup_AddDeferred_1(&resource_dictionary_0, rt::to_object(::core::clone::Clone::clone(&key_0)), ::core::clone::Clone::clone(&deferred_0) as ::std::rc::Rc<dyn ::ferroui_base::controls::IDeferredContent>), 4, 37)?;
    let source_info_2 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(4_i32, 37_i32, ::core::option::Option::Some(::std::string::String::from("Resources.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_1(rt::cast(resource_dictionary_0.clone(), 4, 37)?, rt::to_object(::core::clone::Clone::clone(&key_0)), rt::cast(::core::clone::Clone::clone(&source_info_2), 4, 37)?), 4, 37)?;
    // MergeResourceInclude_Works_With_Single_Resource.xaml(6,45) Content (resource)
    let deferred_1 = rt::defer(::ferroui_base::data::core::ValueType::object(), &context, build_mergeresourceinclude_works_with_single_resource_xaml_deferred_1, 6, 45)?;
    let key_1 = ::std::string::String::from("brush1");
    rt::invoked(::ferroui_base::controls::ResourceDictionary::__markup_AddDeferred_1(&resource_dictionary_0, rt::to_object(::core::clone::Clone::clone(&key_1)), ::core::clone::Clone::clone(&deferred_1) as ::std::rc::Rc<dyn ::ferroui_base::controls::IDeferredContent>), 6, 45)?;
    let source_info_3 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(6_i32, 45_i32, ::core::option::Option::Some(::std::string::String::from("MergeResourceInclude_Works_With_Single_Resource.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_1(rt::cast(resource_dictionary_0.clone(), 6, 45)?, rt::to_object(::core::clone::Clone::clone(&key_1)), rt::cast(::core::clone::Clone::clone(&source_info_3), 6, 45)?), 6, 45)?;
    rt::invoked(::ferroui_base::StyledElement::__markup_set_Resources(user_control_0.upcast_ref::<::ferroui_base::StyledElement>(), rt::cast(resource_dictionary_0.clone(), 5, 10)?), 5, 10)?;
    rt::invoked(user_control_0.try_end_init(), 2, 2)?;
    rt::complete_root_name_scope(::core::option::Option::Some(&user_control_0), name_scope.as_ref(), 2, 2)?;
    ::core::result::Result::Ok(user_control_0)
}

/// Builds the deferred content at `MergeResourceInclude_Works_With_Single_Resource.xaml(4,37)` (a template or a deferred resource).
fn build_mergeresourceinclude_works_with_single_resource_xaml_deferred_0(
    service_provider: &::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>,
) -> ::core::result::Result<::ferroui_base::metadata::MarkupValue, ::ferroui_markup_xaml::XamlLoadException> {
    let _context = rt::deferred_context(service_provider, &BUILD_MERGERESOURCEINCLUDE_WORKS_WITH_SINGLE_RESOURCE_XAML_DOCUMENT);
    let immutable_solid_color_brush_0 = ::ferroui_base::media::immutable::ImmutableSolidColorBrush::__markup_new_0(4294901760_u32);
    let source_info_0 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(4_i32, 37_i32, ::core::option::Option::Some(::std::string::String::from("Resources.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&immutable_solid_color_brush_0)), rt::cast(::core::clone::Clone::clone(&source_info_0), 4, 37)?), 4, 37)?;
    ::core::result::Result::Ok(rt::to_value(immutable_solid_color_brush_0))
}

/// Builds the deferred content at `MergeResourceInclude_Works_With_Single_Resource.xaml(6,45)` (a template or a deferred resource).
fn build_mergeresourceinclude_works_with_single_resource_xaml_deferred_1(
    service_provider: &::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>,
) -> ::core::result::Result<::ferroui_base::metadata::MarkupValue, ::ferroui_markup_xaml::XamlLoadException> {
    let _context = rt::deferred_context(service_provider, &BUILD_MERGERESOURCEINCLUDE_WORKS_WITH_SINGLE_RESOURCE_XAML_DOCUMENT);
    let immutable_solid_color_brush_0 = ::ferroui_base::media::immutable::ImmutableSolidColorBrush::__markup_new_0(4278190335_u32);
    let source_info_0 = ::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_new_0(6_i32, 45_i32, ::core::option::Option::Some(::std::string::String::from("MergeResourceInclude_Works_With_Single_Resource.xaml")));
    rt::invoked(::ferroui_markup_xaml::diagnostics::XamlSourceInfo::__markup_SetXamlSourceInfo_0(rt::to_object(::core::clone::Clone::clone(&immutable_solid_color_brush_0)), rt::cast(::core::clone::Clone::clone(&source_info_0), 6, 45)?), 6, 45)?;
    ::core::result::Result::Ok(rt::to_value(immutable_solid_color_brush_0))
}

fn build_mergeresourceinclude_works_with_single_resource_xaml_untyped(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
) -> ::core::result::Result<::ferroui_base::BoxedValue, ::ferroui_markup_xaml::XamlLoadException> {
    let root = build_mergeresourceinclude_works_with_single_resource_xaml(service_provider)?;
    ::core::result::Result::Ok(::std::rc::Rc::new(root) as ::ferroui_base::BoxedValue)
}

/// The build function of every eligible public document, by document name.
pub const DOCUMENTS: &[(&str, BuildDocument)] = &[
    ("Resources.xaml", build_resources_xaml_untyped as BuildDocument),
    ("MergeResourceInclude_Works_With_Single_Resource.xaml", build_mergeresourceinclude_works_with_single_resource_xaml_untyped as BuildDocument),
];

/// The loader of the compiled markup of the assembly: builds the document with the URI
/// `uri` (compared as upstream's `OrdinalIgnoreCase`, `rt::uri_equals`); `Ok(None)` if this
/// file has no such document,
/// the load error of the build if it fails.
pub fn try_load(
    service_provider: ::core::option::Option<&::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    uri: &str,
) -> ::core::result::Result<::core::option::Option<::ferroui_base::BoxedValue>, ::ferroui_markup_xaml::XamlLoadException> {
    let ::core::option::Option::Some((_, build)) = ::core::iter::Iterator::find(&mut DOCUMENTS.iter(), |(document, _)| rt::uri_equals(uri, ROOT_URI, document)) else {
        return ::core::result::Result::Ok(::core::option::Option::None);
    };
    let provider = ::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(
        service_provider.cloned(),
    );
    build(::core::option::Option::Some(provider)).map(::core::option::Option::Some)
}

/// Registers the documents of this file as the compiled markup of the assembly.
pub fn register_compiled_xaml() {
    ::ferroui_markup_xaml::FerroXamlLoader::register_compiled_xaml(ASSEMBLY_NAME, try_load);
}
