// @generated by the Rust emitter of ferroui-markup-xaml-loader (rust_emitter::generate_class_file).
// Do not edit: regenerate it (see the header of the module that includes this file).
// The document of `XamlIncludeFixture.Theme.StyleWithServiceProvider` and the 0 it calls, of a group of 1 documents.

#![allow(dead_code, unused_imports)]

use ::ferroui_markup_xaml::xaml_il::runtime::compiled as rt;

/// The XML namespaces of documents of this file, as the compiler resolved them.
const XML_NAMESPACES_0: rt::XmlNamespaceTable = &[
    ("", &[("FerroUI", "FerroUI.Base"), ("FerroUI.Animation", "FerroUI.Base"), ("FerroUI.Animation.Easings", "FerroUI.Base"), ("FerroUI.Controls", "FerroUI.Base"), ("FerroUI.Data", "FerroUI.Base"), ("FerroUI.Data.Converters", "FerroUI.Base"), ("FerroUI.Input", "FerroUI.Base"), ("FerroUI.Input.GestureRecognizers", "FerroUI.Base"), ("FerroUI.Input.TextInput", "FerroUI.Base"), ("FerroUI.Layout", "FerroUI.Base"), ("FerroUI.LogicalTree", "FerroUI.Base"), ("FerroUI.Media", "FerroUI.Base"), ("FerroUI.Media.Imaging", "FerroUI.Base"), ("FerroUI.Media.Transformation", "FerroUI.Base"), ("FerroUI.Styling", "FerroUI.Base"), ("FerroUI", "FerroUI.Controls"), ("FerroUI.Automation", "FerroUI.Controls"), ("FerroUI.Controls", "FerroUI.Controls"), ("FerroUI.Controls.Embedding", "FerroUI.Controls"), ("FerroUI.Controls.Presenters", "FerroUI.Controls"), ("FerroUI.Controls.Primitives", "FerroUI.Controls"), ("FerroUI.Controls.Shapes", "FerroUI.Controls"), ("FerroUI.Controls.Templates", "FerroUI.Controls"), ("FerroUI.Controls.Notifications", "FerroUI.Controls"), ("FerroUI.Controls.Chrome", "FerroUI.Controls"), ("FerroUI.Controls.Documents", "FerroUI.Controls"), ("FerroUI.Markup.Xaml.MarkupExtensions", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Styling", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Templates", "FerroUI.Markup.Xaml")]),
    ("x", &[]),
];

/// Populates `root` from the document of the class (`populate_xaml_stylewithserviceprovider_xaml`), with a root service provider
/// over `service_provider` (`XamlIlRuntimeHelpers.CreateRootServiceProviderV3`), as the
/// run-time loader populates it.
pub fn populate(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    root: &::ferroui_base::Ref<crate::StyleWithServiceProvider>,
) -> ::core::result::Result<(), ::ferroui_markup_xaml::XamlLoadException> {
    let service_provider =
        ::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(service_provider);
    populate_xaml_stylewithserviceprovider_xaml(::core::option::Option::Some(service_provider), root)
}

/// The base URI and the XML namespaces of `Xaml/StyleWithServiceProvider.xaml`.
static POPULATE_XAML_STYLEWITHSERVICEPROVIDER_XAML_DOCUMENT: rt::DocumentInfo = rt::DocumentInfo { base_uri: ::core::option::Option::Some("ferres://tests/Xaml/StyleWithServiceProvider.xaml"), namespaces: XML_NAMESPACES_0 };

/// Generated from `Xaml/StyleWithServiceProvider.xaml`.
pub fn populate_xaml_stylewithserviceprovider_xaml(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    root: &::ferroui_base::Ref<crate::StyleWithServiceProvider>,
) -> ::core::result::Result<(), ::ferroui_markup_xaml::XamlLoadException> {
    let root = root.clone();
    let context = rt::populate_context(service_provider, &POPULATE_XAML_STYLEWITHSERVICEPROVIDER_XAML_DOCUMENT, rt::to_value(root.clone()));
    let name_scope = context.name_scope_field();
    rt::complete_root_name_scope(::core::option::Option::None, name_scope.as_ref(), 1, 2)?;
    ::core::result::Result::Ok(())
}

/// The loader of the compiled documents of this file (`!XamlLoader.TryLoad`): the object of the
/// public document with the URI `uri` (compared as upstream's `OrdinalIgnoreCase`,
/// `rt::uri_equals`); `Ok(None)` if this file has no such document, the load error of the build
/// if it fails.
pub fn try_load(
    service_provider: ::core::option::Option<&::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    uri: &str,
) -> ::core::result::Result<::core::option::Option<::ferroui_base::BoxedValue>, ::ferroui_markup_xaml::XamlLoadException> {
    if rt::uri_equals(uri, "ferres://tests/Xaml/StyleWithServiceProvider.xaml", "") {
        return ::core::result::Result::Ok(::ferroui_base::metadata::into_markup_value(crate::StyleWithServiceProvider::__markup_new_0(::core::option::Option::Some(::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(service_provider.cloned())))));
    }
    ::core::result::Result::Ok(::core::option::Option::None)
}
