//! Test fixture of the XAML compiler (docs/porting/xaml.md, 9.6, 9.7.3 and
//! 9.10.1, stage E5): a library with compiled markup, the assembly `Tests`,
//! whose documents the crate `xaml-include-fixture-application` includes. Not a
//! port of an upstream project: it holds the documents of upstream's include
//! tests that belong to the assembly the tests include from
//! ([`documents`]), and the types of upstream's test assembly those documents
//! and the documents of the application name.
//!
//! The compiled markup of every document of the crate is generated by its
//! build script (`build.rs`, `ferroui-build`) into `OUT_DIR`, with the
//! `.xamlmeta` that describes the compiled markup and the types of the crate
//! to the crates that include its documents: the documents without a class,
//! and the document of [`StyleWithServiceProvider`], a class of this crate.
//! The build script compiles against the type models (the scan of these
//! sources and the models of the framework crates), so it links none of them
//! and compiles a document that names a type of the crate it builds.
//! `tests/compiled_xaml_tests.rs` compares what it wrote with the output of
//! the emitter run in the tests against the run-time type system.

pub mod documents;
mod locale_collection;
mod rust_paths;
mod style_with_service_provider;

// `compiled_xaml` (the documents of [`documents::DOCUMENTS`], compiled as one group),
// `compiled_xaml_source_info` (the documents of [`documents::SOURCE_INFO_DOCUMENTS`],
// compiled as one group with `CreateSourceInfo`), `compiled_style_with_service_provider`
// (the document of [`StyleWithServiceProvider`]) and `compiled_markup` (the loader table
// of the crate and `register()`).
ferroui_markup_xaml::include_compiled_xaml!();

pub use locale_collection::LocaleCollection;
pub use style_with_service_provider::StyleWithServiceProvider;

use ferroui_base::TypeInfo;

/// The dotted namespaces of the modules of this crate.
const NAMESPACES: &[(&str, &str)] = &[("xaml_include_fixture_theme", "XamlIncludeFixture.Theme")];

/// What this crate states about itself for markup: the assembly `Tests` of upstream's tests.
/// The build script reads it from this file.
pub static ASSEMBLY: ::ferroui_base::metadata::MarkupAssembly = ::ferroui_base::metadata::MarkupAssembly {
    name: "Tests",
    crate_name: "xaml_include_fixture_theme",
    xmlns_definitions: &[],
    xmlns_prefixes: &[],
    metadata: &[],
};

const TYPES: &[&TypeInfo] = &[LocaleCollection::TYPE, StyleWithServiceProvider::TYPE];

/// Registers the namespaces, the types, the assembly and the compiled markup of this
/// crate (and of the crates it is built on). Cheap and idempotent.
pub fn register_types() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        ferroui_markup_xaml::register_types();
        TypeInfo::register_namespaces(NAMESPACES);
        TypeInfo::register_all(TYPES);
        rust_paths::register_rust_paths();
        ferroui_base::metadata::MarkupAssembly::register(&ASSEMBLY);
        // The assembly has no assets; the registration makes it known to the asset loader,
        // which a load by URI asks for the assembly of the document. The loader table asks
        // the table of each group of the build in turn.
        compiled_markup::register();
    });
}

#[cfg(test)]
mod tests;
