//! Test fixture of the XAML compiler (docs/porting/xaml.md, 9.7.3 and 9.10.1,
//! stage E5): a library with compiled markup, the assembly `Tests`, whose
//! documents the crate `xaml-include-fixture-application` includes. Not a
//! port of an upstream project: it holds the documents of upstream's include
//! tests that belong to the assembly the tests include from
//! ([`documents`]).
//!
//! The compiled markup is generated by the emitter of Rust source and checked
//! in, with the `.xamlmeta` that describes it to the crates that include its
//! documents (`tests/compiled_xaml_tests.rs`):
//!
//! ```text
//! cargo test -p xaml-include-fixture-theme --lib tests::compiled_xaml_tests::regenerate_compiled_xaml -- --ignored
//! ```

pub mod documents;
mod style_with_service_provider;

/// The documents of [`documents::DOCUMENTS`], compiled as one group.
#[doc(hidden)]
#[rustfmt::skip]
pub mod compiled_xaml;
/// The documents of [`documents::SOURCE_INFO_DOCUMENTS`], compiled as one group with
/// `CreateSourceInfo`.
#[doc(hidden)]
#[rustfmt::skip]
pub mod compiled_xaml_source_info;
/// The document of [`StyleWithServiceProvider`].
#[rustfmt::skip]
mod compiled_style_with_service_provider;

pub use style_with_service_provider::StyleWithServiceProvider;

use std::rc::Rc;

use ferroui_base::metadata::{IServiceProvider, MarkupAssembly};
use ferroui_base::{BoxedValue, TypeInfo};
use ferroui_markup_xaml::{FerroXamlLoader, XamlLoadException};

/// The dotted namespaces of the modules of this crate.
const NAMESPACES: &[(&str, &str)] = &[("xaml_include_fixture_theme", "XamlIncludeFixture.Theme")];

/// What this crate states about itself for markup: the assembly `Tests` of upstream's tests.
pub static ASSEMBLY: MarkupAssembly =
    MarkupAssembly { name: "Tests", crate_name: "xaml_include_fixture_theme", xmlns_definitions: &[], xmlns_prefixes: &[], metadata: &[] };

const TYPES: &[&TypeInfo] = &[StyleWithServiceProvider::TYPE];

/// The loader of the compiled markup of the assembly: the table of each generated
/// file, in turn (build integration generates one table for a crate).
fn try_load(service_provider: Option<&Rc<dyn IServiceProvider>>, uri: &str) -> Result<Option<BoxedValue>, XamlLoadException> {
    if let Some(loaded) = compiled_style_with_service_provider::try_load(service_provider, uri)? {
        return Ok(Some(loaded));
    }
    compiled_xaml::try_load(service_provider, uri)
}

/// Registers the namespaces, the types, the assembly and the compiled markup of this
/// crate (and of the crates it is built on). Cheap and idempotent.
pub fn register_types() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        ferroui_markup_xaml::register_types();
        TypeInfo::register_namespaces(NAMESPACES);
        TypeInfo::register_all(TYPES);
        MarkupAssembly::register(&ASSEMBLY);
        // The assembly has no assets; registering the empty table makes it known to the
        // asset loader, which a load by URI asks for the assembly of the document.
        ferroui_base::platform::register_assets(ASSEMBLY.name, &[]);
        FerroXamlLoader::register_compiled_xaml(ASSEMBLY.name, try_load);
    });
}

#[cfg(test)]
mod tests;
