//! ferroui-build
//!
//! Build-script support: compiles the markup documents of a crate to Rust
//! source and embeds its assets (docs/porting/xaml.md, section 9.6). The
//! counterpart of the build tasks of the upstream project
//! (`CompileXamlTask` with `XamlCompilerTaskExecutor`, and
//! `GenerateResourcesTask`), which run after the compiler and rewrite the
//! assembly; a Rust crate has no such step, so the build script of the crate
//! runs before the compiler and writes source the crate includes.
//!
//! ```ignore
//! // build.rs
//! fn main() {
//!     ferroui_controls::register_types();           // the types the documents name
//!     ferroui_build::Build::from_env()
//!         .assembly(&ASSEMBLY)                      // the assembly of the crate
//!         .embed_assets(&["Assets"])
//!         .compile_xaml()                           // every *.xaml of the crate
//!         .run();
//! }
//!
//! // lib.rs
//! ferroui_markup_xaml::include_compiled_xaml!();    // pub mod compiled_xaml, pub mod compiled_markup
//! pub fn register_types() { /* .. */ compiled_markup::register(); }
//! ```
//!
//! # What a run does, in order
//!
//! 1. Reads the `.xamlmeta` of every crate the crate depends on directly
//!    (`DEP_<CRATE>_XAML_XAMLMETA`, which Cargo sets from the `links` key and
//!    the `cargo::metadata=xamlmeta=<path>` line of that crate) and,
//!    transitively, the files they name: the compiled documents an include of
//!    a document of another crate is linked to.
//! 2. Compiles each group of documents as upstream compiles the documents of
//!    an assembly (parse, transform, group transformers, emit) and writes
//!    `$OUT_DIR/xaml/<module>.rs` with its position map.
//! 3. Lists the assets, leaving out the documents it compiled (upstream
//!    removes a compiled resource from the assembly).
//! 4. Writes `$OUT_DIR/<crate>.xamlmeta` (the compiled documents of the
//!    crate, and the paths of the files of step 1) and
//!    `$OUT_DIR/xaml/mod.rs` (the modules of the groups, the asset table, the
//!    loader table of the crate and `register()`).
//! 5. Prints the `cargo::` lines: `rerun-if-changed` for every input,
//!    `metadata=xamlmeta=<path>` for the crates that depend on this one, and
//!    `rustc-env=FERROUI_XAMLMETA=<path>` for the crate itself.
//!
//! Every document is compiled before the run fails: each error is printed as
//! a `cargo::error=` line, and the script exits with a failure once.
//!
//! # Where the type metadata comes from
//!
//! The compiler transforms a document against the run-time type system: the
//! types, properties and constructors the crates registered in the process
//! (`register_types()` of each). A build script therefore takes the crates
//! whose types its documents name as build dependencies and registers them
//! before it calls [`Build::run`], and it starts whatever application
//! services the transform of its documents needs. Two consequences:
//!
//! - those crates are built for the host as well as for the target (once
//!   more when the two differ or their features do);
//! - a build script cannot link the crate it builds, so it cannot compile a
//!   document that names a type of that crate: neither the document of a
//!   class of the crate (`x:Class`) nor a document that uses one of its
//!   types. Such a document is generated by a test of the crate and checked
//!   in (`rust_emitter::generate_class_file`); its loader table and its
//!   `.xamlmeta` join the ones of the build through [`Build::loader`] and
//!   [`Build::checked_in_metadata`].
//!
//! This crate itself links the compiler and the base crate only, never the
//! controls.
//!
//! # The build-time type model
//!
//! The way out of both consequences is xaml.md 9.5: the types read from the
//! sources instead of the process. What is here:
//!
//! - [`model`]: the type model of a crate (`AssemblyModel`, `TypeModel`,
//!   `MemberModel`, `RegisteredModel`) and its file, the `.xamlmeta` of format
//!   2, which keeps the documents of format 1 where the compiler reads them;
//! - [`scanner`]: the source scanner, which fills the model from the
//!   declaration macros of the sources of a crate (`scan_crate`), linking
//!   nothing;
//! - [`model_set`]: the models of several crates read together, so that a
//!   type or a property of one crate is found by the path another crate
//!   names it by;
//! - [`Build::export_metadata`]: the scan of the crate, with the models of
//!   its dependencies, written into its `.xamlmeta`;
//! - [`type_system`]: the type system of the compiler over the models
//!   (`ModelTypeSystem`, xaml.md 9.5.5), with the closed table of runtime
//!   library types it shares with the run-time type system.
//!
//! [`Build::compile_xaml`] still transforms against the run-time type system.
//! What is missing between `ModelTypeSystem` and the compilation is the call
//! forms of 9.5.3 and an emitter that reads them; xaml.md 9.10.1 has the
//! stages.
//!
//! ```ignore
//! // build.rs of a crate that declares types and has no documents
//! fn main() {
//!     ferroui_build::Build::from_env().export_metadata().run();
//! }
//! ```
//!
//! # A crate with checked-in compiled markup
//!
//! A crate that keeps all of its compiled markup checked in (the two themes)
//! does not need this crate: its build script prints the line of step 5 for
//! its checked-in file, and its manifest has the `links` key.
//!
//! ```ignore
//! println!("cargo::metadata=xamlmeta={}/compiled_xaml.xamlmeta", env!("CARGO_MANIFEST_DIR"));
//! ```

#![forbid(unsafe_code)]

mod json;
pub mod model;
pub mod model_set;
pub mod scanner;
pub mod type_system;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use ferroui_base::metadata::MarkupAssembly;
use ferroui_markup_xaml::RuntimeXamlLoaderConfiguration;

use crate::model::AssemblyModel;
use crate::model_set::ModelSet;
use crate::scanner::{scan_crate, Scan, ScanOptions, Severity};
use ferroui_markup_xaml_loader::rust_emitter::{generate_file, rust_string_literal, XamlMetadata};
use ferroui_markup_xaml_loader::FerroRuntimeXamlLoader;

/// The name of the module of the default group ([`Build::compile_xaml`]).
pub const DEFAULT_MODULE: &str = "compiled_xaml";

/// The environment variable the build sets for the crate: the path of its `.xamlmeta`
/// (`env!("FERROUI_XAMLMETA")`).
pub const XAMLMETA_VARIABLE: &str = "FERROUI_XAMLMETA";

/// A group of documents that are compiled together into one module: the group
/// transformers see every document of it, so includes between them are linked, as
/// upstream compiles the documents of an assembly.
pub struct XamlGroup {
    module: String,
    documents: Option<Vec<(String, String)>>,
    create_source_info: Option<bool>,
    exported: bool,
}

impl XamlGroup {
    /// A group whose generated file is the body of the module `module` of the crate
    /// root. Without [`documents`](Self::documents) the group is every `.xaml` file
    /// below the XAML root of the build.
    pub fn new(module: &str) -> Self {
        Self { module: module.to_string(), documents: None, create_source_info: None, exported: true }
    }

    /// The documents of the group, by their path below the root URI of the assembly
    /// (`Views/Main.xaml`), in the order they are compiled. The build script states the
    /// files they come from with [`Build::input`].
    pub fn documents(mut self, documents: &[(&str, &str)]) -> Self {
        self.documents = Some(documents.iter().map(|(name, xaml)| (name.to_string(), xaml.to_string())).collect());
        self
    }

    /// Whether the documents are compiled with source information (`CreateSourceInfo`);
    /// without the call, as the assembly states it.
    pub fn create_source_info(mut self, value: bool) -> Self {
        self.create_source_info = Some(value);
        self
    }

    /// Keeps the group out of the loader table and of the `.xamlmeta` of the crate: its
    /// documents are reached by their build functions only (a second compilation of
    /// documents another group registers, as a test compiles them).
    pub fn internal(mut self) -> Self {
        self.exported = false;
        self
    }
}

/// What a build did: the lines for Cargo and the errors.
pub struct Outcome {
    /// The `cargo::` lines, in order.
    pub lines: Vec<String>,
    /// The errors, each on one line. A build with errors wrote no `.xamlmeta` and no
    /// `mod.rs`.
    pub errors: Vec<String>,
}

/// The build of the markup of a crate; see the crate documentation.
pub struct Build {
    manifest_dir: PathBuf,
    out_dir: PathBuf,
    crate_name: String,
    assembly: Option<&'static MarkupAssembly>,
    xaml_root: PathBuf,
    groups: Vec<XamlGroup>,
    asset_directories: Vec<String>,
    loaders: Vec<String>,
    checked_in_metadata: Vec<PathBuf>,
    inputs: Vec<PathBuf>,
    dependencies: Vec<PathBuf>,
    export_metadata: bool,
    source_root: Option<PathBuf>,
}

impl Build {
    /// The build of the crate whose build script is running: `CARGO_MANIFEST_DIR`,
    /// `OUT_DIR`, `CARGO_PKG_NAME`, and the `.xamlmeta` of every direct dependency
    /// (`DEP_<CRATE>_XAML_XAMLMETA`), in the order of the names of the variables.
    ///
    /// # Panics
    /// Panics outside a build script (a variable Cargo sets is missing).
    pub fn from_env() -> Self {
        let variable = |name: &str| env::var_os(name).unwrap_or_else(|| panic!("{name} is not set: not a build script"));
        let mut dependencies: Vec<(String, PathBuf)> = env::vars_os()
            .filter_map(|(name, value)| {
                let name = name.into_string().ok()?;
                (name.starts_with("DEP_") && name.ends_with("_XAMLMETA")).then(|| (name, PathBuf::from(value)))
            })
            .collect();
        dependencies.sort();
        Self::new(
            PathBuf::from(variable("CARGO_MANIFEST_DIR")),
            PathBuf::from(variable("OUT_DIR")),
            &variable("CARGO_PKG_NAME").to_string_lossy(),
            dependencies.into_iter().map(|(_, path)| path).collect(),
        )
    }

    /// The build of the package `package_name` in `manifest_dir`, writing below `out_dir`,
    /// with the `.xamlmeta` files of its direct dependencies.
    pub fn new(manifest_dir: PathBuf, out_dir: PathBuf, package_name: &str, dependencies: Vec<PathBuf>) -> Self {
        Self {
            manifest_dir,
            out_dir,
            crate_name: package_name.replace('-', "_"),
            assembly: None,
            xaml_root: PathBuf::new(),
            groups: Vec::new(),
            asset_directories: Vec::new(),
            loaders: Vec::new(),
            checked_in_metadata: Vec::new(),
            inputs: Vec::new(),
            dependencies,
            export_metadata: false,
            source_root: None,
        }
    }

    /// Scans the sources of the crate and writes its type model into its `.xamlmeta`
    /// (format 2: the model next to the compiled documents), which the crates that depend
    /// on this one read as they read its documents (xaml.md 9.6.3). The scan reads the
    /// models of the dependencies of the crate first, so that what the crate names of
    /// theirs is resolved ([`ScanOptions::dependencies`]).
    ///
    /// The sources are read as files: nothing of the crate is linked, and a crate that
    /// only exports its model needs no [`assembly`](Self::assembly) (the scan reads the
    /// `MarkupAssembly` the sources state; a crate without one is the assembly named after
    /// the crate). What the scanner cannot read of a declaration is a `cargo::warning=`
    /// line and does not fail the build.
    pub fn export_metadata(mut self) -> Self {
        self.export_metadata = true;
        self
    }

    /// The root file of the sources of the crate, relative to the crate directory, for
    /// [`export_metadata`](Self::export_metadata). Without the call: `src/lib.rs`, else
    /// `lib.rs`, else `src/main.rs`.
    pub fn source_root(mut self, file: &str) -> Self {
        self.source_root = Some(PathBuf::from(file));
        self
    }

    /// The scan of the sources of the crate, with the models of its dependencies.
    fn scan(&self, dependencies: Vec<AssemblyModel>) -> Result<Scan, String> {
        let root = match &self.source_root {
            Some(root) => self.manifest_dir.join(root),
            None => ["src/lib.rs", "lib.rs", "src/main.rs"]
                .iter()
                .map(|candidate| self.manifest_dir.join(candidate))
                .find(|candidate| candidate.is_file())
                .ok_or_else(|| {
                    format!(
                        "the root file of the sources of the crate is not found in {} (`src/lib.rs`, `lib.rs`, `src/main.rs`): state it with Build::source_root",
                        self.manifest_dir.display()
                    )
                })?,
        };
        if !root.is_file() {
            return Err(format!("the root file of the sources of the crate, {}, is not a file", root.display()));
        }
        let mut options = ScanOptions::new(&self.crate_name, root).with_dependencies(dependencies);
        options.assembly_name = self.assembly.map(|assembly| assembly.name.to_string());
        Ok(scan_crate(&options))
    }

    /// The assembly of the crate: its name is the host of the URIs of its documents and
    /// assets, and its metadata the default of `CreateSourceInfo`. The same value the
    /// crate registers in its `register_types()`.
    pub fn assembly(mut self, assembly: &'static MarkupAssembly) -> Self {
        self.assembly = Some(assembly);
        self
    }

    /// The directory, relative to the crate directory, below which the documents of a
    /// group without stated documents are found. The crate directory by default.
    pub fn xaml_root(mut self, directory: &str) -> Self {
        self.xaml_root = PathBuf::from(directory);
        self
    }

    /// A file, relative to the crate directory, the build reads through the build
    /// script (a file the script includes): the build runs again when it changes.
    pub fn input(mut self, path: &str) -> Self {
        self.inputs.push(self.manifest_dir.join(path));
        self
    }

    /// Embeds every file below the directories (relative to the crate directory) as an
    /// asset of the crate, by its path below the crate directory, except the documents
    /// the build compiles.
    pub fn embed_assets(mut self, directories: &[&str]) -> Self {
        self.asset_directories.extend(directories.iter().map(|directory| directory.to_string()));
        self
    }

    /// Compiles every `.xaml` file below the XAML root as the group
    /// [`DEFAULT_MODULE`].
    pub fn compile_xaml(self) -> Self {
        self.compile_group(XamlGroup::new(DEFAULT_MODULE))
    }

    /// Compiles a group of documents.
    pub fn compile_group(mut self, group: XamlGroup) -> Self {
        self.groups.push(group);
        self
    }

    /// The loader table of a checked-in generated file of the crate, by the path of its
    /// `try_load` (`crate::compiled_main_window::try_load`): the table of the crate asks
    /// it first, in the order of the calls.
    pub fn loader(mut self, path: &str) -> Self {
        self.loaders.push(path.to_string());
        self
    }

    /// The `.xamlmeta` of a checked-in generated file of the crate, relative to the crate
    /// directory: its documents are added to the `.xamlmeta` of the crate.
    pub fn checked_in_metadata(mut self, path: &str) -> Self {
        self.checked_in_metadata.push(self.manifest_dir.join(path));
        self
    }

    /// Runs the build and prints its lines for Cargo. On an error every error is printed
    /// and the process exits with a failure.
    pub fn run(self) {
        let outcome = self.execute();
        for line in &outcome.lines {
            println!("{line}");
        }
        if !outcome.errors.is_empty() {
            for error in &outcome.errors {
                eprintln!("error: {error}");
                println!("cargo::error={error}");
            }
            std::process::exit(1);
        }
    }

    /// Runs the build and returns what [`run`](Self::run) prints.
    pub fn execute(self) -> Outcome {
        let mut lines = Vec::new();
        let mut errors = Vec::new();
        let rerun = |lines: &mut Vec<String>, path: &Path| lines.push(format!("cargo::rerun-if-changed={}", path.display()));
        rerun(&mut lines, &self.manifest_dir.join("build.rs"));
        rerun(&mut lines, &self.manifest_dir.join("Cargo.toml"));
        for input in &self.inputs {
            rerun(&mut lines, input);
        }
        // The documents are compiled against the assembly the crate registers; a build
        // that only exports the type model of the crate reads the assembly from the sources.
        if self.assembly.is_none() && (!self.export_metadata || !self.groups.is_empty()) {
            errors.push("the assembly of the crate is not stated (Build::assembly)".to_string());
            return Outcome { lines, errors };
        }

        // 1. The compiled markup and the type models of the dependencies.
        let (models, dependency_files) = match ModelSet::read(&self.dependencies) {
            Ok(read) => read,
            Err(error) => {
                errors.push(format!("the .xamlmeta of a dependency cannot be read: {error}"));
                return Outcome { lines, errors };
            }
        };
        for file in &dependency_files {
            rerun(&mut lines, file);
        }
        let dependencies: Vec<XamlMetadata> = models.iter().map(AssemblyModel::metadata).collect();

        // The type model of the crate, from its sources.
        let mut model: Option<AssemblyModel> = None;
        if self.export_metadata {
            match self.scan(models) {
                Ok(scan) => {
                    for file in &scan.files {
                        rerun(&mut lines, &file.path);
                    }
                    for diagnostic in scan.diagnostics_of(Severity::Error) {
                        lines.push(format!("cargo::warning={diagnostic}"));
                    }
                    model = Some(scan.model);
                }
                Err(error) => {
                    errors.push(error);
                    return Outcome { lines, errors };
                }
            }
        }
        let assembly_name: String = match (self.assembly, &model) {
            (Some(assembly), _) => assembly.name.to_string(),
            (None, Some(model)) if !model.name.is_empty() => model.name.clone(),
            // A crate that states no assembly is the assembly named after the crate, as
            // the type systems name it.
            (None, _) => self.crate_name.clone(),
        };

        if let Some(assembly) = self.assembly {
            // The compiler resolves the assembly of the crate and the types of the runtime
            // library; every other type is the build script's to register.
            ferroui_markup_xaml::register_types();
            MarkupAssembly::register(assembly);
            // Makes the assembly known to the asset loader, as the `register_types()` of the
            // crate does: the host of the emitter in the tests of a crate runs with it.
            ferroui_base::platform::register_assets(assembly.name, &[]);
            FerroRuntimeXamlLoader::register();
        }

        // 2. The groups.
        let xaml_directory = self.out_dir.join("xaml");
        let root_uri = format!("ferres://{assembly_name}/");
        let mut metadata = XamlMetadata {
            name: assembly_name.clone(),
            crate_name: self.crate_name.clone(),
            documents: Vec::new(),
            dependencies: self.dependencies.iter().map(|path| path.display().to_string()).collect(),
        };
        let mut modules: Vec<(String, PathBuf, bool)> = Vec::new();
        let mut compiled_documents: Vec<String> = Vec::new();
        for group in &self.groups {
            let Some(assembly) = self.assembly else { break };
            if modules.iter().any(|(module, _, _)| *module == group.module) {
                errors.push(format!("two groups have the module `{}`", group.module));
                continue;
            }
            let documents = match &group.documents {
                Some(documents) => documents.clone(),
                None => {
                    let root = self.manifest_dir.join(&self.xaml_root);
                    rerun(&mut lines, &root);
                    let mut files = Vec::new();
                    if let Err(error) = collect(&self.manifest_dir, &root, &mut files) {
                        errors.push(error);
                    }
                    let mut documents = Vec::with_capacity(files.len());
                    for (rooted, path) in files {
                        if !path.extension().is_some_and(|extension| extension == "xaml") {
                            continue;
                        }
                        match fs::read_to_string(&path) {
                            Ok(text) => documents.push((rooted.trim_start_matches('/').to_string(), text)),
                            Err(error) => errors.push(format!("{}: {error}", path.display())),
                        }
                    }
                    documents
                }
            };
            let mut configuration = RuntimeXamlLoaderConfiguration::new();
            configuration.local_assembly = Some(assembly);
            if let Some(create_source_info) = group.create_source_info {
                configuration.set_create_source_info(create_source_info);
            }
            let borrowed: Vec<(&str, &str)> = documents.iter().map(|(name, xaml)| (name.as_str(), xaml.as_str())).collect();
            let file = generate_file(assembly.name, &root_uri, &borrowed, &configuration, &dependencies);
            for (name, reason) in &file.documents {
                if let Some(reason) = reason {
                    errors.push(format!("{name}: {}", reason.replace(['\r', '\n'], " ")));
                }
            }
            let path = xaml_directory.join(format!("{}.rs", group.module));
            write_if_changed(&path, &file.source, &mut errors);
            write_if_changed(&xaml_directory.join(format!("{}.map.json", group.module)), &file.position_map, &mut errors);
            if group.exported {
                let module_path = format!("::{}::{}", self.crate_name, group.module);
                metadata.documents.extend(file.metadata(&self.crate_name, &module_path, &[]).documents);
                compiled_documents.extend(documents.iter().map(|(name, _)| format!("/{name}")));
            }
            modules.push((group.module.clone(), path, group.exported));
        }
        for path in &self.checked_in_metadata {
            rerun(&mut lines, path);
            let read = fs::read_to_string(path).map_err(|error| error.to_string()).and_then(|text| XamlMetadata::parse(&text));
            match read {
                Ok(read) if read.name == assembly_name => metadata.documents.extend(read.documents),
                Ok(read) => errors.push(format!(
                    "{}: the file describes the assembly `{}`, the crate is `{}`",
                    path.display(),
                    read.name,
                    assembly_name
                )),
                Err(error) => errors.push(format!("{}: {error}", path.display())),
            }
        }

        // 3. The assets.
        let mut assets: Vec<(String, PathBuf)> = Vec::new();
        for directory in &self.asset_directories {
            let directory = self.manifest_dir.join(directory);
            rerun(&mut lines, &directory);
            if let Err(error) = collect(&self.manifest_dir, &directory, &mut assets) {
                errors.push(error);
            }
        }
        assets.retain(|(rooted, _)| !compiled_documents.contains(rooted));
        assets.sort();
        assets.dedup();

        if !errors.is_empty() {
            return Outcome { lines, errors };
        }

        // 4. The `.xamlmeta` (with the type model of the crate, when it is exported) and
        // the file the crate includes.
        let metadata_path = self.out_dir.join(format!("{}.xamlmeta", self.crate_name));
        let metadata_text = match model {
            Some(mut model) => {
                model.name = metadata.name;
                model.crate_name = metadata.crate_name;
                model.documents = metadata.documents;
                model.dependencies = metadata.dependencies;
                model.to_json()
            }
            None => metadata.to_json(),
        };
        write_if_changed(&metadata_path, &metadata_text, &mut errors);
        // A crate that only exports its model includes nothing.
        if self.assembly.is_some() {
            let text = crate_file(&assembly_name, &modules, &self.loaders, &assets);
            write_if_changed(&xaml_directory.join("mod.rs"), &text, &mut errors);
        }

        // 5. For the dependents, and for the crate itself.
        lines.push(format!("cargo::metadata=xamlmeta={}", metadata_path.display()));
        lines.push(format!("cargo::rustc-env={XAMLMETA_VARIABLE}={}", metadata_path.display()));
        Outcome { lines, errors }
    }
}

/// Compiles every `.xaml` file of the crate whose build script is running
/// (`Build::from_env().assembly(assembly).compile_xaml().run()`).
pub fn compile_xaml(assembly: &'static MarkupAssembly) {
    Build::from_env().assembly(assembly).compile_xaml().run();
}

/// Embeds the files below `directories` as the assets of the crate whose build script
/// is running (`Build::from_env().assembly(assembly).embed_assets(directories).run()`).
pub fn embed_assets(assembly: &'static MarkupAssembly, directories: &[&str]) {
    Build::from_env().assembly(assembly).embed_assets(directories).run();
}

/// Scans the sources of the crate whose build script is running and exports its type
/// model (`Build::from_env().export_metadata().run()`).
pub fn export_metadata() {
    Build::from_env().export_metadata().run();
}

/// Every file below `directory`, with its rooted path below `root` (`/Assets/a.png`),
/// in the order of the names. Directories whose name starts with a dot and the
/// directory `target` of `root` are skipped.
fn collect(root: &Path, directory: &Path, found: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    let entries = fs::read_dir(directory).map_err(|error| format!("{}: {error}", directory.display()))?;
    let mut paths = Vec::new();
    for entry in entries {
        paths.push(entry.map_err(|error| format!("{}: {error}", directory.display()))?.path());
    }
    paths.sort();
    for path in paths {
        let name = path.file_name().map(|name| name.to_string_lossy().into_owned()).unwrap_or_default();
        if path.is_dir() {
            if !name.starts_with('.') && !(directory == root && name == "target") {
                collect(root, &path, found)?;
            }
            continue;
        }
        let relative = path.strip_prefix(root).map_err(|_| format!("{} is not below {}", path.display(), root.display()))?;
        let parts: Vec<String> = relative.components().map(|part| part.as_os_str().to_string_lossy().into_owned()).collect();
        found.push((format!("/{}", parts.join("/")), path));
    }
    Ok(())
}

/// Writes `text` to `path` unless the file holds it already, so that a build that
/// changed nothing does not make the compiler run again.
fn write_if_changed(path: &Path, text: &str, errors: &mut Vec<String>) {
    if fs::read_to_string(path).ok().as_deref() == Some(text) {
        return;
    }
    let written = match path.parent() {
        Some(directory) => fs::create_dir_all(directory).and_then(|()| fs::write(path, text)),
        None => fs::write(path, text),
    };
    if let Err(error) = written {
        errors.push(format!("{}: {error}", path.display()));
    }
}

/// The text of `$OUT_DIR/xaml/mod.rs`, which `include_compiled_xaml!()` includes at the
/// root of the crate: the module of every group, and the module `compiled_markup`
/// with the asset table, the loader table of the crate (the checked-in tables, then
/// the groups, in order) and `register()`.
fn crate_file(assembly_name: &str, modules: &[(String, PathBuf, bool)], loaders: &[String], assets: &[(String, PathBuf)]) -> String {
    let mut text = String::new();
    text.push_str("// @generated by ferroui-build (Build::run). Do not edit.\n");
    for (module, path, _) in modules {
        text.push('\n');
        text.push_str(&format!("/// The compiled documents of the group `{module}`.\n"));
        text.push_str("#[doc(hidden)]\n");
        text.push_str("#[rustfmt::skip]\n");
        text.push_str(&format!("pub mod {module} {{\n"));
        text.push_str(&format!("    include!({});\n", rust_string_literal(&path.display().to_string())));
        text.push_str("}\n");
    }
    text.push('\n');
    text.push_str("/// The compiled markup and the embedded assets of the crate.\n");
    text.push_str("#[doc(hidden)]\n");
    text.push_str("#[rustfmt::skip]\n");
    text.push_str("pub mod compiled_markup {\n");
    text.push_str("    /// The assembly of the crate.\n");
    text.push_str(&format!("    pub const ASSEMBLY_NAME: &str = {};\n", rust_string_literal(assembly_name)));
    text.push('\n');
    text.push_str("    /// The embedded assets of the crate, by rooted path.\n");
    text.push_str("    pub static ASSETS: &[(&str, &[u8])] = &[\n");
    for (rooted, path) in assets {
        text.push_str(&format!(
            "        ({}, include_bytes!({})),\n",
            rust_string_literal(rooted),
            rust_string_literal(&path.display().to_string())
        ));
    }
    text.push_str("    ];\n");
    text.push('\n');
    text.push_str("    /// The loader of the compiled markup of the crate: the object of the document with the URI\n");
    text.push_str("    /// `uri`, from the first table that has it; `Ok(None)` if none has.\n");
    text.push_str("    #[allow(unused_variables)]\n");
    text.push_str("    pub fn try_load(\n");
    text.push_str("        service_provider: ::core::option::Option<&::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,\n");
    text.push_str("        uri: &str,\n");
    text.push_str("    ) -> ::core::result::Result<::core::option::Option<::ferroui_base::BoxedValue>, ::ferroui_markup_xaml::XamlLoadException> {\n");
    let tables = loaders
        .iter()
        .cloned()
        .chain(modules.iter().filter(|(_, _, exported)| *exported).map(|(module, _, _)| format!("super::{module}::try_load")));
    for table in tables {
        text.push_str(&format!("        if let ::core::option::Option::Some(loaded) = {table}(service_provider, uri)? {{\n"));
        text.push_str("            return ::core::result::Result::Ok(::core::option::Option::Some(loaded));\n");
        text.push_str("        }\n");
    }
    text.push_str("        ::core::result::Result::Ok(::core::option::Option::None)\n");
    text.push_str("    }\n");
    text.push('\n');
    text.push_str("    /// Registers the assets and the compiled markup of the crate. The assembly is made known\n");
    text.push_str("    /// to the asset loader even without assets: a load by URI asks it for the assembly of the\n");
    text.push_str("    /// document.\n");
    text.push_str("    pub fn register() {\n");
    text.push_str("        ::ferroui_base::platform::register_assets(ASSEMBLY_NAME, ASSETS);\n");
    text.push_str("        ::ferroui_markup_xaml::FerroXamlLoader::register_compiled_xaml(ASSEMBLY_NAME, try_load);\n");
    text.push_str("    }\n");
    text.push_str("}\n");
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Not from upstream: the file a crate includes names the generated files, chains the
    /// loader tables (the checked-in ones first, a group that is not exported not at all)
    /// and registers the assets with the table.
    #[test]
    fn crate_file_declares_the_modules_and_the_loader_table() {
        let modules = vec![
            ("compiled_xaml".to_string(), PathBuf::from("/out/xaml/compiled_xaml.rs"), true),
            ("compiled_xaml_source_info".to_string(), PathBuf::from("/out/xaml/compiled_xaml_source_info.rs"), false),
        ];
        let assets = vec![("/Assets/a.png".to_string(), PathBuf::from("/crate/Assets/a.png"))];
        let text = crate_file("Tests", &modules, &["crate::compiled_main::try_load".to_string()], &assets);
        assert!(text.contains("pub mod compiled_xaml {\n    include!(\"/out/xaml/compiled_xaml.rs\");\n}\n"), "{text}");
        assert!(text.contains("pub mod compiled_xaml_source_info {\n"), "{text}");
        assert!(text.contains("    pub const ASSEMBLY_NAME: &str = \"Tests\";\n"), "{text}");
        assert!(text.contains("        (\"/Assets/a.png\", include_bytes!(\"/crate/Assets/a.png\")),\n"), "{text}");
        let checked_in = text.find("= crate::compiled_main::try_load(service_provider, uri)?").expect("the checked-in table");
        let group = text.find("= super::compiled_xaml::try_load(service_provider, uri)?").expect("the table of the group");
        assert!(checked_in < group, "{text}");
        assert!(!text.contains("super::compiled_xaml_source_info::try_load"), "{text}");
    }

    /// Not from upstream: `export_metadata()` scans the sources of the crate, writes its
    /// type model into its `.xamlmeta` and names every file it read; the build of a crate
    /// that depends on it reads that file and resolves against the model in it.
    #[test]
    fn export_metadata_writes_the_model_and_reads_the_models_of_the_dependencies() {
        let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("fixtures");
        let out = env::temp_dir().join(format!("ferroui-build-export-{}", std::process::id()));
        let first = Build::new(fixtures.join("scanner"), out.join("fixture"), "fixture", Vec::new()).source_root("lib.rs").export_metadata().execute();
        assert_eq!(first.errors, Vec::<String>::new());
        let fixture_file = out.join("fixture").join("fixture.xamlmeta");
        assert!(first.lines.contains(&format!("cargo::metadata=xamlmeta={}", fixture_file.display())), "{:?}", first.lines);
        let border = fixtures.join("scanner").join("controls").join("border.rs");
        assert!(first.lines.contains(&format!("cargo::rerun-if-changed={}", border.display())), "{:?}", first.lines);
        // What the scanner does not read is a warning of the build.
        assert!(first.lines.iter().any(|line| line.starts_with("cargo::warning=") && line.contains("error FRN9010")), "{:?}", first.lines);
        let text = fs::read_to_string(&fixture_file).expect("the .xamlmeta of the fixture");
        let model = AssemblyModel::parse(&text).expect("a file of format 2");
        assert_eq!((model.name.as_str(), model.crate_name.as_str()), ("Fixture", "fixture"));
        assert!(model.find_type("Fixture.Controls.Border").is_some() && !model.exports.is_empty());
        assert!(model.documents.is_empty() && model.dependencies.is_empty());
        assert_eq!(XamlMetadata::parse(&text).map(|metadata| metadata.name), Ok("Fixture".to_string()));
        assert!(!out.join("fixture").join("xaml").join("mod.rs").exists(), "a crate that only exports its model includes nothing");

        let second = Build::new(fixtures.join("dependent"), out.join("dependent"), "dependent", vec![fixture_file.clone()]).export_metadata().execute();
        assert_eq!(second.errors, Vec::<String>::new());
        assert!(second.lines.contains(&format!("cargo::rerun-if-changed={}", fixture_file.display())), "{:?}", second.lines);
        let text = fs::read_to_string(out.join("dependent").join("dependent.xamlmeta")).expect("the .xamlmeta of the dependent crate");
        let model = AssemblyModel::parse(&text).expect("a file of format 2");
        assert_eq!((model.name.as_str(), model.crate_name.as_str()), ("dependent", "dependent"));
        assert_eq!(model.dependencies, [fixture_file.display().to_string()]);
        let card = model.find_type("Card").expect("the class of the dependent crate");
        assert_eq!(card.registered[0].name.as_deref(), Some("Background"));
        assert_eq!(card.base.as_ref().map(|base| base.text.as_str()), Some("::fixture::controls::border::Border"));
        // The models are read back as a set, the dependency through the file that names it.
        let (models, files) = ModelSet::read(&[out.join("dependent").join("dependent.xamlmeta")]).expect("the two files");
        assert_eq!(models.iter().map(|model| model.name.as_str()).collect::<Vec<_>>(), ["dependent", "Fixture"]);
        assert_eq!(files.len(), 2);

        let missing = Build::new(fixtures.join("dependent"), out.join("missing"), "dependent", Vec::new()).source_root("main.rs").export_metadata().execute();
        assert_eq!(missing.errors.len(), 1, "{:?}", missing.errors);
        assert!(missing.errors[0].ends_with("main.rs, is not a file"), "{:?}", missing.errors);
        let _ = fs::remove_dir_all(&out);
    }

    /// Not from upstream: a build without an assembly reports it, with the lines that make
    /// Cargo run the script again.
    #[test]
    fn build_without_an_assembly_is_an_error() {
        let outcome = Build::new(PathBuf::from("/crate"), PathBuf::from("/out"), "my-crate", Vec::new()).compile_xaml().execute();
        assert_eq!(outcome.errors, ["the assembly of the crate is not stated (Build::assembly)"]);
        assert_eq!(outcome.lines, ["cargo::rerun-if-changed=/crate/build.rs", "cargo::rerun-if-changed=/crate/Cargo.toml"]);
    }
}
