//! ferroui-themes-simple
//!
//! The Simple theme: the control themes of the control set and the
//! resources they use, in a light and a dark variant.
//!
//! The theme is markup: `SimpleTheme.xaml` (the document of the
//! [`SimpleTheme`] class), `Accents/Base.xaml` (colours and brushes of the
//! variants), `Controls/SimpleControls.xaml` (the list of the control
//! themes) and one document per control under `Controls/`. The documents
//! belong to the assembly `FerroUI.Themes.Simple`, with the URIs
//! `ferres://FerroUI.Themes.Simple/<path>`. They are compiled into the crate,
//! as upstream's compiler compiles them, and are not embedded as assets: a
//! load by URI goes to the loader table of the compiled markup, which
//! answers the public document `SimpleTheme.xaml` (see `build.rs`).
//!
//! ```ignore
//! application.styles().add(SimpleTheme::new().upcast::<Styles>());
//! ```

mod assets;
// `compiled_xaml`, the compiled markup of the theme: generated by the build script of the
// crate from the documents of [`SimpleTheme`], against the type models of this crate and of
// the crates it is built on (docs/porting/xaml.md, 9.5.13). The checked-in `compiled_xaml.rs`
// is the reference `tests/compiled_xaml_tests.rs` compares the output of the build with, byte
// for byte; it is not a module of the crate. (`compiled_markup`, which the same file declares,
// is not used: the theme registers its assets and its loader table itself.)
ferroui_markup_xaml::include_compiled_xaml!();
mod register_types;
mod rust_paths;
mod simple_theme;

pub use assets::{excluded_documents, ExcludedDocument};
pub use register_types::{register_types, ASSEMBLY};
pub use simple_theme::SimpleTheme;

#[cfg(test)]
mod tests;
