//! The markup documents and the other assets of the crate as embedded
//! assets.
//!
//! The table is generated by the build script of the crate from the files
//! of the crate directory (the counterpart of the resource items of the
//! upstream project file).

use crate::ASSEMBLY;
use ferroui_base::platform::register_assets;

include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// The content of the embedded asset with the rooted asset path `path`.
pub(crate) fn asset(path: &str) -> Option<&'static [u8]> {
    ASSETS.iter().find(|(asset_path, _)| *asset_path == path).map(|(_, content)| *content)
}

/// Registers the embedded assets with the asset loader under the name of
/// the assembly of the crate.
pub(crate) fn register() {
    register_assets(ASSEMBLY.name, ASSETS);
}
