[package]
name = "ferroui-harfbuzz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[dependencies]
ferroui-base.workspace = true
ferroui-controls.workspace = true
harfbuzz-sys.workspace = true

[dev-dependencies]
ferroui-base = { workspace = true, features = ["testing"] }
ferroui-controls = { workspace = true, features = ["testing"] }
