#!/usr/bin/env python3
"""Converts the upstream generated Unicode data tables (C#) into Rust data files.

Origin of the data
------------------
Upstream (Avalonia, MIT) generates its Unicode tables from the Unicode Character
Database with the tool ``src/tools/Avalonia.UnicodeTrieGenerator`` (it downloads
the UCD files and writes ``*.trie.cs`` / ``*.data.cs`` into
``src/Avalonia.Base/Media/TextFormatting/Unicode``). That tool is NOT ported and
is not run here: this script only transliterates its committed output, so the
Rust tables are bit-for-bit the upstream tables.

Inputs (read from ``<upstream>/src/Avalonia.Base/Media/TextFormatting/Unicode``):

    UnicodeData.trie.cs       -> unicode_data_trie.rs       (UnicodeDataTrie)
    BiDi.trie.cs              -> bidi_trie.rs               (BiDiTrie)
    Segmentation.trie.cs      -> segmentation_trie.rs       (SegmentationTrie)
    EastAsianWidth.trie.cs    -> east_asian_width_trie.rs   (EastAsianWidthTrie)
    ScriptExtensions.data.cs  -> script_extensions_data.rs
    UnicodeDataSource.cs      -> only read for the Unicode version recorded in
                                 the generated headers

Outputs are written to ``src/FerroUI.Base/media/text_formatting/unicode`` of the
workspace this script lives in (override with ``--out``).

How to rerun
------------
    python3 scripts/convert-unicode-tries.py /path/to/upstream/checkout

Run it whenever upstream regenerates its Unicode data (new Unicode version),
together with ``scripts/convert-unicode-enums.py`` (enums and property value
aliases change with the data), then run ``cargo test -p ferroui-base``.

Conformance tests
-----------------
The data driven conformance tests of the ``unicode`` module (BidiTest,
BidiCharacterTest, GraphemeBreakTest, LineBreakTest, WordBreakTest,
SentenceBreakTest) read the UCD test files from the directory named by the
environment variable ``FERROUI_UCD_DIR`` and are skipped when it is unset.
The directory must mirror ``https://www.unicode.org/Public/<version>/ucd/``
for the Unicode version of the tables, i.e. contain

    BidiTest.txt
    BidiCharacterTest.txt
    auxiliary/GraphemeBreakTest.txt
    auxiliary/LineBreakTest.txt
    auxiliary/WordBreakTest.txt
    auxiliary/SentenceBreakTest.txt

(files placed directly in the directory, without ``auxiliary/``, are found too).

Only the Python standard library is used.
"""

import argparse
import os
import re
import sys

UPSTREAM_DIR = os.path.join("src", "Avalonia.Base", "Media", "TextFormatting", "Unicode")
DEFAULT_OUT = os.path.join("src", "FerroUI.Base", "media", "text_formatting", "unicode")

# (upstream file, rust file, rust struct name)
TRIES = [
    ("UnicodeData.trie.cs", "unicode_data_trie.rs", "UnicodeDataTrie"),
    ("BiDi.trie.cs", "bidi_trie.rs", "BiDiTrie"),
    ("Segmentation.trie.cs", "segmentation_trie.rs", "SegmentationTrie"),
    ("EastAsianWidth.trie.cs", "east_asian_width_trie.rs", "EastAsianWidthTrie"),
]


def read(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d bytes)" % (path, len(text)))


def unicode_version(upstream_dir):
    source = read(os.path.join(upstream_dir, "UnicodeDataSource.cs"))
    match = re.search(r'Version\s*=\s*"([0-9.]+)"', source)
    if not match:
        sys.exit("cannot find the Unicode version in UnicodeDataSource.cs")
    return match.group(1)


def header(version, source_file):
    return (
        "// Generated by scripts/convert-unicode-tries.py from the upstream file\n"
        "// `%s`. Do not edit.\n"
        "// Unicode version: %s\n\n" % (source_file, version)
    )


def strip_comments(text):
    return re.sub(r"//[^\n]*", "", text)


def array_literals(text):
    """Returns the bodies of all top level `[ ... ];` collection literals."""
    return [m.group(1) for m in re.finditer(r"^\s*\[\s*\n(.*?)^\s*\];", text, re.S | re.M)]


def parse_numbers(body):
    return [int(token, 0) for token in re.findall(r"0x[0-9A-Fa-f]+|\d+", strip_comments(body))]


def convert_trie(upstream_dir, out_dir, version, source_file, rust_file, struct_name):
    text = read(os.path.join(upstream_dir, source_file))
    if not re.search(r"\bclass\s+%s\b" % struct_name, text):
        sys.exit("%s: class %s not found" % (source_file, struct_name))
    ctor = re.search(r"new\(Data,\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+)\)", text)
    if not ctor:
        sys.exit("%s: trie constructor not found" % source_file)
    high_start = int(ctor.group(1), 16)
    error_value = int(ctor.group(2), 16)
    literals = array_literals(text)
    if len(literals) != 1:
        sys.exit("%s: expected exactly one array literal, found %d" % (source_file, len(literals)))
    data = parse_numbers(literals[0])

    out = [header(version, source_file)]
    out.append("use super::unicode_trie::UnicodeTrie;\n\n")
    out.append("/// The generated `%s` lookup table.\n" % struct_name)
    out.append("pub(crate) struct %s;\n\n" % struct_name)
    out.append("impl %s {\n" % struct_name)
    out.append("    /// The trie over [`%s::data`].\n" % struct_name)
    out.append("    #[inline(always)]\n")
    out.append("    pub(crate) const fn trie() -> UnicodeTrie<'static> {\n")
    out.append("        UnicodeTrie::new(&DATA, 0x%08X, 0x%08X)\n" % (high_start, error_value))
    out.append("    }\n\n")
    out.append("    /// The serialized trie (index followed by data).\n")
    out.append("    #[allow(dead_code)] // upstream member, only the lookups are used so far\n")
    out.append("    #[inline(always)]\n")
    out.append("    pub(crate) const fn data() -> &'static [u32] {\n")
    out.append("        &DATA\n")
    out.append("    }\n")
    out.append("}\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("static DATA: [u32; %d] = [\n" % len(data))
    for i in range(0, len(data), 12):
        out.append("    " + ", ".join("0x%08X" % v for v in data[i:i + 12]) + ",\n")
    out.append("];\n")
    write(os.path.join(out_dir, rust_file), "".join(out))


def convert_script_extensions(upstream_dir, out_dir, version):
    source_file = "ScriptExtensions.data.cs"
    text = read(os.path.join(upstream_dir, source_file))
    literals = array_literals(text)
    if len(literals) != 2:
        sys.exit("%s: expected two array literals, found %d" % (source_file, len(literals)))

    # The offsets keep their per-entry comments (the set each index stands for).
    offsets = []
    for line in literals[0].splitlines():
        match = re.match(r"\s*(\d+)\s*,?\s*(?://\s*(.*))?$", line)
        if match:
            offsets.append((int(match.group(1)), (match.group(2) or "").strip()))
        elif line.strip():
            sys.exit("%s: cannot parse offsets line %r" % (source_file, line))
    sets = parse_numbers(literals[1])
    if offsets[-1][0] != len(sets):
        sys.exit("%s: the last offset does not match the set data length" % source_file)

    out = [header(version, source_file)]
    out.append("// Indexed by the SCRIPTEXTENSIONS field of the unicode data trie. Each logical set i lives in\n")
    out.append("// SCRIPT_EXTENSION_SETS[SCRIPT_EXTENSION_SET_OFFSETS[i]..SCRIPT_EXTENSION_SET_OFFSETS[i + 1]].\n")
    out.append("// Index 0 is the implicit empty set: the codepoint has no overriding Script_Extensions\n")
    out.append("// value and falls back to its primary Script property.\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("pub(super) static SCRIPT_EXTENSION_SET_OFFSETS: [u16; %d] = [\n" % len(offsets))
    for value, comment in offsets:
        out.append("    %d,%s\n" % (value, (" // " + comment) if comment else ""))
    out.append("];\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append("pub(super) static SCRIPT_EXTENSION_SETS: [u8; %d] = [\n" % len(sets))
    for i in range(0, len(sets), 16):
        out.append("    " + ", ".join(str(v) for v in sets[i:i + 16]) + ",\n")
    out.append("];\n")
    write(os.path.join(out_dir, "script_extensions_data.rs"), "".join(out))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("upstream", help="path of the upstream checkout")
    parser.add_argument("--out", help="output directory (default: %s in this workspace)" % DEFAULT_OUT)
    args = parser.parse_args()

    upstream_dir = os.path.join(args.upstream, UPSTREAM_DIR)
    if not os.path.isdir(upstream_dir):
        sys.exit("not an upstream checkout: %s does not exist" % upstream_dir)
    workspace = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = args.out or os.path.join(workspace, DEFAULT_OUT)
    os.makedirs(out_dir, exist_ok=True)

    version = unicode_version(upstream_dir)
    for source_file, rust_file, struct_name in TRIES:
        convert_trie(upstream_dir, out_dir, version, source_file, rust_file, struct_name)
    convert_script_extensions(upstream_dir, out_dir, version)
    print("Unicode version %s" % version)


if __name__ == "__main__":
    main()
