#!/usr/bin/env python3
"""Converts the upstream Unicode property enums and alias tables (C#) to Rust.

Upstream (Avalonia, MIT) generates these files with the tool
``src/tools/Avalonia.UnicodeTrieGenerator`` (``UnicodeEnumsGenerator``) from the
Unicode Character Database. The numeric value of every enum member is what the
generated tries store, so the Rust enums must be regenerated together with the
tries (``scripts/convert-unicode-tries.py``) whenever upstream updates its
Unicode data. The generator tool itself is NOT ported and is not run here.

Inputs (``<upstream>/src/Avalonia.Base/Media/TextFormatting/Unicode``) and
outputs (``src/FerroUI.Base/media/text_formatting/unicode``):

    BiDiClass.cs                -> bidi_class.rs
    BiDiPairedBracketType.cs    -> bidi_paired_bracket_type.rs
    GeneralCategory.cs          -> general_category.rs
    GraphemeBreakClass.cs       -> grapheme_break_class.rs
    IndicConjunctBreakClass.cs  -> indic_conjunct_break_class.rs
    EastAsianWidthClass.cs      -> east_asian_width_class.rs
    LineBreakClass.cs           -> line_break_class.rs
    WordBreakClass.cs           -> word_break_class.rs
    SentenceBreakClass.cs       -> sentence_break_class.rs
    Script.cs                   -> script.rs
    PropertyValueAliasHelper.cs -> property_value_alias_helper.rs

How to rerun
------------
    python3 scripts/convert-unicode-enums.py /path/to/upstream/checkout

Only the Python standard library is used.
"""

import argparse
import os
import re
import sys

UPSTREAM_DIR = os.path.join("src", "Avalonia.Base", "Media", "TextFormatting", "Unicode")
DEFAULT_OUT = os.path.join("src", "FerroUI.Base", "media", "text_formatting", "unicode")

ENUMS = [
    ("BiDiClass.cs", "bidi_class.rs"),
    ("BiDiPairedBracketType.cs", "bidi_paired_bracket_type.rs"),
    ("GeneralCategory.cs", "general_category.rs"),
    ("GraphemeBreakClass.cs", "grapheme_break_class.rs"),
    ("IndicConjunctBreakClass.cs", "indic_conjunct_break_class.rs"),
    ("EastAsianWidthClass.cs", "east_asian_width_class.rs"),
    ("LineBreakClass.cs", "line_break_class.rs"),
    ("WordBreakClass.cs", "word_break_class.rs"),
    ("SentenceBreakClass.cs", "sentence_break_class.rs"),
    ("Script.cs", "script.rs"),
]

RUST_MODULE = {
    "BidiClass": "bidi_class",
    "BidiPairedBracketType": "bidi_paired_bracket_type",
    "GeneralCategory": "general_category",
    "LineBreakClass": "line_break_class",
    "WordBreakClass": "word_break_class",
    "Script": "script",
}


def read(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d bytes)" % (path, len(text)))


def header(source_file):
    return (
        "// Generated by scripts/convert-unicode-enums.py from the upstream file\n"
        "// `%s`. Do not edit.\n\n" % source_file
    )


def doc_text(lines):
    """Turns C# xml doc comment lines into plain rustdoc lines."""
    text = "\n".join(lines)
    text = re.sub(r"</?summary>", "", text)
    text = re.sub(r'<see cref="([^"]+)"\s*/>', r"`\1`", text)
    text = re.sub(r"</?c>", "`", text)
    return [line.strip() for line in text.splitlines() if line.strip()]


def convert_enum(upstream_dir, out_dir, source_file, rust_file):
    text = read(os.path.join(upstream_dir, source_file))
    lines = text.splitlines()
    declaration = None
    variants = []  # (name, tag comment, docs)
    enum_docs = []
    pending_docs = []
    inside = False
    for line in lines:
        stripped = line.strip()
        if declaration is None:
            match = re.match(r"(public|internal)\s+enum\s+(\w+)", stripped)
            if match:
                declaration = (match.group(1), match.group(2))
                enum_docs = doc_text(pending_docs)
                pending_docs = []
            elif stripped.startswith("///"):
                pending_docs.append(stripped[3:])
            continue
        if stripped == "{":
            inside = True
            continue
        if not inside:
            continue
        if stripped.startswith("}"):
            break
        if stripped.startswith("///"):
            pending_docs.append(stripped[3:])
            continue
        if not stripped:
            continue
        match = re.match(r"(\w+)\s*,?\s*(?://\s*(.*))?$", stripped)
        if not match:
            sys.exit("%s: cannot parse enum member %r" % (source_file, line))
        variants.append((match.group(1), (match.group(2) or "").strip(), doc_text(pending_docs)))
        pending_docs = []
    if declaration is None or not variants:
        sys.exit("%s: no enum found" % source_file)

    visibility = "pub" if declaration[0] == "public" else "pub(crate)"
    name = declaration[1]
    out = [header(source_file)]
    if enum_docs:
        for doc in enum_docs:
            out.append("/// %s\n" % doc)
    else:
        out.append("/// The Unicode `%s` property values, numbered as the generated tries store them.\n" % name)
    out.append("#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]\n")
    out.append("#[repr(i32)]\n")
    out.append("%s enum %s {\n" % (visibility, name))
    for index, (variant, tag, docs) in enumerate(variants):
        for doc in docs:
            out.append("    /// %s\n" % doc)
        if tag:
            if docs:
                out.append("    ///\n")
            out.append("    /// Property value alias: `%s`\n" % tag)
        if index == 0:
            out.append("    #[default]\n")
        out.append("    %s = %d,\n" % (variant, index))
    out.append("}\n\n")
    out.append("impl %s {\n" % name)
    out.append("    /// The number of values.\n")
    if visibility == "pub(crate)":
        out.append("    #[allow(dead_code)] // part of the generated surface, not used yet\n")
    out.append("    %s const COUNT: usize = %d;\n\n" % (visibility, len(variants)))
    out.append("    /// Converts the numeric value stored in the generated tries (the cast upstream performs).\n")
    out.append("    /// Values outside of the enum map to `%s` (value 0).\n" % variants[0][0])
    out.append("    #[inline]\n")
    out.append("    %s const fn from_u32(value: u32) -> Self {\n" % visibility)
    out.append("        match value {\n")
    for index, (variant, _, _) in enumerate(variants):
        if index == 0:
            continue
        out.append("            %d => Self::%s,\n" % (index, variant))
    out.append("            _ => Self::%s,\n" % variants[0][0])
    out.append("        }\n")
    out.append("    }\n")
    out.append("}\n")
    write(os.path.join(out_dir, rust_file), "".join(out))


def rust_fn_name(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def convert_alias_helper(upstream_dir, out_dir):
    source_file = "PropertyValueAliasHelper.cs"
    text = read(os.path.join(upstream_dir, source_file))

    dictionaries = {}
    for match in re.finditer(
            r"Dictionary<\s*(\w+)\s*,\s*(\w+)\s*>\s+(s_\w+)\s*=\s*new\s+Dictionary<[^>]+>\s*\{(.*?)\n\s*\};",
            text, re.S):
        key_type, value_type, name, body = match.groups()
        entries = re.findall(r"\{\s*([^,{}]+?)\s*,\s*([^,{}]+?)\s*\}", body)
        dictionaries[name] = (key_type, value_type, entries)

    functions = re.findall(
        r"public static (\w+) (\w+)\((\w+) (\w+)\)\s*\{\s*if \(!(s_\w+)\.TryGetValue\(\w+, out var value\)\)"
        r"\s*\{\s*return ([^;]+);",
        text)
    if not functions or len(functions) != len(dictionaries):
        sys.exit("%s: unexpected shape (%d functions, %d dictionaries)"
                 % (source_file, len(functions), len(dictionaries)))

    def rust_value(value):
        value = value.strip()
        if value.startswith('"'):
            return value
        enum, member = value.split(".")
        return "%s::%s" % (enum, member)

    used_enums = sorted({t for (k, v, _) in dictionaries.values() for t in (k, v) if t != "string"})
    out = [header(source_file)]
    for enum in used_enums:
        out.append("use super::%s::%s;\n" % (RUST_MODULE[enum], enum))
    out.append("\n/// Maps between Unicode property value aliases (the short tags used by the\n")
    out.append("/// Unicode Character Database) and the property enums.\n")
    out.append("pub(crate) struct PropertyValueAliasHelper;\n\n")
    out.append("// Used by the conformance tests and by code that parses UCD style tags.\n")
    out.append("#[allow(dead_code)]\n")
    out.append("impl PropertyValueAliasHelper {\n")
    for index, (return_type, fn_name, param_type, param, dictionary, default) in enumerate(functions):
        key_type, value_type, entries = dictionaries[dictionary]
        if index:
            out.append("\n")
        rust_return = "&'static str" if return_type == "string" else return_type
        rust_param = "&str" if param_type == "string" else param_type
        out.append("    pub(crate) fn %s(%s: %s) -> %s {\n" % (rust_fn_name(fn_name), param, rust_param, rust_return))
        out.append("        match %s {\n" % param)
        for key, value in entries:
            out.append("            %s => %s,\n" % (rust_value(key), rust_value(value)))
        if key_type == "string":
            out.append("            _ => %s,\n" % rust_value(default))
        else:
            # Every enum member is listed upstream; keep its fallback for members
            # added later without regenerating this file.
            out.append("            #[allow(unreachable_patterns)]\n")
            out.append("            _ => %s,\n" % rust_value(default))
        out.append("        }\n")
        out.append("    }\n")
    out.append("}\n")
    write(os.path.join(out_dir, "property_value_alias_helper.rs"), "".join(out))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("upstream", help="path of the upstream checkout")
    parser.add_argument("--out", help="output directory (default: %s in this workspace)" % DEFAULT_OUT)
    args = parser.parse_args()

    upstream_dir = os.path.join(args.upstream, UPSTREAM_DIR)
    if not os.path.isdir(upstream_dir):
        sys.exit("not an upstream checkout: %s does not exist" % upstream_dir)
    workspace = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = args.out or os.path.join(workspace, DEFAULT_OUT)
    os.makedirs(out_dir, exist_ok=True)

    for source_file, rust_file in ENUMS:
        convert_enum(upstream_dir, out_dir, source_file, rust_file)
    convert_alias_helper(upstream_dir, out_dir)


if __name__ == "__main__":
    main()
