#!/usr/bin/env python3
"""Generates the mechanical part of the markup metadata of FerroUI.Base and
FerroUI.Controls (the `markup_types/` module of each crate).

The managed original answers markup's questions with reflection; the port
states the answers as declarations (see "Markup metadata" in
docs/porting/PORTING-GUIDE.md). Most of them follow mechanically from the
upstream C# sources and the Rust sources, so this script derives them by
comparing the two:

    target        generated file (per crate)             from
    ------        --------------------------             ----
    enums         markup_types/enums.rs                  every public enum / bitflags type of the crate that
                                                         upstream declares public, with upstream member names
    classes       markup_types/classes.rs                the `markup:` part of every class listed in the
                                                         crate's register_types.rs: [Content], plain
                                                         properties, routed events as static values, plain
                                                         events, type attributes, attributes of registered
                                                         properties
    named-values  markup_types/named_values.rs (Base)    the static values of `Colors` and `Brushes`
    rust-paths    rust_paths.rs (Base, Controls,         the shortest public Rust path of every registered class
                  Markup.Xaml, Dialogs)                  and markup type, for the emitter of Rust source
                                                         (scripts/rust_paths.py)

Everything else in `markup_types/` (mod.rs, values.rs, contracts.rs,
plain.rs, the tests) is written by hand and never touched by this script.

What cannot be derived (constructors with arguments, members whose Rust
signature needs an adapter closure, notes) is hand-maintained in
scripts/markup_types_overrides.py and merged into the generated class
declarations; edit that file, never the generated ones.

How to rerun (from the repository root; Python 3, standard library only):

    python3 scripts/generate_markup_types.py --upstream ../Avalonia

Options:
    --upstream P   the reference checkout of the upstream project (its `src`
                   directory is read); default: $FERROUI_UPSTREAM, else the
                   sibling directory `Avalonia` of the repository
    --check        do not write; exit with status 1 and name the stale files
                   (with a line-count summary of the difference) if a
                   generated file differs from what would be generated
    --target T     only `enums`, `classes`, `named-values` or `rust-paths` (repeatable)
    --report       also print what was left out and why (members that are not
                   ported, events whose arguments cannot be held in an untyped
                   value, plain properties that need a hand-written override)

The output is deterministic: it depends only on the upstream checkout, the
Rust sources of the two crates, the override file and this script. Because
the Rust sources are an input, rerun it (or `--check` it) after porting a
class or changing the public interface of one.

Tables in this script:

    XMLNS_NAMESPACES   the dotted namespaces mapped to the framework XML
                       namespace (mirrors the ASSEMBLY statics of the two
                       register_types.rs)
    ENUM_EXTRA         enumerations outside those namespaces that are declared
                       anyway
    ENUM_NAMESPACE     namespaces the scanner cannot read from upstream
    ENUM_RENAMED       upstream member -> Rust variant, where they differ
    FLAG_CONSTANTS     upstream flags member -> Rust constant, where the
                       SCREAMING_SNAKE_CASE rule does not give it
    EVENT_ARGS_NOT_COPIED
                       event argument types whose instances must reach the
                       handler itself (cancellable), so the events cannot be
                       adapted by cloning the arguments
"""

import argparse
import difflib
import importlib.util
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import rust_paths  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
CRATES = ["FerroUI.Base", "FerroUI.Controls"]
# The crates whose registered types get a table of public Rust paths (`rust_paths.rs`).
RUST_PATH_CRATES = ["FerroUI.Base", "FerroUI.Controls", os.path.join("Markup", "FerroUI.Markup.Xaml"), "FerroUI.Dialogs"]
UPSTREAM_PROJECTS = {"FerroUI.Base": "Avalonia.Base", "FerroUI.Controls": "Avalonia.Controls"}
OVERRIDES = os.path.join(ROOT, "scripts", "markup_types_overrides.py")

HEADER = "// @generated by scripts/generate_markup_types.py — do not edit\n"

XMLNS_NAMESPACES = {
    "FerroUI", "FerroUI.Animation", "FerroUI.Animation.Easings", "FerroUI.Controls", "FerroUI.Data",
    "FerroUI.Data.Converters", "FerroUI.Input", "FerroUI.Input.GestureRecognizers", "FerroUI.Input.TextInput",
    "FerroUI.Layout", "FerroUI.LogicalTree", "FerroUI.Media", "FerroUI.Media.Imaging",
    "FerroUI.Media.Transformation", "FerroUI.Styling", "FerroUI.Automation", "FerroUI.Controls.Embedding",
    "FerroUI.Controls.Presenters", "FerroUI.Controls.Primitives", "FerroUI.Controls.Shapes",
    "FerroUI.Controls.Templates", "FerroUI.Controls.Notifications", "FerroUI.Controls.Chrome",
    "FerroUI.Controls.Documents",
}
ENUM_EXTRA = {
    "RoutingStrategies", "PlatformThemeVariant", "ResetBehavior", "Corners", "FormFactorType", "WellKnownFolder",
    "DayOfWeek", "DateTimeKind", "NumberStyles", "CalendarWeekRule",
}
ENUM_NAMESPACE = {
    "RelativeUnit": "FerroUI",
    "GridUnitType": "FerroUI.Controls",
    "Key": "FerroUI.Input",
    "PhysicalKey": "FerroUI.Input",
    # Mirror types of the runtime library.
    "UriKind": "System",
    "DayOfWeek": "System",
    "DateTimeKind": "System",
    "NumberStyles": "System.Globalization",
    "CalendarWeekRule": "System.Globalization",
}
ENUM_RENAMED = {"RelativeSourceMode": {"Self": "SelfMode"}}
FLAG_CONSTANTS = {"XButton1MouseButton": "X_BUTTON_1_MOUSE_BUTTON", "XButton2MouseButton": "X_BUTTON_2_MOUSE_BUTTON"}
EVENT_ARGS_NOT_COPIED = set()

ENUM_USES = {
    "FerroUI.Base": """use crate::animation::*;
use crate::collections::ResetBehavior;
use crate::data::core::ValueTypes;
use crate::data::*;
use crate::ferro_markup_enum;
use crate::input::navigation::*;
use crate::input::text_input::*;
use crate::input::*;
use crate::interactivity::RoutingStrategies;
use crate::layout::*;
use crate::logical_tree::*;
use crate::media::imaging::*;
use crate::media::transformation::*;
use crate::media::*;
use crate::metadata::{MarkupType, MarkupTyped};
use crate::platform::storage::WellKnownFolder;
use crate::platform::{FormFactorType, PlatformThemeVariant};
use crate::rendering::*;
use crate::styling::*;
use crate::utilities::{CalendarWeekRule, DateTimeKind, DayOfWeek, UriKind};
use crate::RelativeUnit;
""",
    "FerroUI.Controls": """use crate::automation::peers::*;
use crate::automation::*;
use crate::chrome::*;
use crate::converters::*;
use crate::platform::*;
use crate::primitives::popup_positioning::*;
use crate::primitives::*;
use crate::*;
use ferroui_base::data::core::ValueTypes;
use ferroui_base::ferro_markup_enum;
use ferroui_base::metadata::{MarkupType, MarkupTyped};
""",
}

CLASS_USES = {
    "FerroUI.Base": """use super::plain::{new_resource_key, property_value};
use crate::animation::*;
use crate::collections::*;
use crate::controls::*;
use crate::data::core::ValueTypes;
use crate::data::{BindingBase, BindingExpressionBase, BindingPriority};
use crate::input::gesture_recognizers::*;
use crate::input::text_input::*;
use crate::input::*;
use crate::interactivity::*;
use crate::layout::*;
use crate::logical_tree::*;
use crate::media::effects::*;
use crate::media::imaging::*;
use crate::media::*;
use crate::ferro_class_info;
use crate::metadata::{into_markup_value, MarkupDelegate, MarkupType};
use crate::reactive::IDisposable;
use crate::styling::*;
use crate::utilities::EventArgs;
use crate::*;
use std::rc::Rc;
""",
    "FerroUI.Controls": """use crate::animation::*;
use crate::application_lifetimes::IApplicationLifetime;
use crate::automation::peers::*;
use crate::chrome::*;
use crate::documents::*;
use crate::presenters::*;
use crate::pull_to_refresh::*;
use crate::templates::{DataTemplates, IDataTemplate, ITemplateOf};
use crate::primitives::*;
use crate::*;
use ferroui_base::animation::easings::Easing;
use ferroui_base::animation::TimeSpan;
use ferroui_base::collections::FerroList;
use ferroui_base::controls::{Classes, IResourceDictionary, ResourceDictionary, ResourcesChangedEventArgs};
use ferroui_base::data::core::ValueTypes;
use ferroui_base::input::*;
use ferroui_base::interactivity::*;
use ferroui_base::media::{
    FontFamily, FontFeatureCollection, FontStretch, FontStyle, FontWeight, IBrush, TextAlignment, TextDecorationCollection,
    TextTrimming, TextWrapping,
};
use ferroui_base::metadata::{into_markup_value, MarkupDelegate, MarkupType};
use ferroui_base::styling::*;
use ferroui_base::utilities::{CancelEventArgs, EventArgs};
use ferroui_base::{ferro_class_info, BoxedValue, FerroObject, IFerroDependencyResolver, PixelPoint, Rect, Ref, Size, Vector};
use std::rc::Rc;
""",
}

# --------------------------------------------------------------------------
# Helpers


def snake(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", name).lower()


def read(path):
    with open(path, encoding="utf-8-sig", errors="replace") as f:
        return f.read()


def walk(directory, extension):
    """The files under `directory` with `extension`, in a stable order."""
    result = []
    for current, directories, files in os.walk(directory):
        directories.sort()
        for name in sorted(files):
            if name.endswith(extension):
                result.append(os.path.join(current, name))
    return result


def is_product_source(path):
    name = os.path.basename(path)
    return not (
        name.endswith("_tests.rs")
        or "/tests/" in path
        or "/testing/" in path
        or "/markup_types/" in path
        or "test_support" in name
        or "mocks" in name
    )


_MODULES = {}


def declared_modules(path):
    """The names of the modules the Rust file `path` declares (`mod x;`, with any visibility)."""
    if path not in _MODULES:
        text = read(path) if os.path.exists(path) else ""
        _MODULES[path] = set(re.findall(r"^\s*(?:pub(?:\([a-z]+\))?\s+)?mod\s+(\w+)\s*;", text, re.M))
    return _MODULES[path]


def is_compiled(crate_root, path):
    """Whether the file is part of the crate: every module on its path is declared by its
    parent (a file that is in the directory but not yet wired into the crate is not read)."""
    parts = os.path.relpath(path, crate_root).split(os.sep)
    parts[-1] = parts[-1][:-3]
    if parts[-1] == "mod":
        parts.pop()
    if parts in ([], ["lib"]):
        return True
    parent = os.path.join(crate_root, "lib.rs")
    directory = crate_root
    for part in parts:
        if part not in declared_modules(parent):
            return False
        directory = os.path.join(directory, part)
        parent = os.path.join(directory, "mod.rs") if os.path.isdir(directory) else directory + ".rs"
    return True


def strip_cs_comments(text):
    text = re.sub(r"//[^\n]*", "", text)
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def block_end(text, start):
    """The index after the brace that closes the block opened before `start`."""
    depth, i = 1, start
    while depth and i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
        i += 1
    return i


class Sources:
    """The Rust sources of the two crates and the upstream C# sources."""

    def __init__(self, upstream):
        self.upstream = upstream
        self.rust = {
            crate: [
                p
                for p in walk(os.path.join(SRC, crate), ".rs")
                if is_product_source(p) and is_compiled(os.path.join(SRC, crate), p)
            ]
            for crate in CRATES
        }
        self.rust_text = {p: read(p) for crate in CRATES for p in self.rust[crate]}
        self.cs = {}
        for project in UPSTREAM_PROJECTS.values():
            for path in walk(os.path.join(upstream, project), ".cs"):
                self.cs[path] = strip_cs_comments(read(path))
        self.cs_by_type = {}
        for path, text in self.cs.items():
            for m in re.finditer(r"\b(?:class|struct|interface)\s+(\w+)", text):
                self.cs_by_type.setdefault(m.group(1), set()).add(path)
        self.members = {crate: self._rust_members(crate) for crate in CRATES}
        self.property_signatures = " ".join(
            signature
            for crate in CRATES
            for owner in self.members[crate].values()
            for (name, signature, _) in owner
            if name.endswith("_property")
        )

    def _rust_members(self, crate):
        """owner type -> [(function name, signature, visibility)] of its inherent functions."""
        members = {}
        for path in self.rust[crate]:
            owner = None
            lines = self.rust_text[path].split("\n")
            for i, line in enumerate(lines):
                m = re.match(r"\s*(?:(?:\w+::)?ferro_properties!\s*\{\s*)?impl(?:<[^>]*>)?\s+(\w+)\s*(?:,.*)?(?:\{.*)?$", line)
                if m and " for " not in line:
                    owner = m.group(1)
                elif re.match(r"impl\b.* for ", line):
                    owner = None
                m = re.search(
                    r"^\s*(?:(?:\w+::)?ferro_property!\()?\s*(?:#\[[^\]]*\]\s*)*(pub(?:\([a-z]+\))?\s+)?(?:const\s+)?fn (\w+)\s*(?:<[^>]*>)?\(",
                    line,
                )
                if m and owner:
                    signature, j = line.strip(), i
                    while "{" not in signature and ";" not in signature and j < i + 12 and j + 1 < len(lines):
                        j += 1
                        signature += " " + lines[j].strip()
                    signature = signature.split("{")[0].strip()
                    members.setdefault(owner, []).append((m.group(2), signature, (m.group(1) or "").strip()))
        return members

    def rust_type_is_boxable(self, name):
        """Whether the Rust type `name` is `Clone + PartialEq` (can be held in an untyped value)."""
        for text in self.rust_text.values():
            m = re.search(r"((?:#\[[^\n]*\]\s*\n)*)pub struct " + name + r"\b", text)
            if not m:
                continue
            derives = " ".join(re.findall(r"derive\(([^)]*)\)", m.group(1)))
            has = lambda trait: bool(
                re.search(r"\b" + trait + r"\b", derives) or re.search(r"impl\s+" + trait + r" for " + name + r"\b", text)
            )
            return has("Clone") and has("PartialEq")
        return False


# --------------------------------------------------------------------------
# Enumerations


def upstream_enums(sources):
    """name -> [(namespace, is public, members in declaration order)]"""
    result = {}
    for path in sorted(sources.cs):
        text = sources.cs[path]
        namespace = re.search(r"namespace\s+([\w.]+)", text)
        namespace = namespace.group(1) if namespace else ""
        # The key enumerations are shared with the remote protocol, where they
        # are compiled into another namespace.
        if namespace.startswith("Avalonia.Remote.Protocol"):
            namespace = "Avalonia.Input"
        for m in re.finditer(r"\b(public|internal)\s+enum\s+(\w+)[^{]*\{(.*?)\}", text, re.S):
            visibility, name, body = m.groups()
            body = re.sub(r"\[[^\]]*\]", "", body)
            members = [x.strip().split("=")[0].strip() for x in body.split(",") if x.strip()]
            result.setdefault(name, []).append((namespace.replace("Avalonia", "FerroUI"), visibility == "public", members))
    return result


def rust_enums(sources, crate):
    """[(name, kind, members, declared constants, file)] of the public field-less enums and flags types."""
    result = []
    for path in sources.rust[crate]:
        text = sources.rust_text[path]
        for m in re.finditer(r"^pub enum (\w+)\s*\{(.*?)^\}", text, re.S | re.M):
            name, body = m.groups()
            body = re.sub(r"//[^\n]*", "", body)
            body = re.sub(r"#\[[^\]]*\]", "", body)
            if re.search(r"[({]", body):
                continue
            members = [x.strip().split("=")[0].strip() for x in body.split(",") if x.strip()]
            result.append((name, "enum", members, path))
        for m in re.finditer(r"bitflags(?:::bitflags)?!\s*\{(.*?)^\}", text, re.S | re.M):
            for m2 in re.finditer(r"pub struct (\w+)\s*:\s*\w+\s*\{(.*?)\n    \}", m.group(1), re.S):
                result.append((m2.group(1), "flags", re.findall(r"const (\w+)\s*=", m2.group(2)), path))
    return result


def wrap_members(members):
    lines, current = [], "       "
    for member in members:
        if len(current) + len(member) + 2 > 116:
            lines.append(current)
            current = "       "
        current += " " + member + ","
    lines.append(current)
    return "\n".join(lines)


def generate_enums(sources, crate, report):
    upstream = upstream_enums(sources)
    by_namespace = {}
    # An enumeration that declares its metadata next to the type is not generated.
    declared_elsewhere = set()
    for text in sources.rust_text.values():
        declared_elsewhere.update(re.findall(r"^(?:\w+::)?ferro_markup_enum!\(\s*(?:flags\s+)?(\w+)", text, re.M))
    for name, kind, members, path in rust_enums(sources, crate):
        if name in declared_elsewhere:
            report.append("%s: enum %s: declares its metadata in its own file; not generated" % (crate, name))
            continue
        declarations = [u for u in upstream.get(name, []) if u[1]]
        if name in ENUM_NAMESPACE:
            namespace = ENUM_NAMESPACE[name]
            upstream_members = declarations[0][2] if declarations else members
            if not declarations and kind == "flags":
                # The member names of the mirrored type: the constants in PascalCase.
                upstream_members = ["".join(part.capitalize() for part in member.split("_")) for member in members]
        elif not declarations:
            continue
        else:
            namespace, _, upstream_members = declarations[0]
        is_property_type = bool(re.search(r"\b" + name + r"\b", sources.property_signatures))
        if namespace.startswith("FerroUI.Rendering.Composition"):
            continue
        if namespace not in XMLNS_NAMESPACES and namespace != "System" and not is_property_type and name not in ENUM_EXTRA:
            continue
        text = sources.rust_text[path]
        constants = re.findall(r"pub const (\w+): " + name + r"\b", text)
        renamed = ENUM_RENAMED.get(name, {})
        entries, missing = [], []
        if kind == "flags":
            known = set(members) | set(constants)
            for member in upstream_members:
                constant = FLAG_CONSTANTS.get(member, re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", member).upper())
                if constant in known:
                    entries.append("    %s = %s::%s,\n" % (member, name, constant))
                elif member in known:
                    entries.append("    %s = %s::%s,\n" % (member, name, member))
                else:
                    missing.append(member)
            declaration = 'ferro_markup_enum!(flags %s {\n%s}, { namespace: "%s" });\n' % (name, "".join(entries), namespace)
        else:
            known = set(members) | set(constants)
            for member in upstream_members:
                if member in renamed:
                    entries.append("%s = %s" % (member, renamed[member]))
                elif member in known:
                    entries.append(member)
                else:
                    missing.append(member)
            declaration = 'ferro_markup_enum!(%s { %s }, { namespace: "%s" });\n' % (name, ", ".join(entries), namespace)
            if len(declaration) > 119:
                declaration = 'ferro_markup_enum!(\n    %s {\n%s\n    },\n    { namespace: "%s" }\n);\n' % (
                    name,
                    wrap_members(entries),
                    namespace,
                )
        if missing:
            report.append("%s: enum %s: members not in the port: %s" % (crate, name, ", ".join(missing)))
            declaration = "// Members of the managed original that the port does not have: %s.\n%s" % (
                ", ".join(missing),
                declaration,
            )
        by_namespace.setdefault(namespace, []).append((name, declaration))

    out = [HEADER]
    out.append(
        "//! Markup metadata of the enumerations of this crate: every public\n"
        "//! enumeration (and set of flags) that markup can name or that is the type of\n"
        "//! a property, with the member names of the managed original.\n\n"
    )
    out.append(ENUM_USES[crate])
    names = []
    for namespace in sorted(by_namespace):
        out.append("\n// %s\n" % namespace)
        for name, declaration in sorted(by_namespace[namespace]):
            out.append(declaration)
            names.append(name)
    out.append("\n/// The enumerations declared in this file.\npub(super) const TYPES: &[&MarkupType] = &[\n")
    out.extend("    <%s as MarkupTyped>::MARKUP,\n" % name for name in names)
    out.append("];\n")
    out.append(
        "\n/// Registers the nullable form of each enumeration with the untyped value\n"
        "/// conversions of the current thread.\npub(super) fn register_value_types() {\n"
    )
    out.extend("    ValueTypes::register_nullable::<%s>();\n" % name for name in names)
    out.append("}\n")
    return "".join(out)


# --------------------------------------------------------------------------
# Named values (Colors, Brushes)


def generate_named_values(sources, report):
    media = os.path.join(sources.upstream, "Avalonia.Base", "Media")
    colors = re.findall(r"public static Color (\w+)\s*=>", read(os.path.join(media, "Colors.cs")))
    brushes = re.findall(r"public static IImmutableSolidColorBrush (\w+)\s*=>", read(os.path.join(media, "Brushes.cs")))
    rust_colors = read(os.path.join(SRC, "FerroUI.Base", "media", "colors.rs"))
    rust_brushes = read(os.path.join(SRC, "FerroUI.Base", "media", "brushes.rs"))
    screaming = lambda n: re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", n).upper()
    out = [HEADER]
    out.append(
        "//! Markup metadata of the named colors and brushes: the static values of\n"
        "//! `Colors` and `Brushes`, with the names of the managed original.\n\n"
        "use crate::ferro_markup_type;\n"
        "use crate::media::{Brushes, Color, Colors, IImmutableSolidColorBrush};\n"
        "use crate::metadata::{MarkupType, MarkupTyped};\n"
        "use std::rc::Rc;\n\n"
    )
    out.append("// The named values are static properties in the managed original.\n")
    out.append('ferro_markup_type!(static Colors {\n    namespace: "FerroUI.Media",\n    static_properties: [\n')
    for name in colors:
        if re.search(r"pub const " + screaming(name) + r": Color", rust_colors):
            out.append("        %s: Color { get: || Colors::%s },\n" % (name, screaming(name)))
        else:
            report.append("FerroUI.Base: Colors.%s is not ported" % name)
    out.append("    ],\n});\n\n")
    out.append("// A named brush is declared with the type the managed original declares (the contract of\n")
    out.append("// an immutable solid color brush, which has `Color`); it is assignable to the properties\n")
    out.append("// that take a brush through the registered casts of the brush contracts.\n")
    out.append('ferro_markup_type!(static Brushes {\n    namespace: "FerroUI.Media",\n    static_properties: [\n')
    for name in brushes:
        function = screaming(name).lower()
        if re.search(r"pub fn " + function + r"\(\)", rust_brushes):
            out.append(
                "        %s: Rc<dyn IImmutableSolidColorBrush> {\n            get: || -> Rc<dyn IImmutableSolidColorBrush> { Brushes::%s() }\n        },\n"
                % (name, function)
            )
        else:
            report.append("FerroUI.Base: Brushes.%s is not ported" % name)
    out.append("    ],\n});\n\n")
    out.append(
        "/// The types declared in this file.\n"
        "pub(super) const TYPES: &[&MarkupType] = &[<Colors as MarkupTyped>::MARKUP, <Brushes as MarkupTyped>::MARKUP];\n"
    )
    return "".join(out)


# --------------------------------------------------------------------------
# Classes

# The types of properties of event arguments that can be held in untyped values.
EVENT_PROPERTY_TYPES = (
    r"(?:Option<)?(?:bool|i32|u32|u64|i64|f64|String|Point|Vector|Size|Rect|PixelPoint|Key|KeyModifiers|PhysicalKey"
    r"|KeyDeviceType|KeySymbol|NavigationMethod|HoldingState|PointerType|SwipeDirection|PullDirection|DragDropEffects"
    r"|RoutedEvent|BoxedValue|Ref<\w+>)>?$"
)
PROPERTY_ATTRIBUTES = r"(DependsOn|ResolveByName|DataType|InheritDataTypeFrom\w*|TemplateContent)\b"


def top_level(body):
    """`body` with the contents of nested blocks removed."""
    out, depth = [], 0
    for c in body:
        if c == "{":
            depth += 1
            out.append("{" if depth == 1 else "")
        elif c == "}":
            depth -= 1
            out.append("}" if depth == 0 else "")
        else:
            out.append(c if depth == 0 else "")
    return "".join(out)


def upstream_class(sources, name):
    """What the upstream declaration(s) of class `name` state."""
    result = dict(files=[], attributes=[], properties=[], events=[], event_types={}, routed=[], registered=[], attached=[], raw="")
    for path in sorted(sources.cs_by_type.get(name, [])):
        text = sources.cs[path]
        m = re.search(
            r"((?:\[[^\n]*\]\s*)*)(?:public|internal)\s+(?:abstract\s+|sealed\s+|static\s+|unsafe\s+|partial\s+)*"
            r"(?:class|struct|interface)\s+" + name + r"\b(?!<)([^{]*)\{",
            text,
        )
        if not m:
            continue
        body = text[m.end() : block_end(text, m.end()) - 1]
        result["files"].append(path)
        result["raw"] += text
        result["attributes"] += [a.strip() for a in re.findall(r"\[([^\]]+)\]", m.group(1))]
        flat = top_level(body)
        for f in re.finditer(r"public\s+static\s+readonly\s+([\w<>?,. \[\]]+?)\s+(\w+)\s*(?:=|;)", flat):
            type_, field = f.groups()
            if "RoutedEvent" in type_:
                result["routed"].append(field)
            elif field.endswith("Property"):
                result["registered"].append(field[:-8])
        for p in re.finditer(
            r"((?:\[[^\]\n]+\]\s*)*)public\s+((?:new\s+|virtual\s+|override\s+|abstract\s+|static\s+|required\s+)*)"
            r"([\w<>?,. \[\]]+?)\s+(\w+)\s*(\{[^}]*\}|=>)",
            flat,
        ):
            attributes, modifiers, type_, property_, _ = p.groups()
            if type_.strip() in ("class", "struct", "interface", "enum") or "event" in type_.split():
                continue
            result["properties"].append(
                dict(
                    name=property_,
                    type=type_.strip(),
                    attributes=[x.strip() for x in re.findall(r"\[([^\]]+)\]", attributes)],
                    static="static" in modifiers,
                )
            )
        # The accessors of attached properties carry the attributes of the property.
        for a in re.finditer(r"((?:\[[^\]\n]+\]\s*)+)public\s+static\s+[\w<>?,. \[\]]+?\s+Get(\w+)\s*\(", flat):
            attributes = [x.strip() for x in re.findall(r"\[([^\]]+)\]", a.group(1))]
            result["attached"].append((a.group(2), attributes))
        for e in re.finditer(r"public\s+(?:static\s+)?event\s+([\w<>?,. ]+?)\s+(\w+)\s*[;{]", flat):
            result["events"].append(e.group(2))
            result["event_types"][e.group(2)] = e.group(1).strip().rstrip("?")
    return result


def has_public_setter(raw, property_):
    m = re.search(r"public\s+(?:new\s+|virtual\s+|override\s+)*[\w<>?,. \[\]]+\s+" + property_ + r"\s*\{", raw)
    if not m:
        return False
    body = raw[m.end() : block_end(raw, m.end())]
    for accessor in re.finditer(r"(\w+\s+)?\b(set|init)\b\s*(;|\{|=>)", body):
        return (accessor.group(1) or "").strip() not in ("private", "internal", "protected")
    return False


def constant_string(raw, name):
    m = re.search(r"const\s+string\s+" + name + r'\s*=\s*"([^"]*)"', raw)
    return m.group(1) if m else None


def registered_classes(crate):
    """[(class name, dotted namespace)] in the order of the crate's register_types.rs.

    The namespace of an entry is the one of the `// FerroUI..` comment that heads its
    section; under any other section comment it is the namespace of the module of the
    entry in the `NAMESPACES` table of the file (the longest module path that is a prefix
    of the path of the entry), which is how the runtime type gets its namespace.
    """
    whole = read(os.path.join(SRC, crate, "register_types.rs"))
    table = whole[whole.index("const NAMESPACES") : whole.index("];", whole.index("const NAMESPACES"))]
    modules = sorted(re.findall(r'\("(?:\w+)((?:::\w+)*)",\s*"([\w.]+)"\)', table), key=lambda entry: -len(entry[0]))
    text = whole[whole.index("const TYPES") :]
    result, namespace = [], None
    for line in text.split("\n"):
        m = re.match(r"\s*// (FerroUI[\w.]*)\s*$", line)
        if m:
            namespace = m.group(1)
        elif re.match(r"\s*//", line):
            namespace = None
        m = re.match(r"\s*crate::([\w:]+),", line)
        if m:
            path = "::" + m.group(1)
            of_module = next((n for prefix, n in modules if path == prefix or path.startswith(prefix + "::")), None)
            result.append((m.group(1).split("::")[-1], namespace or of_module))
    return result


def class_kinds(sources, crate):
    """class name -> True for a class of the object model, False for a static type."""
    kinds = {}
    for path in sources.rust[crate]:
        text = sources.rust_text[path]
        for m in re.finditer(r"^(?:\w+::)?ferro_static_type!\((\w+)\)", text, re.M):
            kinds[m.group(1)] = False
        for m in re.finditer(r"^impl (?:\w+::)?StaticType for (\w+)", text, re.M):
            kinds.setdefault(m.group(1), False)
        for m in re.finditer(r"^(?:\w+::)?ferro_class!\s*[({]\s*(\w+)\s*:", text, re.M):
            kinds[m.group(1)] = True
        for m in re.finditer(r"^(?:\w+::)?ferro_transition_class!\(\s*(?:///[^\n]*\s*)*(\w+)\s*:", text, re.M):
            kinds[m.group(1)] = True
    # The root class is declared by hand, without the class macro.
    kinds["FerroObject"] = True
    return kinds


def translate_attribute(attribute, ported):
    """An upstream property attribute in the declaration form, or None if it names something not ported."""
    attribute = attribute.replace("Metadata.", "")
    attribute = re.sub(r"nameof\((?:\w+\.)*(\w+)\)", r'"\1"', attribute)
    for type_ in re.findall(r"typeof\((\w+)\)", attribute):
        if type_ not in ported:
            return None
    return re.sub(r"typeof\((\w+)\)", r"type(Ref<\1>)", attribute)


def generate_classes(sources, crate, overrides, report, known_event_arguments, known_event_classes):
    ported = set()
    for c in CRATES:
        ported.update(name for name, _ in registered_classes(c))
    kinds = class_kinds(sources, crate)
    # A class may have one `markup:` part: one that is declared with the class is not generated.
    declared_elsewhere = set()
    for path in sources.rust[crate]:
        for m in re.finditer(r"ferro_class_info!\(\s*(\w+)\s*\{(.*?)\n\}\);", sources.rust_text[path], re.S):
            if re.search(r"\bmarkup:", m.group(2)):
                declared_elsewhere.add(m.group(1))
    by_namespace, statics = {}, []
    for name, namespace in registered_classes(crate):
        if name not in kinds:
            report.append("%s: %s: declaration form not recognised" % (crate, name))
            continue
        if name in declared_elsewhere:
            report.append("%s: %s: declares its `markup:` part in its own file; not generated" % (crate, name))
            continue
        up = upstream_class(sources, name)
        raw = up["raw"]
        extra = overrides.get(name, {})
        members = {}
        for function, signature, visibility in sources.members[crate].get(name, []):
            members.setdefault(function, (signature, visibility))
        registered = set(up["registered"])
        rust_properties = {f[:-9] for f in members if f.endswith("_property")}

        # Plain properties, and the attributes of registered ones.
        properties = list(extra.get("properties", []))
        declared = {re.match(r"\s*(\w+)", p).group(1) for p in properties}
        property_attributes = []
        for p in up["properties"]:
            property_ = p["name"]
            if property_ in registered:
                # An attached property that the class registers and also exposes as a property of
                # its own instances (`Visual.FlowDirection`): the run-time type system projects the
                # static accessors of an attached property only, so the instance property is
                # declared, over the registered property.
                definition = members.get(snake(property_) + "_property")
                attached_type = (
                    re.search(r"->\s*AttachedProperty<(.+)>$", definition[0]) if definition and definition[1] == "pub" else None
                )
                registers = re.search(r"\b%sProperty\s*=\s*(?:AvaloniaProperty\s*\.\s*)?RegisterAttached<" % property_, raw)
                if attached_type and registers and not p["static"] and property_ not in declared and property_ not in extra.get("skip", []):
                    value_type = attached_type.group(1).strip()
                    accessors = "get: |this: &Ref<%s>| this.get_value(%s::%s_property())" % (name, name, snake(property_))
                    if has_public_setter(raw, property_):
                        accessors += ",\n                set: |this: &Ref<%s>, value: %s| this.set_value(%s::%s_property(), value)" % (
                            name, value_type, name, snake(property_))
                    properties.append("%s: %s {\n                %s\n            }" % (property_, value_type, accessors))
                    declared.add(property_)
                attributes = [a for a in p["attributes"] if re.match(PROPERTY_ATTRIBUTES + r"|AssignBinding\b", a.replace("Metadata.", ""))]
                if not attributes:
                    continue
                if snake(property_) not in rust_properties:
                    report.append("%s: %s.%s: registered property not ported (attributes %s)" % (crate, name, property_, attributes))
                    continue
                translated = [translate_attribute(a, ported) for a in attributes]
                if None in translated:
                    report.append("%s: %s.%s: attribute names a type that is not ported: %s" % (crate, name, property_, attributes))
                    translated = [a for a in translated if a]
                if translated:
                    property_attributes.append("%s: [%s]" % (property_, ", ".join(translated)))
                continue
            if p["static"] or property_ in declared or property_ in extra.get("skip", []):
                continue
            getter, setter = members.get(snake(property_)), members.get("set_" + snake(property_))
            settable = has_public_setter(raw, property_)
            if p["type"].rstrip("?") == "IResourceDictionary" and getter and setter:
                # The property is typed with the contract, as in the managed original; the
                # port holds the dictionary object.
                properties.append(
                    "%s: Rc<dyn IResourceDictionary> {\n"
                    "                get: |this: &Ref<%s>| -> Rc<dyn IResourceDictionary> { this.%s().into() },\n"
                    "                try_set: |this: &Ref<%s>, value: Rc<dyn IResourceDictionary>| {\n"
                    "                    match value.as_object().and_then(|object| object.to_ref().cast::<ResourceDictionary>()) {\n"
                    "                        Some(dictionary) => Ok(this.set_%s(dictionary)),\n"
                    "                        None => Err(\"The resource dictionary is not a ResourceDictionary.\"),\n"
                    "                    }\n"
                    "                }\n"
                    "            }" % (property_, name, snake(property_), name, snake(property_))
                )
                declared.add(property_)
                continue
            if getter and setter and getter[1] == "pub" and setter[1] == "pub" and settable:
                get_type = re.search(r"->\s*(.+)$", getter[0])
                set_type = re.search(r"\(&self,\s*\w+:\s*(.+)\)$", setter[0])
                if get_type and set_type and get_type.group(1).strip() == set_type.group(1).strip() and not re.search(r"&|impl ", get_type.group(1)):
                    attributes = [
                        translate_attribute(a, ported)
                        for a in p["attributes"]
                        if re.match(PROPERTY_ATTRIBUTES + r"|AssignBinding\b|Obsolete\b", a)
                    ]
                    suffix = " [%s]" % ", ".join(a for a in attributes if a) if attributes else ""
                    properties.append(
                        "%s: %s { get: %s::%s, set: %s::set_%s }%s"
                        % (property_, get_type.group(1).strip(), name, snake(property_), name, snake(property_), suffix)
                    )
                    declared.add(property_)
                    continue
            collection = re.search(r"List|Collection|Dictionar|Definitions|Classes|Styles|Controls|Templates|Inlines|KeyFrames", p["type"])
            get_type = re.search(r"->\s*(.+)$", getter[0]) if getter and getter[1] == "pub" else None
            if collection and not settable and get_type and not re.search(r"&|impl |\bVec<", get_type.group(1)):
                # A collection is a read-only property whose value (a shared handle) is added to.
                properties.append("%s: %s { get: %s::%s }" % (property_, get_type.group(1).strip(), name, snake(property_)))
                declared.add(property_)
                continue
            if settable or collection:
                report.append(
                    "%s: %s.%s (%s): not declared; %s"
                    % (crate, name, property_, p["type"], "its getter is `%s`" % getter[0] if getter else "it has no getter in the port")
                )
        for property_, attributes in up["attached"]:
            attributes = [a for a in attributes if re.match(PROPERTY_ATTRIBUTES, a)]
            if attributes and snake(property_) in rust_properties:
                translated = [a for a in (translate_attribute(a, ported) for a in attributes) if a]
                property_attributes.append("%s: [%s]" % (property_, ", ".join(translated)))

        # The accessors of attached properties. The run-time type system projects the pair
        # of every attached property with the host type of its registration as the type of
        # the element; where the managed original declares an accessor for another type of
        # element (`TextElement.GetFontSize(Control)` of a property registered for
        # `TextElement`), the accessor is declared as it is there.
        accessors = []
        declared_methods = " ".join(extra.get("methods", []))
        for a in re.finditer(
            r"\b(\w+)Property\s*=\s*(?:AvaloniaProperty\s*\.\s*)?RegisterAttached<\s*\w+\s*,\s*(\w+)\s*,", raw
        ):
            property_, host = a.groups()
            definition = members.get(snake(property_) + "_property")
            value_type = re.search(r"->\s*AttachedProperty<(.+)>$", definition[0]) if definition and definition[1] == "pub" else None
            if not value_type:
                continue
            value_type = value_type.group(1).strip()
            get = re.search(r"public\s+static\s+[\w<>?,. \[\]]+?\s+Get%s\s*\(\s*(\w+)\s+\w+\s*\)" % property_, raw)
            set_ = re.search(r"public\s+static\s+void\s+Set%s\s*\(\s*(\w+)\s+\w+\s*," % property_, raw)
            for kind, accessor in (("Get", get), ("Set", set_)):
                if not accessor or accessor.group(1) == host or ("fn %s%s(" % (kind, property_)) in declared_methods:
                    continue
                element = "FerroObject" if accessor.group(1) == "AvaloniaObject" else accessor.group(1)
                if element not in ported:
                    report.append("%s: %s.%s%s(%s): the type of the element is not ported" % (crate, name, kind, property_, element))
                    continue
                if kind == "Get":
                    accessors.append(
                        "static fn Get%s(Ref<%s>) -> %s =>\n                |element: Ref<%s>| element.get_value(%s::%s_property())"
                        % (property_, element, value_type, element, name, snake(property_))
                    )
                else:
                    accessors.append(
                        "static fn Set%s(Ref<%s>, %s) =>\n                |element: Ref<%s>, value: %s| element.set_value(%s::%s_property(), value)"
                        % (property_, element, value_type, element, value_type, name, snake(property_))
                    )
        methods = list(extra.get("methods", [])) + accessors

        # The content property.
        content = extra.get("content")
        if content is None:
            for p in up["properties"]:
                if any(a.replace("Metadata.", "") == "Content" for a in p["attributes"]):
                    if snake(p["name"]) in rust_properties or p["name"] in declared:
                        content = p["name"]
                    else:
                        report.append("%s: %s: [Content] %s: the property cannot be declared" % (crate, name, p["name"]))

        # Routed events as static values.
        fields = list(extra.get("fields", []))
        for field in up["routed"]:
            accessor = members.get(snake(field))
            type_ = re.search(r"->\s*(.+)$", accessor[0]) if accessor and accessor[1] == "pub" else None
            if type_:
                fields.append("%s: %s => || *%s::%s()" % (field, re.sub(r"^&'static ", "", type_.group(1).strip()), name, snake(field)))
            else:
                report.append("%s: %s.%s: routed event not ported" % (crate, name, field))

        # Plain events.
        events = list(extra.get("events", []))
        routed = {field[:-5] for field in up["routed"]}
        for event in up["events"]:
            if event in routed or any(e.startswith(event + "(") for e in events):
                continue
            subscribe = members.get(snake(event))
            if not subscribe or subscribe[1] != "pub":
                report.append("%s: %s.%s: event not ported" % (crate, name, event))
                continue
            # `EventHandler` and `EventHandler<EventArgs>` are the same handler: the sender and `EventArgs`.
            plain_handler = up["event_types"].get(event) in ("EventHandler", "EventHandler<EventArgs>")
            if re.search(r"handler: impl Fn\(\) \+ 'static", subscribe[0]) and plain_handler:
                # A plain `EventHandler`: the sender and empty arguments.
                events.append(
                    "%s(Option<BoxedValue>, EventArgs) => |this: &Ref<%s>, handler: MarkupDelegate| {\n"
                    "                let sender = this.downgrade();\n"
                    "                this.%s(move || {\n"
                    "                    handler.invoke(&[into_markup_value(sender.upgrade()), into_markup_value(EventArgs::EMPTY)]);\n"
                    "                })\n            }" % (event, name, snake(event))
                )
                continue
            if re.search(r"handler: impl Fn\(\) \+ 'static", subscribe[0]):
                events.append(
                    "%s() => |this: &Ref<%s>, handler: MarkupDelegate| this.%s(move || {\n"
                    "                handler.invoke(&[]);\n            })" % (event, name, snake(event))
                )
                continue
            m = re.search(r"handler: impl Fn\(&(\w+)\) \+ 'static", subscribe[0])
            if not m:
                report.append("%s: %s.%s: event not declared; handler form `%s`" % (crate, name, event, subscribe[0]))
            elif m.group(1) in EVENT_ARGS_NOT_COPIED:
                report.append("%s: %s.%s: event not declared; its arguments (%s) are cancellable and cannot be copied" % (crate, name, event, m.group(1)))
            elif not sources.rust_type_is_boxable(m.group(1)):
                report.append("%s: %s.%s: event not declared; its arguments (%s) are not `Clone + PartialEq`" % (crate, name, event, m.group(1)))
            else:
                # The Rust event passes no sender: the adapter passes the instance.
                # The parameters are the ones of the handler of the managed original: an event
                # declared with the plain handler raises `EventArgs` (whatever arguments derived
                # from them the instance passes).
                events.append(
                    "%s(Option<BoxedValue>, %s) => |this: &Ref<%s>, handler: MarkupDelegate| {\n"
                    "                let sender = this.downgrade();\n"
                    "                this.%s(move |e: &%s| {\n"
                    "                    handler.invoke(&[into_markup_value(sender.upgrade()), into_markup_value(e.clone())]);\n"
                    "                })\n            }"
                    % (event, "EventArgs" if plain_handler else m.group(1), name, snake(event), m.group(1))
                )

        # Type attributes.
        attributes = list(extra.get("attributes", []))
        for attribute in up["attributes"]:
            m = re.match(r"(\w+)(?:\((.*)\))?$", attribute.strip(), re.S)
            if not m:
                continue
            kind, arguments = m.groups()
            if kind in ("UsableDuringInitialization", "TrimSurroundingWhitespace", "WhitespaceSignificantCollection", "ControlTemplateScope"):
                attributes.append(kind)
            elif kind == "PseudoClasses":
                values = []
                for argument in (a.strip() for a in arguments.split(",")):
                    value = argument if argument.startswith('"') else constant_string(raw, argument)
                    if value is None:
                        values = None
                        break
                    values.append(value if value.startswith('"') else '"%s"' % value)
                if values is None:
                    if not any(a.startswith("PseudoClasses(") for a in extra.get("attributes", [])):
                        report.append("%s: %s: [%s]: constant not resolved; needs an override" % (crate, name, attribute))
                else:
                    attributes.append("PseudoClasses(%s)" % ", ".join(values))
            elif kind == "TemplatePart":
                m2 = re.match(r'\s*("?\w+"?)\s*,\s*typeof\((\w+)\)\s*(?:,\s*IsRequired\s*=\s*(true|false))?\s*$', arguments)
                part = m2 and (m2.group(1) if m2.group(1).startswith('"') else constant_string(raw, m2.group(1)))
                if not part:
                    report.append("%s: %s: [%s]: form not recognised" % (crate, name, attribute))
                elif m2.group(2) not in ported:
                    report.append("%s: %s: [%s]: the part type is not a ported class" % (crate, name, attribute))
                else:
                    part = part if part.startswith('"') else '"%s"' % part
                    required = ", IsRequired = " + m2.group(3) if m2.group(3) else ""
                    attributes.append("TemplatePart(%s, type(Ref<%s>)%s)" % (part, m2.group(2), required))

        def part(label, items, indent):
            return "%s%s: [\n%s%s],\n" % (indent, label, "".join("%s    %s,\n" % (indent, i) for i in items), indent)

        if not kinds[name]:
            # A static type: its metadata is linked to the runtime type and registered.
            if not (fields or property_attributes or methods or extra.get("static_properties")):
                continue
            body = '    namespace: "%s",\n    type_info: %s,\n' % (namespace, name)
            if property_attributes:
                body += part("property_attributes", property_attributes, "    ")
            if methods:
                body += part("methods", methods, "    ")
            if fields:
                body += part("fields", fields, "    ")
            if extra.get("static_properties"):
                body += part("static_properties", extra["static_properties"], "    ")
            by_namespace.setdefault(namespace, []).append((name, "ferro_markup_type!(static %s {\n%s});\n" % (name, body)))
            statics.append(name)
            continue

        body = ""
        if content:
            body += "        content: %s,\n" % content
        if extra.get("parse"):
            body += "        parse: %s,\n" % extra["parse"]
        for label, items in (
            ("constructors", extra.get("constructors", [])),
            ("properties", properties),
            ("property_attributes", property_attributes),
            ("methods", methods),
            ("fields", fields),
            ("static_properties", extra.get("static_properties", [])),
            ("events", events),
        ):
            if items:
                body += part(label, items, "        ")
        if attributes:
            joined = ", ".join(attributes)
            body += "        attributes: [%s],\n" % joined if len(joined) < 90 else part("attributes", attributes, "        ")
        if not body:
            continue
        note = extra.get("note", "")
        by_namespace.setdefault(namespace, []).append(
            (
                name,
                "%sferro_class_info!(%s {\n    markup: {\n        namespace: \"%s\",\n%s    },\n});\n"
                % (note + "\n" if note else "", name, namespace, body),
            )
        )

    for name in overrides:
        if name not in kinds and not name.startswith("_"):
            report.append("%s: override for %s, which is not a class of the crate" % (crate, name))

    out = [HEADER]
    out.append(
        "//! The `markup` part of the classes of the object model of this crate:\n"
        "//! what markup needs to know about each class beyond its registered\n"
        "//! properties (content property, plain properties, constructors with\n"
        "//! arguments, methods, routed events as static values, plain events,\n"
        "//! attributes of the type and of its registered properties), as the managed\n"
        "//! original declares it. The hand-written members come from\n"
        "//! `scripts/markup_types_overrides.py`.\n"
        "//!\n"
        "//! A plain event lists the parameters of the handler of the managed\n"
        "//! original: nothing for an event without arguments, the sender and the\n"
        "//! arguments otherwise (the adapter passes the instance as the sender).\n\n"
        "// Obsolete members of the managed original are declared too (with `[Obsolete]`).\n"
        "#![allow(deprecated)]\n\n"
    )
    out.append(CLASS_USES[crate])
    for namespace in sorted(by_namespace):
        out.append("\n// %s\n" % namespace)
        for name, declaration in sorted(by_namespace[namespace]):
            out.append("\n" + declaration)
    # The typed routed events: an instantiation of `RoutedEvent<TEventArgs>` per type of
    # arguments of the events declared above. The base crate declares them on the type
    # itself; another crate cannot (the type is not its own) and uses a marker.
    arguments = sorted(set(re.findall(r": RoutedEvent<(\w+)> =>", "".join(out))) - set(known_event_arguments))
    known_event_arguments.extend(arguments)
    events = []
    if arguments:
        out.append("\n// FerroUI.Interactivity\n")
        if crate != "FerroUI.Base":
            out.append(
                "\n/// Carries the metadata of `RoutedEvent<TEventArgs>` for the arguments of this crate.\n"
                "pub(crate) struct RoutedEventOf<TEventArgs>(std::marker::PhantomData<TEventArgs>);\n"
            )
        for argument in arguments:
            type_ = ("RoutedEvent<%s>" if crate == "FerroUI.Base" else "RoutedEventOf<%s>") % argument
            events.append(type_)
            out.append(
                "\nferro_markup_type!(class %s as \"RoutedEvent`1\" {\n"
                "    namespace: \"FerroUI.Interactivity\",\n"
                "    handles: [RoutedEvent<%s>, Option<RoutedEvent<%s>>],\n"
                "    base: RoutedEvent,\n"
                "    generic: \"RoutedEvent`1\" [%s],\n"
                "});\n" % (type_, argument, argument, argument)
            )
    # The typed arguments of routed events: live handles like the base arguments
    # (`Rc<dyn IRoutedEventArgs>`), with the public properties of the managed original
    # whose Rust accessors return a type that can be held in an untyped value.
    argument_bases = {}
    for path in sources.rust[crate]:
        for m in re.finditer(r"^\s*(?:\w+::)*ferro_routed_event_args!\((\w+)\s*:\s*(\w+)\)", sources.rust_text[path], re.M):
            argument_bases[m.group(1)] = m.group(2)
    typed = [a for a in arguments if a in argument_bases]
    for argument in list(typed):
        base = argument_bases[argument]
        while base in argument_bases and base not in typed and base not in known_event_classes:
            typed.append(base)
            base = argument_bases[base]
    typed = sorted(set(typed) - set(known_event_classes))
    known_event_classes.extend(typed)
    argument_classes = []
    if typed:
        out.append(
            "\n// The typed arguments of routed events.\n\n"
            "/// The arguments of a routed event as the typed arguments `T`.\n"
            "fn typed_event_args<T: 'static, R>(e: &Rc<dyn IRoutedEventArgs>, f: impl FnOnce(&T) -> R) -> Result<R, String> {\n"
            "    match e.query_args(std::any::TypeId::of::<T>()).and_then(|args| args.downcast_ref::<T>()) {\n"
            "        Some(args) => Ok(f(args)),\n"
            "        None => Err(format!(\"The arguments are not {}.\", std::any::type_name::<T>())),\n"
            "    }\n"
            "}\n"
        )
    for argument in typed:
        up = upstream_class(sources, argument)
        namespace = re.search(r"namespace\s+([\w.]+)", up["raw"])
        if not namespace:
            report.append("%s: %s: event arguments not found upstream; not declared" % (crate, argument))
            continue
        members = {}
        for function, signature, visibility in sources.members[crate].get(argument, []):
            members.setdefault(function, (signature, visibility))
        properties = []
        for p in up["properties"]:
            if p["static"]:
                continue
            getter = members.get(snake(p["name"]))
            get_type = re.search(r"\(&self\)\s*->\s*(.+)$", getter[0]) if getter and getter[1] == "pub" else None
            if not get_type or not re.match(EVENT_PROPERTY_TYPES, get_type.group(1).strip()):
                report.append(
                    "%s: %s.%s: not declared (%s)"
                    % (crate, argument, p["name"], "accessor `%s`" % getter[0] if getter else "no accessor in the port")
                )
                continue
            type_ = get_type.group(1).strip()
            accessors = "try_get: |e: &Rc<dyn IRoutedEventArgs>| typed_event_args::<%s, _>(e, |e| e.%s())" % (argument, snake(p["name"]))
            setter = members.get("set_" + snake(p["name"]))
            if setter and setter[1] == "pub" and re.search(r"\(&self,\s*\w+:\s*%s\)$" % re.escape(type_), setter[0]) and has_public_setter(up["raw"], p["name"]):
                accessors += ",\n            try_set: |e: &Rc<dyn IRoutedEventArgs>, value: %s| typed_event_args::<%s, _>(e, |e| e.set_%s(value))" % (
                    type_, argument, snake(p["name"]))
            properties.append("        %s: %s {\n            %s\n        },\n" % (p["name"], type_, accessors))
        base = argument_bases[argument]
        base = base if base in known_event_classes else "Rc<dyn IRoutedEventArgs>"
        out.append(
            "\nferro_markup_type!(class %s {\n    namespace: \"%s\",\n    handles: [%s],\n"
            "    this: Rc<dyn IRoutedEventArgs>,\n    base: %s,\n%s});\n"
            % (
                argument,
                namespace.group(1).replace("Avalonia", "FerroUI"),
                argument,
                base,
                "    properties: [\n%s    ],\n" % "".join(properties) if properties else "",
            )
        )
        argument_classes.append(argument)
    events = events + argument_classes
    registrations = [
        "    ValueTypes::register_cast::<RoutedEvent<%s>, RoutedEvent>(|event| event.as_routed_event());\n" % a for a in arguments
    ]
    out.append(
        "\n/// Registers the casts of the typed routed events declared in this file to the\n"
        "/// untyped routed event, with the untyped value conversions of the current thread.\n"
        "pub(super) fn register_value_types() {\n%s}\n" % "".join(registrations)
    )
    out.append(
        "\n/// The types declared in this file that are not classes: the types that own static\n"
        "/// members only and the typed routed events. (The metadata of a class is reached\n"
        "/// from its runtime type and needs no registration.)\n"
        "pub(super) const TYPES: &[&MarkupType] = &[\n"
    )
    out.extend("    <%s as MarkupTyped>::MARKUP,\n" % name for name in sorted(statics) + events)
    out.append("];\n")
    text = "".join(out)
    if statics or events:
        # Only these declarations need the two imports.
        prefix = "crate" if crate == "FerroUI.Base" else "ferroui_base"
        text = text.replace(
            CLASS_USES[crate], CLASS_USES[crate] + "use %s::ferro_markup_type;\nuse %s::metadata::MarkupTyped;\n" % (prefix, prefix)
        )
    return text


# --------------------------------------------------------------------------


def load_overrides():
    spec = importlib.util.spec_from_file_location("markup_types_overrides", OVERRIDES)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {"FerroUI.Base": module.BASE, "FerroUI.Controls": module.CONTROLS}


def main():
    parser = argparse.ArgumentParser(description="Generates the mechanical part of the markup metadata.")
    default_upstream = os.environ.get("FERROUI_UPSTREAM") or os.path.join(os.path.dirname(ROOT), "Avalonia")
    parser.add_argument("--upstream", default=default_upstream)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--report", action="store_true")
    parser.add_argument("--target", action="append", choices=["enums", "classes", "named-values", "rust-paths"])
    args = parser.parse_args()

    upstream = os.path.join(args.upstream, "src")
    if not os.path.isdir(os.path.join(upstream, "Avalonia.Base")):
        print("no upstream checkout at %s (pass --upstream or set FERROUI_UPSTREAM)" % args.upstream)
        return 2
    targets = args.target or ["enums", "classes", "named-values", "rust-paths"]
    sources = Sources(upstream)
    overrides = load_overrides()
    report, files = [], {}
    # The base crate declares its typed routed events first; the crates built on it add theirs.
    known_event_arguments = []
    known_event_classes = []
    for crate in CRATES:
        directory = os.path.join(SRC, crate, "markup_types")
        if "enums" in targets:
            files[os.path.join(directory, "enums.rs")] = generate_enums(sources, crate, report)
        if "classes" in targets:
            files[os.path.join(directory, "classes.rs")] = generate_classes(sources, crate, overrides[crate], report, known_event_arguments, known_event_classes)
    if "named-values" in targets:
        files[os.path.join(SRC, "FerroUI.Base", "markup_types", "named_values.rs")] = generate_named_values(sources, report)
    if "rust-paths" in targets:
        for crate in RUST_PATH_CRATES:
            macro = "crate::ferro_rust_paths" if crate == "FerroUI.Base" else "ferroui_base::ferro_rust_paths"
            text, missing = rust_paths.rust_paths_file(os.path.join(SRC, crate), HEADER, macro)
            files[os.path.join(SRC, crate, "rust_paths.rs")] = text
            report.extend("%s: %s" % (crate, line) for line in missing)

    stale = []
    for path in sorted(files):
        old = read(path) if os.path.exists(path) else ""
        if old == files[path]:
            continue
        diff = list(difflib.unified_diff(old.split("\n"), files[path].split("\n"), lineterm="", n=0))
        added = sum(1 for line in diff if line.startswith("+") and not line.startswith("+++"))
        removed = sum(1 for line in diff if line.startswith("-") and not line.startswith("---"))
        stale.append("%s (+%d -%d lines)" % (os.path.relpath(path, ROOT), added, removed))
        if not args.check:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(files[path])
    if args.report:
        for line in report:
            print("  " + line)
    if args.check:
        if stale:
            print("stale generated files:\n  " + "\n  ".join(stale))
            return 1
        print("generated files are up to date")
        return 0
    print("generated %d files (%d changed)" % (len(files), len(stale)))
    for line in stale:
        print("  " + line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
