#!/usr/bin/env python3
"""Generates the composition object model of FerroUI from the composition schema.

This is the port of the upstream generator
(src/tools/DevGenerators/CompositionGenerator/*.cs in Avalonia: Generator.cs,
Config.cs, Generator.ListProxy.cs, Generator.KeyFrameAnimation.cs,
Generator.Utils.cs, Generator.ConfigHelpers.cs, Extensions.cs). It reads
scripts/composition-schema.xml (a verbatim copy of upstream
src/Avalonia.Base/composition-schema.xml) and writes one Rust file per schema
class, plus composition_animations.rs and mod.rs, under
src/FerroUI.Base/rendering/composition/generated/.

How to rerun (from the repository root; Python 3, standard library only):

    python3 scripts/generate_composition.py

Options:
    --check     do not write; exit with status 1 if a generated file is stale
    --schema P  read the schema from P instead of scripts/composition-schema.xml
    --out D     write to directory D instead of the default

The output is deterministic: it depends only on the schema and this script.
Files in the output directory that the generator no longer produces are
removed.

Where upstream emits C# partial classes, this generator emits, per schema
class X, "property blocks" that a hand-written class embeds:

    XChangedFields        the changed-fields bit mask (upstream XChangedFields)
    XHooks / XProps       the UI-thread half (not for ServerOnly classes)
    ServerXHooks / ServerXProps
                          the server half

See the documentation at the top of the generated mod.rs for the contract.

Tables in this script that carry what upstream takes from the C# type system:

    TYPES            how each schema type maps to Rust and crosses a batch
    UNPORTED_TYPES   schema types that have no Rust counterpart yet; their
                     properties are skipped (the changed-fields bit stays
                     reserved) and listed in the generated file
    DEFAULTS         the DefaultValue expressions of the schema, in Rust
    SERVER_BASES     hand-written server base classes named by ServerBase /
                     Inherits, and whether they derive from ServerObject
"""

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET

HEADER = "// @generated by scripts/generate_composition.py — do not edit\n"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SCHEMA = os.path.join(ROOT, "scripts", "composition-schema.xml")
DEFAULT_OUT = os.path.join(ROOT, "src", "FerroUI.Base", "rendering", "composition", "generated")

# --------------------------------------------------------------------------
# Config (Config.cs)
# --------------------------------------------------------------------------


def _bool(element, name):
    return element.get(name, "false").strip().lower() == "true"


class GManualClass:
    def __init__(self, element):
        self.name = element.get("Name")
        self.passthrough = _bool(element, "Passthrough")
        self.server_name = element.get("ServerName")


class GImplements:
    def __init__(self, element):
        self.name = element.get("Name")
        self.server_name = element.get("ServerName")


class GProperty:
    def __init__(self, element):
        self.name = element.get("Name")
        self.client_name = element.get("ClientName")
        self.type = element.get("Type")
        self.default_value = element.get("DefaultValue")
        self.animated = _bool(element, "Animated")
        self.internal_set = _bool(element, "InternalSet")
        self.internal = _bool(element, "Internal")
        self.private = _bool(element, "Private")


class GClass:
    def __init__(self, element):
        self.name = element.get("Name")
        self.inherits = element.get("Inherits")
        self.changes_base = element.get("ChangesBase")
        self.server_base = element.get("ServerBase")
        self.custom_ctor = _bool(element, "CustomCtor")
        self.custom_server_ctor = _bool(element, "CustomServerCtor")
        self.internal = _bool(element, "Internal")
        self.server_only = _bool(element, "ServerOnly")
        self.abstract = _bool(element, "Abstract")
        self.implements = [GImplements(e) for e in element.findall("Implements")]
        self.properties = [GProperty(e) for e in element.findall("Property")]
        self.is_list = element.tag == "List"
        self.item_type = element.get("ItemType")
        if element.tag == "Brush":
            # GBrush
            self.custom_update = _bool(element, "CustomUpdate")
            self.inherits = "CompositionBrush"


class GAnimationType:
    def __init__(self, element):
        self.name = element.get("Name")
        self.type = element.get("Type")


class GConfig:
    def __init__(self, path):
        root = ET.parse(path).getroot()
        if root.tag != "NComposition":
            raise SystemExit("the schema root element must be NComposition")
        self.usings = [e.text for e in root.findall("Using")]
        self.manual_classes = [GManualClass(e) for e in root.findall("Manual")]
        # Document order across the three element kinds, like the XML
        # serializer of the reference.
        self.classes = [GClass(e) for e in root if e.tag in ("Object", "Brush", "List")]
        self.key_frame_animations = [GAnimationType(e) for e in root.findall("KeyFrameAnimation")]


# --------------------------------------------------------------------------
# Naming (Extensions.cs, Generator.cs name helpers)
# --------------------------------------------------------------------------


def snake(name):
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", name)
    s = re.sub(r"([A-Z0-9]+)([A-Z][a-z])", r"\1_\2", s)
    return s.lower()


def screaming(name):
    return snake(name).upper()


def server_name(c):
    return ("Server" + c) if c is not None else "ServerObject"


def changed_fields_type_name(cl):
    return cl.name + "ChangedFields"


def changed_fields_field_name(cl):
    return "changed_fields_of_" + snake(cl.name)


# --------------------------------------------------------------------------
# Types
# --------------------------------------------------------------------------

# How a schema type exists in Rust.
#
# kind:
#   value     a Copy value with a BatchValue impl; crosses in the value stream
#   boxed     a Copy value without a BatchValue impl; crosses as a payload
#   payload   a passthrough reference (Rc); crosses as a payload
#   resource  a passthrough reference that may be a server render resource
#             (a brush, a transform); crosses as a payload or as the id of
#             its server object (BatchResource)
#   object    a composition object; crosses as the id of its server object
#
# Each entry: kind, Rust type (for resource: the unsized target), the paths
# to import, and for resources the IServerObject cast.
TYPES = {
    "bool": ("value", "bool", []),
    "float": ("value", "f32", []),
    "double": ("value", "f64", []),
    "Vector": ("value", "Vector", ["crate::Vector"]),
    "Vector3D": ("value", "Vector3D", ["crate::Vector3D"]),
    "Quaternion": ("value", "Quaternion", ["crate::numerics::Quaternion"]),
    "Size": ("value", "Size", ["crate::Size"]),
    "CornerRadius": ("value", "CornerRadius", ["crate::CornerRadius"]),
    "RelativePoint": ("value", "RelativePoint", ["crate::RelativePoint"]),
    "Avalonia.RelativePoint": ("value", "RelativePoint", ["crate::RelativePoint"]),
    "Avalonia.RelativeScalar": ("value", "RelativeScalar", ["crate::RelativeScalar"]),
    "Avalonia.RelativeRect": ("value", "RelativeRect", ["crate::RelativeRect"]),
    "Avalonia.Matrix": ("value", "Matrix", ["crate::Matrix"]),
    "Avalonia.Media.Color": ("value", "Color", ["crate::media::Color"]),
    "Avalonia.Media.RenderOptions": ("value", "RenderOptions", ["crate::media::RenderOptions"]),
    "Avalonia.Media.TextOptions": ("value", "TextOptions", ["crate::media::TextOptions"]),
    "Avalonia.Media.PenLineCap": ("value", "PenLineCap", ["crate::media::PenLineCap"]),
    "Avalonia.Media.PenLineJoin": ("value", "PenLineJoin", ["crate::media::PenLineJoin"]),
    "Avalonia.Media.AlignmentX": ("value", "AlignmentX", ["crate::media::AlignmentX"]),
    "Avalonia.Media.AlignmentY": ("value", "AlignmentY", ["crate::media::AlignmentY"]),
    "Avalonia.Media.Stretch": ("value", "Stretch", ["crate::media::Stretch"]),
    "Avalonia.Media.TileMode": ("value", "TileMode", ["crate::media::TileMode"]),
    "RendererDebugOverlays": ("value", "RendererDebugOverlays", ["crate::rendering::RendererDebugOverlays"]),
    "LayoutPassTiming": ("value", "LayoutPassTiming", ["crate::rendering::LayoutPassTiming"]),
    "CompositionTransparencyLevel": (
        "value",
        "CompositionTransparencyLevel",
        ["crate::rendering::composition::CompositionTransparencyLevel"],
    ),
    "Avalonia.Media.ImmutableExperimentalAcrylicMaterial": (
        "boxed",
        "ImmutableExperimentalAcrylicMaterial",
        ["crate::media::ImmutableExperimentalAcrylicMaterial"],
    ),
    "Avalonia.Platform.IGeometryImpl": (
        "payload",
        "Arc<dyn IGeometryImpl>",
        ["std::sync::Arc", "crate::platform::IGeometryImpl"],
    ),
    "Avalonia.Media.IImmutableBrush": (
        "payload",
        "Rc<dyn IImmutableBrush>",
        ["std::rc::Rc", "crate::media::IImmutableBrush"],
    ),
    "Avalonia.Media.IImmutableEffect": (
        "payload",
        "Arc<dyn IImmutableEffect>",
        ["std::sync::Arc", "crate::media::IImmutableEffect"],
    ),
    "Avalonia.Media.Immutable.ImmutableDashStyle": (
        "payload",
        "Arc<ImmutableDashStyle>",
        ["std::sync::Arc", "crate::media::immutable::ImmutableDashStyle"],
    ),
    "object": ("payload", "Arc<dyn Any + Send + Sync>", ["std::sync::Arc", "std::any::Any"]),
    "Avalonia.Media.ITransform": ("resource", "dyn ITransform", ["crate::media::ITransform"], "as_transform"),
    "Avalonia.Media.IBrush": ("resource", "dyn IBrush", ["crate::media::IBrush"], "as_brush"),
}

# Schema types without a Rust counterpart yet, with the reason. Properties of
# these types are skipped; remove the entry (and add the type to TYPES) once
# the type is ported, then regenerate.
UNPORTED_TYPES = {}

# The DefaultValue expressions of the schema, by (schema type, expression).
DEFAULTS = {
    ("bool", "true"): "true",
    ("bool", "false"): "false",
    ("float", "1"): "1.0",
    ("double", "1"): "1.0",
    ("double", "1.0"): "1.0",
    ("Quaternion", "Quaternion.Identity"): "Quaternion::IDENTITY",
    ("Vector3D", "new Avalonia.Vector3D(1, 1, 1)"): "Vector3D::new(1.0, 1.0, 1.0)",
    ("Avalonia.Matrix", "Avalonia.Matrix.Identity"): "Matrix::IDENTITY",
    ("Avalonia.RelativeScalar", "RelativeScalar.Middle"): "RelativeScalar::MIDDLE",
}

# The property types whose value has an expression variant form
# (Generator.VariantPropertyTypes; matched on the schema spelling of the
# type, like upstream).
VARIANT_PROPERTY_TYPES = {
    "bool",
    "float",
    "double",
    "Vector2",
    "Vector3",
    "Vector4",
    "Matrix",
    "Matrix3x2",
    "Matrix4x4",
    "Quaternion",
    "Color",
    "Avalonia.Media.Color",
    "Avalonia.RelativePoint",
    "Avalonia.RelativeScalar",
    "Vector",
    "Vector3D",
}

# Server base classes that are not generated: whether they (transitively)
# derive from ServerObject, i.e. support animated properties. The first three
# are the framework roots; the others are hand-written classes that sit
# between a generated class and its generated or framework base.
SERVER_BASES = {
    "ServerObject": True,
    "ServerRenderResource": True,
    "SimpleServerRenderResource": False,
    "ServerSizeDependantVisual": True,
    "ServerCompositionDrawListVisual": True,
    "ServerCompositionGradientBrush": True,
    "ServerCompositionSimpleGradientBrush": False,
}
SERVER_ROOTS = {"ServerObject", "ServerRenderResource", "SimpleServerRenderResource"}

# The Rust types of the key frame animations and their interpolators
# (Generator.KeyFrameAnimation.cs uses the schema type and
# `{name}Interpolator`).
ANIMATION_TYPES = {
    "float": ("f32", None),
    "double": ("f64", None),
    "bool": ("bool", None),
    "Avalonia.Media.Color": ("Color", "crate::media::Color"),
    "Vector": ("Vector", "crate::Vector"),
    "Vector2": ("Vector2", "crate::numerics::Vector2"),
    "Vector3": ("Vector3", "crate::numerics::Vector3"),
    "Vector3D": ("Vector3D", "crate::Vector3D"),
    "Vector4": ("Vector4", "crate::numerics::Vector4"),
    "Quaternion": ("Quaternion", "crate::numerics::Quaternion"),
    "Avalonia.RelativePoint": ("RelativePoint", "crate::RelativePoint"),
    "Avalonia.RelativeScalar": ("RelativeScalar", "crate::RelativeScalar"),
}

COMPOSITION = "crate::rendering::composition"


class TypeInfo:
    """GeneratorTypeInfo (Generator.ConfigHelpers.cs), in Rust terms."""

    def __init__(self, gen, type_name):
        filtered = type_name.rstrip("?")
        self.schema_type = type_name
        self.filtered_type_name = filtered
        self.is_nullable = type_name.endswith("?")
        self.is_object = filtered in gen.objects
        manual = gen.manuals.get(filtered)
        self.is_passthrough = manual is not None and manual.passthrough
        self.imports = []
        self.server_imports = []
        self.cast = None
        if self.is_object and not self.is_passthrough:
            self.kind = "object"
            self.client_type = "Option<Rc<dyn ICompositionObject>>"
            self.server_type = "Option<Rc<dyn IServerObject>>"
            self.imports = ["std::rc::Rc", COMPOSITION + "::ICompositionObject"]
            self.server_imports = ["std::rc::Rc", COMPOSITION + "::server::IServerObject"]
            return
        if filtered not in TYPES:
            raise SystemExit("schema type %r is not in the TYPES table of the generator" % filtered)
        entry = TYPES[filtered]
        self.kind = entry[0]
        self.imports = list(entry[2])
        self.server_imports = list(entry[2])
        if self.kind in ("value", "boxed"):
            self.client_type = self.server_type = entry[1]
        elif self.kind == "payload":
            self.client_type = self.server_type = "Option<%s>" % entry[1]
        elif self.kind == "resource":
            self.cast = entry[3]
            self.client_type = "Option<BatchResource<%s>>" % entry[1]
            self.server_type = "Option<ServerResourceRef<%s>>" % entry[1]
            self.imports.append(COMPOSITION + "::transport::BatchResource")
            self.server_imports.append(COMPOSITION + "::server::ServerResourceRef")
        else:
            raise SystemExit("unknown kind %r" % self.kind)

    @property
    def is_copy(self):
        return self.kind in ("value", "boxed")


# --------------------------------------------------------------------------
# Output helpers (Generator.Utils.cs)
# --------------------------------------------------------------------------


class Unit:
    """One generated file: collects imports while code is emitted."""

    def __init__(self):
        self.imports = set()
        self.lines = []

    def use(self, *paths):
        for path in paths:
            self.imports.add(path)

    def emit(self, text=""):
        self.lines.extend(text.split("\n"))

    def render(self, doc):
        out = [HEADER.rstrip("\n")]
        out.append("")
        out.extend("//! " + line if line else "//!" for line in doc)
        out.append("")
        for path in sorted(self.imports):
            out.append("use %s;" % path)
        if self.imports:
            out.append("")
        body = self.lines
        while body and body[-1] == "":
            body = body[:-1]
        out.extend(body)
        return "\n".join(line.rstrip() for line in out) + "\n"


# --------------------------------------------------------------------------
# Generator (Generator.cs)
# --------------------------------------------------------------------------


class Generator:
    def __init__(self, config):
        self.config = config
        self.manuals = {m.name: m for m in config.manual_classes}
        self.objects = set(m.name for m in config.manual_classes) | set(c.name for c in config.classes)
        self.brushes = set(c.name for c in config.classes if hasattr(c, "custom_update")) | {"CompositionBrush"}
        self.classes = {c.name: c for c in config.classes}
        self.type_info_cache = {}
        self.files = {}
        self.skipped = []

    def get_type_info(self, type_name):
        if type_name not in self.type_info_cache:
            self.type_info_cache[type_name] = TypeInfo(self, type_name)
        return self.type_info_cache[type_name]

    # ---- class graph ----------------------------------------------------

    def props_of(self, cl):
        """The properties of a class that are generated."""
        return [p for p in cl.properties if p.type.rstrip("?") not in UNPORTED_TYPES]

    def client_base(self, cl):
        """(kind, name): 'none', 'generated' (embedded) or 'manual'."""
        if cl.inherits is None:
            return ("none", None)
        base = self.classes.get(cl.inherits)
        if base is not None and not base.server_only:
            return ("generated", base)
        return ("manual", cl.inherits)

    def server_base(self, cl):
        """(kind, value): 'root', 'list', 'generated' (embedded) or 'manual'."""
        if cl.is_list:
            return ("list", server_name(cl.item_type))
        name = cl.server_base or server_name(cl.inherits)
        if name in SERVER_ROOTS:
            return ("root", name)
        if name.startswith("Server") and name[len("Server"):] in self.classes:
            return ("generated", self.classes[name[len("Server"):]])
        if name not in SERVER_BASES:
            raise SystemExit("server base %r of %s is not in the SERVER_BASES table" % (name, cl.name))
        return ("manual", name)

    def server_is_animated(self, cl):
        """Whether the server class derives from ServerObject."""
        kind, value = self.server_base(cl)
        if kind == "list":
            return True
        if kind == "generated":
            return self.server_is_animated(value)
        return SERVER_BASES[value]

    def has_start_animation(self, cl):
        if any(p.animated for p in self.props_of(cl)):
            return True
        kind, base = self.client_base(cl)
        return kind == "generated" and self.has_start_animation(base)

    def variant_props(self, cl):
        return [p for p in self.props_of(cl) if p.type in VARIANT_PROPERTY_TYPES]

    def has_get_composition_property(self, cl):
        if cl.server_only:
            return False
        if self.variant_props(cl):
            return True
        kind, base = self.server_base(cl)
        return kind == "generated" and self.has_get_composition_property(base)

    # ---- entry point ----------------------------------------------------

    def generate(self):
        for cl in self.config.classes:
            self.generate_class(cl)
        self.generate_animations()
        self.generate_mod()
        return self.files

    # ---- changed fields enum --------------------------------------------

    def generate_changed_fields_enum(self, unit, cl):
        name = changed_fields_type_name(cl)
        values = []
        for prop in cl.properties:
            values.append(prop.name)
            if prop.animated:
                values.append(prop.name + "Animated")
        count = len(values)
        base_type = "u8" if count <= 8 else "u16" if count <= 16 else "u32" if count <= 32 else "u64"
        unit.use("bitflags::bitflags", COMPOSITION + "::transport::BatchValue", COMPOSITION + "::transport::BatchValueReader")
        unit.emit("bitflags! {")
        unit.emit("    /// The fields of `%s` that changed since its last serialization." % cl.name)
        unit.emit("    #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]")
        unit.emit("    pub struct %s: %s {" % (name, base_type))
        for index, value in enumerate(values):
            unit.emit("        const %s = %d;" % (screaming(value), 1 << index))
        unit.emit("    }")
        unit.emit("}")
        unit.emit()
        unit.emit("impl BatchValue for %s {" % name)
        unit.emit("    #[inline]")
        unit.emit("    fn write_to(&self, out: &mut Vec<u8>) {")
        unit.emit("        self.bits().write_to(out);")
        unit.emit("    }")
        unit.emit()
        unit.emit("    #[inline]")
        unit.emit("    fn read_from(input: &mut BatchValueReader<'_>) -> Self {")
        unit.emit("        %s::from_bits_retain(%s::read_from(input))" % (name, base_type))
        unit.emit("    }")
        unit.emit("}")
        unit.emit()

    # ---- field access snippets ------------------------------------------

    @staticmethod
    def field_decl(info, type_name):
        return ("Cell<%s>" if info.is_copy else "RefCell<%s>") % type_name

    @staticmethod
    def field_get(info, field):
        return ("self.%s.get()" if info.is_copy else "self.%s.borrow().clone()") % field

    @staticmethod
    def field_set(info, field, value):
        if info.is_copy:
            return "self.%s.set(%s);" % (field, value)
        return "*self.%s.borrow_mut() = %s;" % (field, value)

    @staticmethod
    def field_init(info):
        return "Cell::new(Default::default())" if info.is_copy else "RefCell::new(None)"

    def default_value(self, prop):
        key = (prop.type.rstrip("?"), prop.default_value)
        if key not in DEFAULTS:
            raise SystemExit("default value %r of type %r is not in the DEFAULTS table" % (prop.default_value, prop.type))
        return DEFAULTS[key]

    # ---- class ----------------------------------------------------------

    def generate_class(self, cl):
        unit = Unit()
        props = self.props_of(cl)
        skipped = [p for p in cl.properties if p.type.rstrip("?") in UNPORTED_TYPES]
        for prop in skipped:
            self.skipped.append((cl.name, prop.name, prop.type, UNPORTED_TYPES[prop.type.rstrip("?")]))

        if cl.properties:
            self.generate_changed_fields_enum(unit, cl)
        if not cl.server_only:
            if cl.is_list:
                self.generate_client_list(unit, cl)
            else:
                self.generate_client(unit, cl, props)
        self.generate_server(unit, cl, props)

        doc = ["`%s`%s." % (cl.name, " (server only)" if cl.server_only else "")]
        notes = []
        if cl.abstract:
            notes.append("abstract")
        if cl.internal:
            notes.append("internal")
        if cl.custom_ctor:
            notes.append("custom constructor on the UI thread")
        if cl.custom_server_ctor:
            notes.append("custom constructor on the server")
        if cl.changes_base:
            notes.append("changes base `%s`" % cl.changes_base)
        if notes:
            doc += ["", "Schema attributes: " + ", ".join(notes) + "."]
        for impl in cl.implements:
            doc += ["", "Implements `%s`%s." % (impl.name, (" (server: `%s`)" % impl.server_name) if impl.server_name else "")]
        for prop in skipped:
            doc += ["", "Skipped property `%s`: %s." % (prop.name, UNPORTED_TYPES[prop.type.rstrip("?")])]
        self.files[snake(cl.name) + ".rs"] = unit.render(doc)

    # ---- client ---------------------------------------------------------

    def client_property_ref(self, unit, cl, prop):
        """ClientProperty(cl, p): the composition property of the server class."""
        return "%sProps::id_of_%s_property().base()" % (server_name(cl.name), snake(prop.name))

    def generate_client(self, unit, cl, props):
        name = cl.name
        hooks = name + "Hooks"
        struct = name + "Props"
        changed_type = changed_fields_type_name(cl)
        changed_field = changed_fields_field_name(cl)
        base_kind, base = self.client_base(cl)
        has_changed = bool(cl.properties)
        animated = [p for p in props if p.animated]

        unit.use(COMPOSITION + "::transport::BatchStreamWriter")

        # --- hooks trait
        if base_kind == "generated":
            supertrait = base.name + "Hooks"
            unit.use("super::%sHooks" % base.name, "super::%sProps" % base.name)
        else:
            supertrait = "ICompositionObjectHost"
            unit.use(COMPOSITION + "::ICompositionObjectHost")
        unit.emit("/// The partial methods of `%s`: implemented by the class that embeds" % name)
        unit.emit("/// [`%s`]. Every hook defaults to doing nothing." % struct)
        unit.emit("pub trait %s: %s {" % (hooks, supertrait))
        if base_kind == "manual":
            unit.emit("    /// `base.SerializeChangesCore(writer)`: serializes the changes of the")
            unit.emit("    /// hand-written base class `%s`." % base)
            unit.emit("    fn base_serialize_changes_core(&self, writer: &mut BatchStreamWriter<'_>);")
            unit.emit()
        unit.emit("    fn initialize_defaults_extra(&self) {}")
        for prop in props:
            info = self.get_type_info(prop.type)
            unit.use(*info.imports)
            pname = snake(prop.name)
            arg = info.client_type if info.is_copy else "&" + info.client_type
            unit.emit()
            unit.emit("    fn validate_%s_change(&self, _old_value: %s, _new_value: %s) {}" % (pname, arg, arg))
            unit.emit("    fn on_%s_changed(&self) {}" % pname)
            unit.emit("    fn on_%s_changing(&self) {}" % pname)
        unit.emit("}")
        unit.emit()

        # --- struct
        unit.emit("/// The UI-thread properties of `%s`." % name)
        unit.emit("pub struct %s {" % struct)
        if base_kind == "generated":
            unit.emit("    base: %sProps," % base.name)
        if has_changed:
            unit.use("std::cell::Cell")
            unit.emit("    %s: Cell<%s>," % (changed_field, changed_type))
        for prop in props:
            info = self.get_type_info(prop.type)
            unit.use("std::cell::Cell" if info.is_copy else "std::cell::RefCell")
            unit.emit("    %s: %s," % (snake(prop.name), self.field_decl(info, info.client_type)))
        unit.emit("}")
        unit.emit()
        unit.emit("impl Default for %s {" % struct)
        unit.emit("    fn default() -> Self {")
        unit.emit("        Self::new()")
        unit.emit("    }")
        unit.emit("}")
        unit.emit()

        unit.emit("impl %s {" % struct)
        unit.emit("    /// Creates the properties with every field at the default of its type.")
        unit.emit("    /// The defaults of the schema are applied by")
        unit.emit("    /// [`initialize_defaults`](Self::initialize_defaults).")
        unit.emit("    pub fn new() -> Self {")
        unit.emit("        Self {")
        if base_kind == "generated":
            unit.emit("            base: %sProps::new()," % base.name)
        if has_changed:
            unit.emit("            %s: Cell::new(%s::empty())," % (changed_field, changed_type))
        for prop in props:
            unit.emit("            %s: %s," % (snake(prop.name), self.field_init(self.get_type_info(prop.type))))
        unit.emit("        }")
        unit.emit("    }")
        unit.emit()
        if base_kind == "generated":
            unit.emit("    /// The properties of the base class.")
            unit.emit("    pub fn base(&self) -> &%sProps {" % base.name)
            unit.emit("        &self.base")
            unit.emit("    }")
            unit.emit()

        # InitializeDefaults
        unit.emit("    /// The `InitializeDefaults` calls of the constructor chain: the base")
        unit.emit("    /// classes first, then this class.")
        unit.emit("    pub fn initialize_defaults(&self, host: &dyn %s) {" % hooks)
        if base_kind == "generated":
            unit.emit("        self.base.initialize_defaults(host);")
        unit.emit("        self.initialize_own_defaults(host);")
        unit.emit("    }")
        unit.emit()
        unit.emit("    /// `InitializeDefaults` of this class alone.")
        unit.emit("    pub fn initialize_own_defaults(&self, host: &dyn %s) {" % hooks)
        unit.emit("        %s::initialize_defaults_extra(host);" % hooks)
        for prop in props:
            if prop.default_value is not None:
                unit.emit("        self.set_%s(host, %s);" % (snake(prop.client_name or prop.name), self.default_value(prop)))
        unit.emit("    }")

        for prop in props:
            self.generate_client_property(unit, cl, prop)

        # StartAnimation
        if self.has_start_animation(cl):
            unit.use(
                COMPOSITION + "::animations::ICompositionAnimation",
                COMPOSITION + "::expressions::ExpressionVariant",
            )
            unit.emit()
            unit.emit("    /// Connects an animation with the named property. Returns `false` when")
            unit.emit("    /// neither this class nor its generated bases have an animated property")
            unit.emit("    /// of that name: the caller continues with its hand-written base.")
            unit.emit("    pub fn start_animation(")
            unit.emit("        &self,")
            unit.emit("        host: &dyn %s," % hooks)
            unit.emit("        property_name: &str,")
            unit.emit("        animation: &dyn ICompositionAnimation,")
            unit.emit("        final_value: Option<ExpressionVariant>,")
            unit.emit("    ) -> bool {")
            for prop in animated:
                unit.emit('        if property_name == "%s" {' % prop.name)
                unit.emit("            let server = animation.create_instance(host.server(), final_value);")
                unit.emit("            host.pending_animations().set(%s, server);" % self.client_property_ref(unit, cl, prop))
                unit.emit(
                    "            self.%s.set(self.%s.get() | %s::%s_ANIMATED);"
                    % (changed_field, changed_field, changed_type, screaming(prop.name))
                )
                unit.emit("            host.register_for_serialization();")
                unit.emit("            return true;")
                unit.emit("        }")
            if base_kind == "generated" and self.has_start_animation(base):
                unit.emit("        self.base.start_animation(host, property_name, animation, final_value)")
            else:
                unit.emit("        false")
            unit.emit("    }")

        # SerializeChangesCore
        unit.emit()
        unit.emit("    /// Writes the changes of the object: the base class first, then the")
        unit.emit("    /// changed-fields mask and the changed members of this class.")
        uses_host = base_kind != "none" or bool(animated)
        uses_writer = base_kind != "none" or has_changed
        unit.emit(
            "    pub fn serialize_changes_core(&self, %shost: &dyn %s, %swriter: &mut BatchStreamWriter<'_>) {"
            % ("" if uses_host else "_", hooks, "" if uses_writer else "_")
        )
        if base_kind == "generated":
            unit.emit("        self.base.serialize_changes_core(host, writer);")
        elif base_kind == "manual":
            unit.emit("        %s::base_serialize_changes_core(host, writer);" % hooks)
        if has_changed:
            unit.emit("        let changed = self.%s.get();" % changed_field)
            unit.emit("        writer.write(changed);")
            for prop in props:
                self.apply_serialize_field(unit, cl, prop)
            unit.emit("        self.%s.set(%s::empty());" % (changed_field, changed_type))
        unit.emit("    }")
        unit.emit("}")
        unit.emit()

    def write_expr(self, info, value):
        if info.kind == "value":
            return "writer.write(%s);" % value
        if info.kind == "boxed":
            return "writer.write_value(Some(%s));" % value
        if info.kind == "payload":
            return "writer.write_value(%s);" % value
        if info.kind == "resource":
            return "writer.write_resource(%s);" % value
        return "writer.write_server_object(%s.map(|o| o.server()));" % value

    def apply_serialize_field(self, unit, cl, prop):
        info = self.get_type_info(prop.type)
        changed_type = changed_fields_type_name(cl)
        flag = screaming(prop.name)
        field = snake(prop.name)
        write = self.write_expr(info, self.field_get(info, field))
        if prop.animated:
            unit.emit("        if changed.contains(%s::%s_ANIMATED) {" % (changed_type, flag))
            unit.emit(
                "            writer.write_value(host.pending_animations().get_and_remove(%s));"
                % self.client_property_ref(unit, cl, prop)
            )
            unit.emit("        } else if changed.contains(%s::%s) {" % (changed_type, flag))
        else:
            unit.emit("        if changed.contains(%s::%s) {" % (changed_type, flag))
        unit.emit("            " + write)
        unit.emit("        }")

    def generate_client_property(self, unit, cl, prop):
        info = self.get_type_info(prop.type)
        hooks = cl.name + "Hooks"
        changed_type = changed_fields_type_name(cl)
        changed_field = changed_fields_field_name(cl)
        field = snake(prop.name)
        accessor = snake(prop.client_name or prop.name)
        flag = screaming(prop.name)
        notes = []
        if prop.private:
            notes.append("private to the class")
        elif prop.internal:
            notes.append("internal")
        if prop.internal_set:
            notes.append("internal setter")
        if prop.animated:
            notes.append("animated")
        if prop.default_value is not None:
            notes.append("default `%s`" % self.default_value(prop))
        doc = "`%s`" % prop.name + ((" (" + ", ".join(notes) + ")") if notes else "") + "."
        unit.use(COMPOSITION + "::server::ServerPropertyValue")

        unit.emit()
        unit.emit("    /// " + doc)
        unit.emit("    pub fn %s(&self) -> %s {" % (accessor, info.client_type))
        unit.emit("        " + self.field_get(info, field))
        unit.emit("    }")
        unit.emit()
        unit.emit("    /// Sets " + doc)
        unit.emit("    pub fn set_%s(&self, host: &dyn %s, value: %s) {" % (accessor, hooks, info.client_type))
        unit.emit("        let mut changed = false;")
        unit.emit("        let old_value = %s;" % self.field_get(info, field))
        unit.emit("        if old_value.differs(&value) {")
        if info.is_copy:
            unit.emit("            %s::validate_%s_change(host, old_value, value);" % (hooks, field))
        else:
            unit.emit("            %s::validate_%s_change(host, &old_value, &value);" % (hooks, field))
        unit.emit("            %s::on_%s_changing(host);" % (hooks, field))
        unit.emit("            changed = true;")
        unit.emit("            // Update the backing value")
        unit.emit("            " + self.field_set(info, field, "value" if info.is_copy else "value.clone()"))
        unit.emit("            // Register object for serialization in the next batch")
        unit.emit("            self.%s.set(self.%s.get() | %s::%s);" % (changed_field, changed_field, changed_type, flag))
        unit.emit("            host.register_for_serialization();")
        if prop.animated:
            unit.use(COMPOSITION + "::expressions::ExpressionVariant")
            prop_ref = self.client_property_ref(unit, cl, prop)
            unit.emit("            // Reset previous animation if any")
            unit.emit("            host.pending_animations().remove(%s);" % prop_ref)
            unit.emit(
                "            self.%s.set(self.%s.get() & !%s::%s_ANIMATED);" % (changed_field, changed_field, changed_type, flag)
            )
            unit.emit("            // Check for implicit animations")
            unit.emit('            if let Some(animation) = host.implicit_animation("%s") {' % prop.name)
            unit.emit("                // Animation affects only current property")
            unit.emit("                if let Some(a) = animation.as_composition_animation() {")
            unit.emit(
                "                    self.%s.set(self.%s.get() | %s::%s_ANIMATED);"
                % (changed_field, changed_field, changed_type, flag)
            )
            unit.emit("                    host.pending_animations().set(")
            unit.emit("                        %s," % prop_ref)
            unit.emit("                        a.create_instance(host.server(), Some(ExpressionVariant::create(value))),")
            unit.emit("                    );")
            unit.emit("                }")
            unit.emit("                // Animation is triggered by the current field, but does not necessary affects it")
            unit.emit('                host.start_animation_group(&animation, "%s", ExpressionVariant::create(value));' % prop.name)
            unit.emit("            }")
        unit.emit("        }")
        unit.emit("        " + self.field_set(info, field, "value"))
        unit.emit("        if changed {")
        unit.emit("            %s::on_%s_changed(host);" % (hooks, field))
        unit.emit("        }")
        unit.emit("    }")

    # ---- client list (Generator.ListProxy.cs) -----------------------------

    def generate_client_list(self, unit, cl):
        name = cl.name
        hooks = name + "Hooks"
        struct = name + "Props"
        base_kind, base = self.client_base(cl)
        if base_kind != "none" or cl.properties:
            raise SystemExit("list class %s: base classes and properties are not supported" % name)
        unit.use(
            "std::rc::Rc",
            COMPOSITION + "::ICompositionObject",
            COMPOSITION + "::ICompositionObjectHost",
            COMPOSITION + "::transport::BatchStreamWriter",
            COMPOSITION + "::transport::ServerListProxyHelper",
        )
        item = "TItem"
        bound = "<TItem: ICompositionObject + ?Sized>"
        unit.emit("/// The partial methods of `%s`: implemented by the class that embeds" % name)
        unit.emit("/// [`%s`]. `TItem` is the UI-thread class of the items (`%s`)." % (struct, cl.item_type))
        unit.emit("/// Every hook defaults to doing nothing.")
        unit.emit("pub trait %s%s: ICompositionObjectHost {" % (hooks, bound))
        unit.emit("    fn initialize_defaults_extra(&self) {}")
        unit.emit("    fn on_before_added(&self, _item: &Rc<%s>) {}" % item)
        unit.emit("    fn on_added(&self, _item: &Rc<%s>) {}" % item)
        unit.emit("    fn on_removed(&self, _item: &Rc<%s>) {}" % item)
        unit.emit("    fn on_before_clear(&self) {}")
        unit.emit("    fn on_before_replace(&self, _old_item: &Rc<%s>, _new_item: &Rc<%s>) {}" % (item, item))
        unit.emit("    fn on_replace(&self, _old_item: &Rc<%s>, _new_item: &Rc<%s>) {}" % (item, item))
        unit.emit("    fn on_clear(&self) {}")
        unit.emit("}")
        unit.emit()
        unit.emit("/// The UI-thread list of `%s`." % name)
        unit.emit("pub struct %s%s {" % (struct, bound))
        unit.emit("    list: ServerListProxyHelper<%s>," % item)
        unit.emit("}")
        unit.emit()
        unit.emit("impl%s Default for %s<%s> {" % (bound, struct, item))
        unit.emit("    fn default() -> Self {")
        unit.emit("        Self::new()")
        unit.emit("    }")
        unit.emit("}")
        unit.emit()
        h = "host: &dyn %s<%s>" % (hooks, item)
        unit.emit("impl%s %s<%s> {" % (bound, struct, item))
        unit.emit(
            """    pub fn new() -> Self {
        Self { list: ServerListProxyHelper::new() }
    }

    /// The `InitializeDefaults` calls of the constructor chain.
    pub fn initialize_defaults(&self, HOST) {
        self.initialize_own_defaults(host);
    }

    /// `InitializeDefaults` of this class alone.
    pub fn initialize_own_defaults(&self, HOST) {
        HOOKS::initialize_defaults_extra(host);
    }

    /// A snapshot of the items, for enumeration.
    pub fn items(&self) -> Vec<Rc<ITEM>> {
        self.list.items()
    }

    pub fn add(&self, HOST, item: Rc<ITEM>) {
        HOOKS::on_before_added(host, &item);
        self.list.add(host, item.clone());
        HOOKS::on_added(host, &item);
    }

    pub fn clear(&self, HOST) {
        HOOKS::on_before_clear(host);
        self.list.clear(host);
        HOOKS::on_clear(host);
    }

    pub fn contains(&self, item: &Rc<ITEM>) -> bool {
        self.list.contains(item)
    }

    pub fn copy_to(&self, array: &mut [Option<Rc<ITEM>>], array_index: usize) {
        self.list.copy_to(array, array_index)
    }

    pub fn remove(&self, HOST, item: &Rc<ITEM>) -> bool {
        let removed = self.list.remove(host, item);
        if removed {
            HOOKS::on_removed(host, item);
        }
        removed
    }

    pub fn count(&self) -> usize {
        self.list.count()
    }

    pub fn is_read_only(&self) -> bool {
        self.list.is_read_only()
    }

    pub fn index_of(&self, item: &Rc<ITEM>) -> Option<usize> {
        self.list.index_of(item)
    }

    pub fn insert(&self, HOST, index: usize, item: Rc<ITEM>) {
        HOOKS::on_before_added(host, &item);
        self.list.insert(host, index, item.clone());
        HOOKS::on_added(host, &item);
    }

    pub fn remove_at(&self, HOST, index: usize) {
        let item = self.list.get(index);
        self.list.remove_at(host, index);
        HOOKS::on_removed(host, &item);
    }

    pub fn get(&self, index: usize) -> Rc<ITEM> {
        self.list.get(index)
    }

    pub fn set(&self, HOST, index: usize, value: Rc<ITEM>) {
        let old = self.list.get(index);
        HOOKS::on_before_replace(host, &old, &value);
        self.list.set(host, index, value.clone());
        HOOKS::on_replace(host, &old, &value);
    }

    /// Writes the changes of the object: the list, then the base class.
    pub fn serialize_changes_core(&self, _HOST, writer: &mut BatchStreamWriter<'_>) {
        self.list.serialize(writer);
    }
}""".replace("HOST", h)
            .replace("HOOKS", hooks)
            .replace("ITEM", item)
        )
        unit.emit()

    # ---- server ---------------------------------------------------------

    def generate_server(self, unit, cl, props):
        name = server_name(cl.name)
        hooks = name + "Hooks"
        struct = name + "Props"
        changed_type = changed_fields_type_name(cl)
        base_kind, base = self.server_base(cl)
        animated_host = self.server_is_animated(cl)
        has_changed = bool(cl.properties)
        needs_compositor = cl.is_list or any(self.get_type_info(p.type).kind in ("object", "resource") for p in props)

        unit.use(COMPOSITION + "::transport::BatchStreamReader", "std::time::Duration", "std::any::Any", "std::any::TypeId")
        host_trait = "IServerAnimatedPropertyHost" if animated_host else "IServerPropertyHost"

        # --- hooks trait
        if base_kind == "generated":
            supertrait = server_name(base.name) + "Hooks"
            unit.use("super::%sHooks" % server_name(base.name), "super::%sProps" % server_name(base.name))
        else:
            supertrait = host_trait
            unit.use(COMPOSITION + "::server::" + host_trait)
        unit.emit("/// The partial methods of `%s`: implemented by the class that embeds" % name)
        unit.emit("/// [`%s`]. Every hook defaults to doing nothing." % struct)
        unit.emit("pub trait %s: %s {" % (hooks, supertrait))
        lines = []
        if base_kind == "manual":
            lines.append("    /// `base.DeserializeChangesCore(reader, committedAt)`: reads the changes of")
            lines.append("    /// the hand-written base class `%s`." % base)
            lines.append(
                "    fn base_deserialize_changes_core(&self, reader: &mut BatchStreamReader<'_>, committed_at: Duration);"
            )
        if has_changed:
            if lines:
                lines.append("")
            lines.append("    fn deserialize_changes_extra(&self, _reader: &mut BatchStreamReader<'_>) {}")
            lines.append("    fn on_fields_deserialized(&self, _changed: %s) {}" % changed_type)
        for prop in props:
            if not prop.animated:
                lines.append("")
                lines.append("    fn on_%s_changed(&self) {}" % snake(prop.name))
                lines.append("    fn on_%s_changing(&self) {}" % snake(prop.name))
        for line in lines:
            unit.emit(line)
        unit.emit("}")
        unit.emit()

        # --- struct
        unit.emit("/// The server-side properties of `%s`." % name)
        unit.emit("pub struct %s {" % struct)
        if base_kind == "generated":
            unit.emit("    base: %sProps," % server_name(base.name))
        if cl.is_list:
            unit.use(COMPOSITION + "::server::ServerList")
            unit.emit("    list: ServerList,")
        for prop in props:
            info = self.get_type_info(prop.type)
            unit.use(*info.server_imports)
            unit.use("std::cell::Cell" if info.is_copy else "std::cell::RefCell")
            unit.emit("    %s: %s," % (snake(prop.name), self.field_decl(info, info.server_type)))
        unit.emit("}")
        unit.emit()
        unit.emit("impl Default for %s {" % struct)
        unit.emit("    fn default() -> Self {")
        unit.emit("        Self::new()")
        unit.emit("    }")
        unit.emit("}")
        unit.emit()

        unit.emit("impl %s {" % struct)
        unit.emit("    /// Creates the properties with every field at the default of its type; the")
        unit.emit("    /// values of the UI thread arrive with the first batch.")
        unit.emit("    pub fn new() -> Self {")
        unit.emit("        Self {")
        if base_kind == "generated":
            unit.emit("            base: %sProps::new()," % server_name(base.name))
        if cl.is_list:
            unit.emit("            list: ServerList::new(),")
        for prop in props:
            unit.emit("            %s: %s," % (snake(prop.name), self.field_init(self.get_type_info(prop.type))))
        unit.emit("        }")
        unit.emit("    }")
        unit.emit()
        if base_kind == "generated":
            unit.emit("    /// The properties of the base class.")
            unit.emit("    pub fn base(&self) -> &%sProps {" % server_name(base.name))
            unit.emit("        &self.base")
            unit.emit("    }")
            unit.emit()
        if cl.is_list:
            unit.emit("    /// The items: server objects of class `%s`." % server_name(cl.item_type))
            unit.emit("    pub fn list(&self) -> &ServerList {")
            unit.emit("        &self.list")
            unit.emit("    }")
            unit.emit()
        unit.emit("    /// This block or the block of a base class, by type: what")
        unit.emit("    /// `IServerObject::get_props` of the embedding class returns.")
        unit.emit("    pub fn find_props(&self, type_id: TypeId) -> Option<&dyn Any> {")
        unit.emit("        if type_id == TypeId::of::<Self>() {")
        unit.emit("            return Some(self);")
        unit.emit("        }")
        if base_kind == "generated":
            unit.emit("        self.base.find_props(type_id)")
        else:
            unit.emit("        None")
        unit.emit("    }")

        for prop in props:
            self.generate_server_property(unit, cl, prop, animated_host)

        # DeserializeChangesCore
        unit.emit()
        unit.emit("    /// Reads the changes of the object: the base class first, then the")
        unit.emit("    /// changed-fields mask and the changed members of this class.")
        uses_host = base_kind in ("generated", "manual") or has_changed or cl.is_list
        uses_reader = uses_host
        uses_time = base_kind in ("generated", "manual") or any(p.animated for p in props)
        unit.emit("    pub fn deserialize_changes_core(")
        unit.emit("        &self,")
        unit.emit("        %shost: &dyn %s," % ("" if uses_host else "_", hooks))
        unit.emit("        %sreader: &mut BatchStreamReader<'_>," % ("" if uses_reader else "_"))
        unit.emit("        %scommitted_at: Duration," % ("" if uses_time else "_"))
        unit.emit("    ) {")
        if needs_compositor:
            unit.emit("        let compositor = host.server_compositor();")
        if cl.is_list:
            unit.emit("        self.list.deserialize_changes_core(reader, compositor.as_ref());")
        if base_kind == "generated":
            unit.emit("        self.base.deserialize_changes_core(host, reader, committed_at);")
        elif base_kind == "manual":
            unit.emit("        %s::base_deserialize_changes_core(host, reader, committed_at);" % hooks)
        if has_changed:
            unit.emit("        %s::deserialize_changes_extra(host, reader);" % hooks)
            unit.emit("        let changed = reader.read::<%s>();" % changed_type)
            for prop in props:
                self.apply_deserialize_field(unit, cl, prop)
            unit.emit("        %s::on_fields_deserialized(host, changed);" % hooks)
        unit.emit("    }")

        # GetCompositionProperty
        if self.has_get_composition_property(cl):
            unit.use(COMPOSITION + "::server::CompositionProperty")
            unit.emit()
            unit.emit("    /// The composition property with the given name, among the properties")
            unit.emit("    /// of this class and of its generated bases that have a variant form.")
            unit.emit("    pub fn get_composition_property(name: &str) -> Option<&'static CompositionProperty> {")
            for prop in self.variant_props(cl):
                unit.emit('        if name == "%s" {' % prop.name)
                unit.emit("            return Some(Self::id_of_%s_property().base());" % snake(prop.name))
                unit.emit("        }")
            if base_kind == "generated" and self.has_get_composition_property(base):
                unit.emit("        %sProps::get_composition_property(name)" % server_name(base.name))
            else:
                unit.emit("        None")
            unit.emit("    }")

        # SerializeAllChanges
        if cl.server_only:
            self.generate_serialize_all_method(unit, cl, props)

        unit.emit("}")
        unit.emit()

    def generate_serialize_all_method(self, unit, cl, props):
        unit.use(COMPOSITION + "::transport::BatchStreamWriter")
        changed_type = changed_fields_type_name(cl)
        params = ["writer: &mut BatchStreamWriter<'_>"]
        for prop in props:
            info = self.get_type_info(prop.type)
            unit.use(*info.imports)
            params.append("%s: %s" % (snake(prop.name), info.client_type))
        unit.emit()
        unit.emit("    /// Writes every property of the class, in the form")
        unit.emit("    /// [`deserialize_changes_core`](Self::deserialize_changes_core) reads.")
        if len(params) > 7:
            unit.emit("    #[allow(clippy::too_many_arguments)]")
        unit.emit("    pub fn serialize_all_changes(")
        for param in params:
            unit.emit("        %s," % param)
        unit.emit("    ) {")
        if cl.properties:
            bits = " | ".join("%s::%s" % (changed_type, screaming(p.name)) for p in props)
            unit.emit("        writer.write(%s);" % (bits or "%s::empty()" % changed_type))
        for prop in props:
            info = self.get_type_info(prop.type)
            unit.emit("        " + self.write_expr(info, snake(prop.name)))
        unit.emit("    }")

    def read_expr(self, info):
        if info.kind == "value":
            return "reader.read::<%s>()" % info.server_type
        if info.kind == "boxed":
            return (
                "match reader.read_value::<%s>() {\n"
                "                Some(value) => value,\n"
                '                None => panic!("a batch holds no value for a property that is not nullable"),\n'
                "            }" % info.server_type
            )
        if info.kind == "payload":
            return "reader.read_value::<%s>()" % info.server_type[len("Option<"):-1]
        if info.kind == "resource":
            return "read_resource(reader, compositor.as_ref(), |o| o.%s())" % info.cast
        return "read_server_object(reader, compositor.as_ref())"

    def apply_deserialize_field(self, unit, cl, prop):
        info = self.get_type_info(prop.type)
        changed_type = changed_fields_type_name(cl)
        flag = screaming(prop.name)
        field = snake(prop.name)
        if info.kind == "resource":
            unit.use(COMPOSITION + "::server::read_resource")
        elif info.kind == "object":
            unit.use(COMPOSITION + "::server::read_server_object")
        if prop.animated:
            unit.use(
                COMPOSITION + "::animations::AnimationInstanceFactory",
                COMPOSITION + "::expressions::ExpressionVariant",
            )
            unit.emit("        if changed.contains(%s::%s_ANIMATED) {" % (changed_type, flag))
            # What a batch carries is the factory of the instance; the instance
            # is created here, on the thread that runs it.
            unit.emit("            let Some(animation) = reader.read_value::<AnimationInstanceFactory>().map(AnimationInstanceFactory::create) else {")
            unit.emit('                panic!("a batch starts an animation of `%s` without an animation instance");' % prop.name)
            unit.emit("            };")
            unit.emit("            host.set_animated_value(")
            unit.emit("                Self::id_of_%s_property().base()," % field)
            unit.emit("                ExpressionVariant::create(%s)," % self.field_get(info, field))
            unit.emit("                committed_at,")
            unit.emit("                animation,")
            unit.emit("            );")
            unit.emit("        } else if changed.contains(%s::%s) {" % (changed_type, flag))
        else:
            unit.emit("        if changed.contains(%s::%s) {" % (changed_type, flag))
        unit.emit("            let value = %s;" % self.read_expr(info))
        unit.emit("            self.set_%s(host, value);" % field)
        unit.emit("        }")

    def generate_server_property(self, unit, cl, prop, animated_host):
        info = self.get_type_info(prop.type)
        name = server_name(cl.name)
        hooks = name + "Hooks"
        struct = name + "Props"
        field = snake(prop.name)
        is_variant = prop.type in VARIANT_PROPERTY_TYPES
        if prop.animated and not animated_host:
            raise SystemExit("%s.%s is animated but %s does not derive from ServerObject" % (cl.name, prop.name, name))
        unit.use(
            "std::sync::OnceLock",
            COMPOSITION + "::server::CompositionProperty",
            COMPOSITION + "::server::CompositionPropertyOf",
            COMPOSITION + "::server::props_of",
        )

        # static CompositionProperty registration
        unit.emit()
        unit.emit("    /// The composition property of `%s`." % prop.name)
        unit.emit("    pub fn id_of_%s_property() -> &'static CompositionPropertyOf<%s> {" % (field, info.server_type))
        unit.emit("        static PROPERTY: OnceLock<CompositionPropertyOf<%s>> = OnceLock::new();" % info.server_type)
        unit.emit("        PROPERTY.get_or_init(|| {")
        unit.emit("            CompositionProperty::register::<%s, %s>(" % (struct, info.server_type))
        unit.emit('                "%s",' % prop.name)
        unit.emit('                "%s",' % name)
        getter = ("props_of::<%s>(obj).%s.get()" if info.is_copy else "props_of::<%s>(obj).%s.borrow().clone()") % (struct, field)
        if info.is_copy:
            setter = "props_of::<%s>(obj).%s.set(v)" % (struct, field)
        else:
            setter = "*props_of::<%s>(obj).%s.borrow_mut() = v" % (struct, field)
        unit.emit("                |obj| %s," % getter)
        unit.emit("                |obj, v| %s," % setter)
        if is_variant:
            unit.use(COMPOSITION + "::expressions::ExpressionVariant")
            unit.emit("                Some(|obj| ExpressionVariant::create(%s))," % getter)
        else:
            unit.emit("                None,")
        if prop.animated:
            unit.use(COMPOSITION + "::expressions::ExpressionVariant")
            unit.emit(
                "                Some(|obj, v: ExpressionVariant| props_of::<%s>(obj).%s.set(v.cast_or_default::<%s>())),"
                % (struct, field, info.server_type)
            )
        else:
            unit.emit("                None,")
        unit.emit("            )")
        unit.emit("        })")
        unit.emit("    }")

        unit.emit()
        unit.emit("    /// `%s`%s." % (prop.name, " (animated)" if prop.animated else ""))
        unit.emit("    pub fn %s(&self) -> %s {" % (field, info.server_type))
        unit.emit("        " + self.field_get(info, field))
        unit.emit("    }")
        unit.emit()
        unit.emit("    pub fn set_%s(&self, host: &dyn %s, value: %s) {" % (field, hooks, info.server_type))
        if prop.animated:
            unit.emit("        " + self.field_set(info, field, "value"))
            unit.emit("        host.remove_animation_for_property(Self::id_of_%s_property().base());" % field)
        else:
            unit.use(COMPOSITION + "::server::ServerPropertyValue", COMPOSITION + "::server::ServerValueChange")
            resource = info.kind in ("object", "resource")
            if resource:
                unit.use(COMPOSITION + "::server::AsServerRenderResource")
            unit.emit("        let old_value = %s;" % self.field_get(info, field))
            unit.emit("        let mut changed = false;")
            unit.emit("        if old_value.differs(&value) {")
            unit.emit("            %s::on_%s_changing(host);" % (hooks, field))
            unit.emit("            changed = true;")
            unit.emit("        }")
            unit.emit("        host.set_value(")
            unit.emit("            Self::id_of_%s_property().base()," % field)
            unit.emit("            ServerValueChange {")
            unit.emit("                equal: old_value.default_equals(&value),")
            unit.emit("                old_resource: %s," % ("old_value.as_server_render_resource()" if resource else "None"))
            unit.emit("                new_resource: %s," % ("value.as_server_render_resource()" if resource else "None"))
            unit.emit("                assign: &mut || %s," % self.field_set(info, field, "value" if info.is_copy else "value.clone()")[:-1])
            unit.emit("            },")
            unit.emit("        );")
            unit.emit("        if changed {")
            unit.emit("            %s::on_%s_changed(host);" % (hooks, field))
            unit.emit("        }")
        unit.emit("    }")

    # ---- key frame animations (Generator.KeyFrameAnimation.cs) ------------

    def generate_animations(self):
        unit = Unit()
        entries = []
        for a in self.config.key_frame_animations:
            name = a.name or a.type
            if a.type not in ANIMATION_TYPES:
                raise SystemExit("animation type %r is not in the ANIMATION_TYPES table" % a.type)
            rust_type, path = ANIMATION_TYPES[a.type]
            entries.append((name, rust_type, path))
        unit.emit("/// Calls `$callback!` with the key frame animation classes of the schema, one")
        unit.emit("/// parenthesised entry per class:")
        unit.emit("///")
        unit.emit("/// ```text")
        unit.emit("/// (class name, compositor factory method, value type, interpolator)")
        unit.emit("/// ```")
        unit.emit("///")
        unit.emit("/// The class of an entry is what upstream generates as")
        unit.emit("/// `{Name}KeyFrameAnimation : KeyFrameAnimation` together with")
        unit.emit("/// `Compositor.Create{Name}KeyFrameAnimation()`: a `KeyFrames<T>` list, the two")
        unit.emit("/// `InsertKeyFrame` overloads and a `CreateInstance` that builds a")
        unit.emit("/// `KeyFrameAnimationInstance<T>` with `{Name}Interpolator`. The callback, written")
        unit.emit("/// next to the key frame animation base class, expands each entry into that")
        unit.emit("/// class.")
        unit.emit("#[macro_export]")
        unit.emit("#[doc(hidden)]")
        unit.emit("macro_rules! __for_each_composition_key_frame_animation {")
        unit.emit("    ($callback:ident) => {")
        unit.emit("        $callback! {")
        for name, rust_type, path in entries:
            full = path if path else rust_type
            full = ("$" + full) if full.startswith("crate::") else full
            unit.emit(
                "            (%sKeyFrameAnimation, create_%s_key_frame_animation, %s, $crate::rendering::composition::animations::%sInterpolator),"
                % (name, snake(name), full, name)
            )
        unit.emit("        }")
        unit.emit("    };")
        unit.emit("}")
        unit.emit()
        unit.emit("pub use crate::__for_each_composition_key_frame_animation as for_each_composition_key_frame_animation;")
        unit.emit()
        unit.emit("/// The key frame animations of the schema: (name, schema type).")
        unit.emit("pub const KEY_FRAME_ANIMATIONS: &[(&str, &str)] = &[")
        for a in self.config.key_frame_animations:
            unit.emit('    ("%s", "%s"),' % (a.name or a.type, a.type.split(".")[-1]))
        unit.emit("];")
        self.files["composition_animations.rs"] = unit.render(["The key frame animation classes of the schema."])

    # ---- mod.rs -----------------------------------------------------------

    def generate_mod(self):
        doc = MOD_DOC.strip("\n").split("\n")
        if self.skipped:
            doc += ["", "# Skipped properties", ""]
            for cl, prop, type_name, reason in self.skipped:
                doc.append("* `%s.%s`: %s." % (cl, prop, reason))
        manual = [m.name for m in self.config.manual_classes if not m.passthrough]
        doc += ["", "# Classes of the schema that are not generated", ""]
        doc.append("Manual classes (written by hand): " + ", ".join("`%s`" % m for m in manual) + ".")
        out = [HEADER.rstrip("\n"), ""]
        out.extend("//! " + line if line else "//!" for line in doc)
        out.append("")
        names = sorted(n[:-3] for n in self.files)
        for name in names:
            out.append("mod %s;" % name)
        out.append("")
        for name in names:
            out.append("pub use %s::*;" % name)
        out.append("")
        out.append("#[cfg(test)]")
        out.append("mod tests;")
        self.files["mod.rs"] = "\n".join(out) + "\n"


MOD_DOC = """
The composition object model generated from the composition schema.

Upstream generates C# partial classes and completes them by hand in the
other half of each partial class. Here the generated half of a schema class
`X` is a pair of *property blocks* that the hand-written class embeds, and a
pair of *hook traits* through which the block calls back into that class:

| Upstream (generated)                         | Here                                   |
|----------------------------------------------|----------------------------------------|
| `enum XChangedFields`                        | `XChangedFields` (bit flags)           |
| fields, properties, `InitializeDefaults`, `SerializeChangesCore`, `StartAnimation` of `X` | `XProps` |
| `partial void` methods of `X`                | `XHooks` (default: do nothing)         |
| fields, properties, `DeserializeChangesCore`, `GetCompositionProperty`, `SerializeAllChanges` of `ServerX` | `ServerXProps` |
| `partial void` methods of `ServerX`          | `ServerXHooks` (default: do nothing)   |
| `static CompositionProperty<T> s_IdOfPProperty` | `ServerXProps::id_of_p_property()`  |

A `ServerOnly` class has no `XProps`; its UI-thread side is a media class
that calls `ServerXProps::serialize_all_changes`.

# Embedding the UI-thread block

The class holds an `XProps` (created with `XProps::new()`), implements
`ICompositionObjectHost` (registering for serialization, the id of its
server object, pending and implicit animations) and `XHooks`, and

* calls `props.initialize_defaults(self)` where the upstream constructor
  calls `InitializeDefaults()` (use `initialize_own_defaults` when the
  constructor chain is customised);
* exposes the properties by forwarding to `props.p()` /
  `props.set_p(self, value)`; the setter raises the hooks, marks the field
  changed, registers the object and handles implicit animations exactly as
  the upstream setter does;
* forwards `ICompositorSerializable::serialize_changes` to
  `props.serialize_changes_core(self, writer)` and `StartAnimation` to
  `props.start_animation(self, name, animation, final_value)` (a `false`
  result means the property is unknown to the generated classes).

# Embedding the server block

The class holds a `ServerXProps`, implements `IServerPropertyHost` (or
`IServerAnimatedPropertyHost` when it derives from the animatable server
object) and `ServerXHooks`, and

* forwards `IServerObject::deserialize_changes_core` to
  `props.deserialize_changes_core(self, reader, committed_at)`;
* returns `props.find_props(type_id)` from `IServerObject::get_props`, which
  is how composition properties reach the fields of the block;
* exposes the properties by forwarding to `props.p()` /
  `props.set_p(self, value)`.

`IServerPropertyHost::set_value` is upstream's `SetValue(prop, ref field,
value)`: the block hands the class the assignment and the class decides what
surrounds it (nothing, animation subscriptions, or the observer bookkeeping
of a render resource).

# Inheritance

A class whose base class is generated embeds the block of the base
(`props.base()`), its hook trait extends the hook trait of the base, and its
`serialize_changes_core` / `deserialize_changes_core` run the base first, as
`base.SerializeChangesCore` does upstream. A class whose base is written by
hand (a `Manual` class of the schema, or a `ServerBase` that is not
generated) has a required hook instead, `base_serialize_changes_core` /
`base_deserialize_changes_core`, called at the same point.

# Types

Composition objects referenced by a property are held as
`Rc<dyn ICompositionObject>` on the UI thread and cross as the id of their
server object; the server block holds the resolved `Rc<dyn IServerObject>`.
Brushes and transforms are `BatchResource` values on the UI thread (the
value itself or the id of its server-side counterpart) and
`ServerResourceRef` values on the server. Other reference types cross as
payloads; plain values cross through `BatchValue`.

The schema attributes `Internal`, `Private` and `InternalSet` are recorded
in the documentation of the generated items; everything is `pub` so the
hand-written classes, which live in other modules, can reach it.
"""


def main():
    parser = argparse.ArgumentParser(description="Generates the composition object model.")
    parser.add_argument("--schema", default=DEFAULT_SCHEMA)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    files = Generator(GConfig(args.schema)).generate()

    stale = []
    os.makedirs(args.out, exist_ok=True)
    for name in sorted(files):
        path = os.path.join(args.out, name)
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current != files[name]:
            stale.append(name)
            if not args.check:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(files[name])
    for name in sorted(os.listdir(args.out)):
        path = os.path.join(args.out, name)
        if name.endswith(".rs") and name not in files and os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                generated = f.readline() == HEADER
            if generated:
                stale.append(name)
                if not args.check:
                    os.remove(path)
    if args.check:
        if stale:
            print("stale generated files: " + ", ".join(stale))
            return 1
        print("generated files are up to date")
        return 0
    print("generated %d files in %s (%d changed)" % (len(files), os.path.relpath(args.out, ROOT), len(stale)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
