use super::{Key, PhysicalKey};

impl PhysicalKey {
    /// Maps a physical key to a corresponding key, if possible, on a QWERTY
    /// keyboard. Returns [`Key::None`] when there is none.
    pub fn to_qwerty_key(self) -> Key {
        match self {
            PhysicalKey::None => Key::None,
            // Writing System Keys
            PhysicalKey::Backquote => Key::OemTilde,
            PhysicalKey::Backslash => Key::OemPipe,
            PhysicalKey::BracketLeft => Key::OemOpenBrackets,
            PhysicalKey::BracketRight => Key::OemCloseBrackets,
            PhysicalKey::Comma => Key::OemComma,
            PhysicalKey::Digit0 => Key::D0,
            PhysicalKey::Digit1 => Key::D1,
            PhysicalKey::Digit2 => Key::D2,
            PhysicalKey::Digit3 => Key::D3,
            PhysicalKey::Digit4 => Key::D4,
            PhysicalKey::Digit5 => Key::D5,
            PhysicalKey::Digit6 => Key::D6,
            PhysicalKey::Digit7 => Key::D7,
            PhysicalKey::Digit8 => Key::D8,
            PhysicalKey::Digit9 => Key::D9,
            PhysicalKey::Equal => Key::OemPlus,
            PhysicalKey::IntlBackslash => Key::OemBackslash,
            PhysicalKey::IntlRo => Key::OemBackslash,
            PhysicalKey::IntlYen => Key::OemPipe,
            PhysicalKey::A => Key::A,
            PhysicalKey::B => Key::B,
            PhysicalKey::C => Key::C,
            PhysicalKey::D => Key::D,
            PhysicalKey::E => Key::E,
            PhysicalKey::F => Key::F,
            PhysicalKey::G => Key::G,
            PhysicalKey::H => Key::H,
            PhysicalKey::I => Key::I,
            PhysicalKey::J => Key::J,
            PhysicalKey::K => Key::K,
            PhysicalKey::L => Key::L,
            PhysicalKey::M => Key::M,
            PhysicalKey::N => Key::N,
            PhysicalKey::O => Key::O,
            PhysicalKey::P => Key::P,
            PhysicalKey::Q => Key::Q,
            PhysicalKey::R => Key::R,
            PhysicalKey::S => Key::S,
            PhysicalKey::T => Key::T,
            PhysicalKey::U => Key::U,
            PhysicalKey::V => Key::V,
            PhysicalKey::W => Key::W,
            PhysicalKey::X => Key::X,
            PhysicalKey::Y => Key::Y,
            PhysicalKey::Z => Key::Z,
            PhysicalKey::Minus => Key::OemMinus,
            PhysicalKey::Period => Key::OemPeriod,
            PhysicalKey::Quote => Key::OemQuotes,
            PhysicalKey::Semicolon => Key::OemSemicolon,
            PhysicalKey::Slash => Key::OemQuestion,
            // Functional Keys
            PhysicalKey::AltLeft => Key::LeftAlt,
            PhysicalKey::AltRight => Key::RightAlt,
            PhysicalKey::Backspace => Key::Back,
            PhysicalKey::CapsLock => Key::CapsLock,
            PhysicalKey::ContextMenu => Key::Apps,
            PhysicalKey::ControlLeft => Key::LeftCtrl,
            PhysicalKey::ControlRight => Key::RightCtrl,
            PhysicalKey::Enter => Key::Return,
            PhysicalKey::MetaLeft => Key::LWin,
            PhysicalKey::MetaRight => Key::RWin,
            PhysicalKey::ShiftLeft => Key::LeftShift,
            PhysicalKey::ShiftRight => Key::RightShift,
            PhysicalKey::Space => Key::Space,
            PhysicalKey::Tab => Key::Tab,
            PhysicalKey::Convert => Key::ImeConvert,
            PhysicalKey::KanaMode => Key::HangulMode,
            PhysicalKey::Lang1 => Key::HangulMode,
            PhysicalKey::Lang2 => Key::KanjiMode,
            PhysicalKey::Lang3 => Key::OemFinish,
            PhysicalKey::Lang4 => Key::DbeHiragana,
            PhysicalKey::Lang5 => Key::DbeSbcsChar,
            PhysicalKey::NonConvert => Key::ImeNonConvert,
            // Control Pad Section
            PhysicalKey::Delete => Key::Delete,
            PhysicalKey::End => Key::End,
            PhysicalKey::Help => Key::Help,
            PhysicalKey::Home => Key::Home,
            PhysicalKey::Insert => Key::Insert,
            PhysicalKey::PageDown => Key::PageDown,
            PhysicalKey::PageUp => Key::PageUp,
            // Arrow Pad Section
            PhysicalKey::ArrowDown => Key::Down,
            PhysicalKey::ArrowLeft => Key::Left,
            PhysicalKey::ArrowRight => Key::Right,
            PhysicalKey::ArrowUp => Key::Up,
            // Numpad Section
            PhysicalKey::NumLock => Key::NumLock,
            PhysicalKey::NumPad0 => Key::NumPad0,
            PhysicalKey::NumPad1 => Key::NumPad1,
            PhysicalKey::NumPad2 => Key::NumPad2,
            PhysicalKey::NumPad3 => Key::NumPad3,
            PhysicalKey::NumPad4 => Key::NumPad4,
            PhysicalKey::NumPad5 => Key::NumPad5,
            PhysicalKey::NumPad6 => Key::NumPad6,
            PhysicalKey::NumPad7 => Key::NumPad7,
            PhysicalKey::NumPad8 => Key::NumPad8,
            PhysicalKey::NumPad9 => Key::NumPad9,
            PhysicalKey::NumPadAdd => Key::Add,
            PhysicalKey::NumPadClear => Key::Clear,
            PhysicalKey::NumPadComma => Key::AbntC2,
            PhysicalKey::NumPadDecimal => Key::Decimal,
            PhysicalKey::NumPadDivide => Key::Divide,
            PhysicalKey::NumPadEnter => Key::Return,
            PhysicalKey::NumPadEqual => Key::OemPlus,
            PhysicalKey::NumPadMultiply => Key::Multiply,
            PhysicalKey::NumPadParenLeft => Key::OemOpenBrackets,
            PhysicalKey::NumPadParenRight => Key::OemCloseBrackets,
            PhysicalKey::NumPadSubtract => Key::Subtract,
            // Function Section
            PhysicalKey::Escape => Key::Escape,
            PhysicalKey::F1 => Key::F1,
            PhysicalKey::F2 => Key::F2,
            PhysicalKey::F3 => Key::F3,
            PhysicalKey::F4 => Key::F4,
            PhysicalKey::F5 => Key::F5,
            PhysicalKey::F6 => Key::F6,
            PhysicalKey::F7 => Key::F7,
            PhysicalKey::F8 => Key::F8,
            PhysicalKey::F9 => Key::F9,
            PhysicalKey::F10 => Key::F10,
            PhysicalKey::F11 => Key::F11,
            PhysicalKey::F12 => Key::F12,
            PhysicalKey::F13 => Key::F13,
            PhysicalKey::F14 => Key::F14,
            PhysicalKey::F15 => Key::F15,
            PhysicalKey::F16 => Key::F16,
            PhysicalKey::F17 => Key::F17,
            PhysicalKey::F18 => Key::F18,
            PhysicalKey::F19 => Key::F19,
            PhysicalKey::F20 => Key::F20,
            PhysicalKey::F21 => Key::F21,
            PhysicalKey::F22 => Key::F22,
            PhysicalKey::F23 => Key::F23,
            PhysicalKey::F24 => Key::F24,
            PhysicalKey::PrintScreen => Key::Snapshot,
            PhysicalKey::ScrollLock => Key::Scroll,
            PhysicalKey::Pause => Key::Pause,
            // Media Keys
            PhysicalKey::BrowserBack => Key::BrowserBack,
            PhysicalKey::BrowserFavorites => Key::BrowserFavorites,
            PhysicalKey::BrowserForward => Key::BrowserForward,
            PhysicalKey::BrowserHome => Key::BrowserHome,
            PhysicalKey::BrowserRefresh => Key::BrowserRefresh,
            PhysicalKey::BrowserSearch => Key::BrowserSearch,
            PhysicalKey::BrowserStop => Key::BrowserStop,
            PhysicalKey::Eject => Key::None,
            PhysicalKey::LaunchApp1 => Key::LaunchApplication1,
            PhysicalKey::LaunchApp2 => Key::LaunchApplication2,
            PhysicalKey::LaunchMail => Key::LaunchMail,
            PhysicalKey::MediaPlayPause => Key::MediaPlayPause,
            PhysicalKey::MediaSelect => Key::SelectMedia,
            PhysicalKey::MediaStop => Key::MediaStop,
            PhysicalKey::MediaTrackNext => Key::MediaNextTrack,
            PhysicalKey::MediaTrackPrevious => Key::MediaPreviousTrack,
            PhysicalKey::Power => Key::None,
            PhysicalKey::Sleep => Key::Sleep,
            PhysicalKey::AudioVolumeDown => Key::VolumeDown,
            PhysicalKey::AudioVolumeMute => Key::VolumeMute,
            PhysicalKey::AudioVolumeUp => Key::VolumeUp,
            PhysicalKey::WakeUp => Key::None,
            // Legacy Keys
            PhysicalKey::Again => Key::None,
            PhysicalKey::Copy => Key::DbeHiragana,
            PhysicalKey::Cut => Key::None,
            PhysicalKey::Find => Key::None,
            PhysicalKey::Open => Key::None,
            PhysicalKey::Paste => Key::None,
            PhysicalKey::Props => Key::None,
            PhysicalKey::Select => Key::Select,
            PhysicalKey::Undo => Key::None,
            #[allow(unreachable_patterns)]
            _ => Key::None,
        }
    }

    /// Maps a physical key to a corresponding key symbol, if possible, on a
    /// QWERTY keyboard. `use_shift_modifier` indicates whether the Shift key
    /// is considered pressed.
    pub fn to_qwerty_key_symbol(self, use_shift_modifier: bool) -> Option<&'static str> {
        match self {
            PhysicalKey::None => None,
            // Writing System Keys
            PhysicalKey::Backquote => Some(if use_shift_modifier { "~" } else { "`" }),
            PhysicalKey::Backslash => Some(if use_shift_modifier { "|" } else { "\\" }),
            PhysicalKey::BracketLeft => Some(if use_shift_modifier { "{" } else { "[" }),
            PhysicalKey::BracketRight => Some(if use_shift_modifier { "}" } else { "]" }),
            PhysicalKey::Comma => Some(if use_shift_modifier { "<" } else { "," }),
            PhysicalKey::Digit0 => Some(if use_shift_modifier { ")" } else { "0" }),
            PhysicalKey::Digit1 => Some(if use_shift_modifier { "!" } else { "1" }),
            PhysicalKey::Digit2 => Some(if use_shift_modifier { "@" } else { "2" }),
            PhysicalKey::Digit3 => Some(if use_shift_modifier { "#" } else { "3" }),
            PhysicalKey::Digit4 => Some(if use_shift_modifier { "$" } else { "4" }),
            PhysicalKey::Digit5 => Some(if use_shift_modifier { "%" } else { "5" }),
            PhysicalKey::Digit6 => Some(if use_shift_modifier { "^" } else { "6" }),
            PhysicalKey::Digit7 => Some(if use_shift_modifier { "&" } else { "7" }),
            PhysicalKey::Digit8 => Some(if use_shift_modifier { "*" } else { "8" }),
            PhysicalKey::Digit9 => Some(if use_shift_modifier { "(" } else { "9" }),
            PhysicalKey::Equal => Some(if use_shift_modifier { "+" } else { "=" }),
            PhysicalKey::IntlBackslash => Some(if use_shift_modifier { "|" } else { "\\" }),
            PhysicalKey::IntlRo => None,
            PhysicalKey::IntlYen => None,
            PhysicalKey::A => Some(if use_shift_modifier { "A" } else { "a" }),
            PhysicalKey::B => Some(if use_shift_modifier { "B" } else { "b" }),
            PhysicalKey::C => Some(if use_shift_modifier { "C" } else { "c" }),
            PhysicalKey::D => Some(if use_shift_modifier { "D" } else { "d" }),
            PhysicalKey::E => Some(if use_shift_modifier { "E" } else { "e" }),
            PhysicalKey::F => Some(if use_shift_modifier { "F" } else { "f" }),
            PhysicalKey::G => Some(if use_shift_modifier { "G" } else { "g" }),
            PhysicalKey::H => Some(if use_shift_modifier { "H" } else { "h" }),
            PhysicalKey::I => Some(if use_shift_modifier { "I" } else { "i" }),
            PhysicalKey::J => Some(if use_shift_modifier { "J" } else { "j" }),
            PhysicalKey::K => Some(if use_shift_modifier { "K" } else { "k" }),
            PhysicalKey::L => Some(if use_shift_modifier { "L" } else { "l" }),
            PhysicalKey::M => Some(if use_shift_modifier { "M" } else { "m" }),
            PhysicalKey::N => Some(if use_shift_modifier { "N" } else { "n" }),
            PhysicalKey::O => Some(if use_shift_modifier { "O" } else { "o" }),
            PhysicalKey::P => Some(if use_shift_modifier { "P" } else { "p" }),
            PhysicalKey::Q => Some(if use_shift_modifier { "Q" } else { "q" }),
            PhysicalKey::R => Some(if use_shift_modifier { "R" } else { "r" }),
            PhysicalKey::S => Some(if use_shift_modifier { "S" } else { "s" }),
            PhysicalKey::T => Some(if use_shift_modifier { "T" } else { "t" }),
            PhysicalKey::U => Some(if use_shift_modifier { "U" } else { "u" }),
            PhysicalKey::V => Some(if use_shift_modifier { "V" } else { "v" }),
            PhysicalKey::W => Some(if use_shift_modifier { "W" } else { "w" }),
            PhysicalKey::X => Some(if use_shift_modifier { "X" } else { "x" }),
            PhysicalKey::Y => Some(if use_shift_modifier { "Y" } else { "y" }),
            PhysicalKey::Z => Some(if use_shift_modifier { "Z" } else { "z" }),
            PhysicalKey::Minus => Some(if use_shift_modifier { "_" } else { "-" }),
            PhysicalKey::Period => Some(if use_shift_modifier { ">" } else { "." }),
            PhysicalKey::Quote => Some(if use_shift_modifier { "\"" } else { "'" }),
            PhysicalKey::Semicolon => Some(if use_shift_modifier { ":" } else { ";" }),
            PhysicalKey::Slash => Some(if use_shift_modifier { "?" } else { "/" }),
            // Functional Keys
            PhysicalKey::AltLeft => None,
            PhysicalKey::AltRight => None,
            PhysicalKey::Backspace => Some("\u{8}"),
            PhysicalKey::CapsLock => None,
            PhysicalKey::ContextMenu => None,
            PhysicalKey::ControlLeft => None,
            PhysicalKey::ControlRight => None,
            PhysicalKey::Enter => Some("\r"),
            PhysicalKey::MetaLeft => None,
            PhysicalKey::MetaRight => None,
            PhysicalKey::ShiftLeft => None,
            PhysicalKey::ShiftRight => None,
            PhysicalKey::Space => Some(" "),
            PhysicalKey::Tab => Some("\t"),
            PhysicalKey::Convert => None,
            PhysicalKey::KanaMode => None,
            PhysicalKey::Lang1 => None,
            PhysicalKey::Lang2 => None,
            PhysicalKey::Lang3 => None,
            PhysicalKey::Lang4 => None,
            PhysicalKey::Lang5 => None,
            PhysicalKey::NonConvert => None,
            // Control Pad Section
            PhysicalKey::Delete => None,
            PhysicalKey::End => None,
            PhysicalKey::Help => None,
            PhysicalKey::Home => None,
            PhysicalKey::Insert => None,
            PhysicalKey::PageDown => None,
            PhysicalKey::PageUp => None,
            // Arrow Pad Section
            PhysicalKey::ArrowDown => None,
            PhysicalKey::ArrowLeft => None,
            PhysicalKey::ArrowRight => None,
            PhysicalKey::ArrowUp => None,
            // Numpad Section
            PhysicalKey::NumLock => None,
            PhysicalKey::NumPad0 => Some("0"),
            PhysicalKey::NumPad1 => Some("1"),
            PhysicalKey::NumPad2 => Some("2"),
            PhysicalKey::NumPad3 => Some("3"),
            PhysicalKey::NumPad4 => Some("4"),
            PhysicalKey::NumPad5 => Some("5"),
            PhysicalKey::NumPad6 => Some("6"),
            PhysicalKey::NumPad7 => Some("7"),
            PhysicalKey::NumPad8 => Some("8"),
            PhysicalKey::NumPad9 => Some("9"),
            PhysicalKey::NumPadAdd => Some("+"),
            PhysicalKey::NumPadClear => None,
            PhysicalKey::NumPadComma => Some(","),
            PhysicalKey::NumPadDecimal => Some("."),
            PhysicalKey::NumPadDivide => Some("/"),
            PhysicalKey::NumPadEnter => Some("\r"),
            PhysicalKey::NumPadEqual => Some("="),
            PhysicalKey::NumPadMultiply => Some("*"),
            PhysicalKey::NumPadParenLeft => Some("("),
            PhysicalKey::NumPadParenRight => Some(")"),
            PhysicalKey::NumPadSubtract => Some("-"),
            // Function Section
            PhysicalKey::Escape => Some("\u{1B}"),
            PhysicalKey::F1 => None,
            PhysicalKey::F2 => None,
            PhysicalKey::F3 => None,
            PhysicalKey::F4 => None,
            PhysicalKey::F5 => None,
            PhysicalKey::F6 => None,
            PhysicalKey::F7 => None,
            PhysicalKey::F8 => None,
            PhysicalKey::F9 => None,
            PhysicalKey::F10 => None,
            PhysicalKey::F11 => None,
            PhysicalKey::F12 => None,
            PhysicalKey::F13 => None,
            PhysicalKey::F14 => None,
            PhysicalKey::F15 => None,
            PhysicalKey::F16 => None,
            PhysicalKey::F17 => None,
            PhysicalKey::F18 => None,
            PhysicalKey::F19 => None,
            PhysicalKey::F20 => None,
            PhysicalKey::F21 => None,
            PhysicalKey::F22 => None,
            PhysicalKey::F23 => None,
            PhysicalKey::F24 => None,
            PhysicalKey::PrintScreen => None,
            PhysicalKey::ScrollLock => None,
            PhysicalKey::Pause => None,
            // Media Keys
            PhysicalKey::BrowserBack => None,
            PhysicalKey::BrowserFavorites => None,
            PhysicalKey::BrowserForward => None,
            PhysicalKey::BrowserHome => None,
            PhysicalKey::BrowserRefresh => None,
            PhysicalKey::BrowserSearch => None,
            PhysicalKey::BrowserStop => None,
            PhysicalKey::Eject => None,
            PhysicalKey::LaunchApp1 => None,
            PhysicalKey::LaunchApp2 => None,
            PhysicalKey::LaunchMail => None,
            PhysicalKey::MediaPlayPause => None,
            PhysicalKey::MediaSelect => None,
            PhysicalKey::MediaStop => None,
            PhysicalKey::MediaTrackNext => None,
            PhysicalKey::MediaTrackPrevious => None,
            PhysicalKey::Power => None,
            PhysicalKey::Sleep => None,
            PhysicalKey::AudioVolumeDown => None,
            PhysicalKey::AudioVolumeMute => None,
            PhysicalKey::AudioVolumeUp => None,
            PhysicalKey::WakeUp => None,
            // Legacy Keys
            PhysicalKey::Again => None,
            PhysicalKey::Copy => None,
            PhysicalKey::Cut => None,
            PhysicalKey::Find => None,
            PhysicalKey::Open => None,
            PhysicalKey::Paste => None,
            PhysicalKey::Props => None,
            PhysicalKey::Select => None,
            PhysicalKey::Undo => None,
            #[allow(unreachable_patterns)]
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_to_qwerty() {
        assert_eq!(PhysicalKey::A.to_qwerty_key(), Key::A);
        assert_eq!(PhysicalKey::Digit1.to_qwerty_key(), Key::D1);
        assert_eq!(PhysicalKey::None.to_qwerty_key(), Key::None);
        assert_eq!(PhysicalKey::A.to_qwerty_key_symbol(false), Some("a"));
        assert_eq!(PhysicalKey::A.to_qwerty_key_symbol(true), Some("A"));
        assert_eq!(PhysicalKey::Digit1.to_qwerty_key_symbol(true), Some("!"));
        assert_eq!(PhysicalKey::None.to_qwerty_key_symbol(false), None);
    }
}
