//! Animators: the per-type interpolation of key frame values.

mod animator;
mod base_brush_animator;
mod bool_animator;
mod box_shadow_animator;
mod box_shadows_animator;
mod byte_animator;
mod color_animator;
mod corner_radius_animator;
mod double_animator;
mod effect_animator;
mod float_animator;
mod gradient_brush_animator;
mod int16_animator;
mod int32_animator;
mod int64_animator;
mod point_animator;
mod rect_animator;
mod relative_point_animator;
mod relative_scalar_animator;
mod size_animator;
mod solid_color_brush_animator;
mod thickness_animator;
mod transform_animator;
mod transform_operations_animator;
mod uint16_animator;
mod uint32_animator;
mod uint64_animator;
mod vector_animator;

pub use animator::{Animator, AnimatorBase};
pub(crate) use animator::{apply_with_visual, interpolation_handler, run};
pub use base_brush_animator::BaseBrushAnimator;
pub use bool_animator::BoolAnimator;
pub use box_shadow_animator::BoxShadowAnimator;
pub use box_shadows_animator::BoxShadowsAnimator;
pub use byte_animator::ByteAnimator;
pub use color_animator::ColorAnimator;
pub use corner_radius_animator::CornerRadiusAnimator;
pub use double_animator::DoubleAnimator;
pub use effect_animator::{BlurEffectAnimator, DropShadowEffectAnimator, EffectAnimator};
pub use float_animator::FloatAnimator;
pub use gradient_brush_animator::GradientBrushAnimator;
pub use int16_animator::Int16Animator;
pub use int32_animator::Int32Animator;
pub use int64_animator::Int64Animator;
pub use point_animator::PointAnimator;
pub use rect_animator::RectAnimator;
pub use relative_point_animator::RelativePointAnimator;
pub use relative_scalar_animator::RelativeScalarAnimator;
pub use size_animator::SizeAnimator;
pub use solid_color_brush_animator::ISolidColorBrushAnimator;
pub use thickness_animator::ThicknessAnimator;
pub use transform_animator::TransformAnimator;
pub use transform_operations_animator::TransformOperationsAnimator;
pub use uint16_animator::UInt16Animator;
pub use uint32_animator::UInt32Animator;
pub use uint64_animator::UInt64Animator;
pub use vector_animator::VectorAnimator;
