// @generated by the Rust emitter of ferroui-markup-xaml-loader (rust_emitter::generate_class_file).
// Do not edit: regenerate it (see the header of the module that includes this file).
// The document of `FerroUI.Markup.Xaml.UnitTests.Xaml.MyPanel` and the 0 it calls, of a group of 1 documents.

#![allow(dead_code, unused_imports)]

use ::ferroui_markup_xaml::xaml_il::runtime::compiled as rt;

/// The XML namespaces of documents of this file, as the compiler resolved them.
const XML_NAMESPACES_0: rt::XmlNamespaceTable = &[
    ("", &[("FerroUI", "FerroUI.Base"), ("FerroUI.Animation", "FerroUI.Base"), ("FerroUI.Animation.Easings", "FerroUI.Base"), ("FerroUI.Controls", "FerroUI.Base"), ("FerroUI.Data", "FerroUI.Base"), ("FerroUI.Data.Converters", "FerroUI.Base"), ("FerroUI.Input", "FerroUI.Base"), ("FerroUI.Input.GestureRecognizers", "FerroUI.Base"), ("FerroUI.Input.TextInput", "FerroUI.Base"), ("FerroUI.Layout", "FerroUI.Base"), ("FerroUI.LogicalTree", "FerroUI.Base"), ("FerroUI.Media", "FerroUI.Base"), ("FerroUI.Media.Imaging", "FerroUI.Base"), ("FerroUI.Media.Transformation", "FerroUI.Base"), ("FerroUI.Styling", "FerroUI.Base"), ("FerroUI", "FerroUI.Controls"), ("FerroUI.Automation", "FerroUI.Controls"), ("FerroUI.Controls", "FerroUI.Controls"), ("FerroUI.Controls.Embedding", "FerroUI.Controls"), ("FerroUI.Controls.Presenters", "FerroUI.Controls"), ("FerroUI.Controls.Primitives", "FerroUI.Controls"), ("FerroUI.Controls.Shapes", "FerroUI.Controls"), ("FerroUI.Controls.Templates", "FerroUI.Controls"), ("FerroUI.Controls.Notifications", "FerroUI.Controls"), ("FerroUI.Controls.Chrome", "FerroUI.Controls"), ("FerroUI.Controls.Documents", "FerroUI.Controls"), ("FerroUI.Markup.Xaml.MarkupExtensions", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Styling", "FerroUI.Markup.Xaml"), ("FerroUI.Markup.Xaml.Templates", "FerroUI.Markup.Xaml")]),
    ("x", &[]),
];

/// Populates `root` from the document of the class (`populate_handlers_templateevent_xaml`), with a root service provider
/// over `service_provider` (`XamlIlRuntimeHelpers.CreateRootServiceProviderV3`), as the
/// run-time loader populates it.
pub fn populate(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    root: &::ferroui_base::Ref<crate::support::xaml::event_tests::MyPanel>,
) -> ::core::result::Result<(), ::ferroui_markup_xaml::XamlLoadException> {
    let service_provider =
        ::ferroui_markup_xaml::xaml_il::runtime::XamlIlRuntimeHelpers::create_root_service_provider_v3(service_provider);
    populate_handlers_templateevent_xaml(::core::option::Option::Some(service_provider), root)
}

/// The base URI and the XML namespaces of `Handlers/TemplateEvent.xaml`.
static POPULATE_HANDLERS_TEMPLATEEVENT_XAML_DOCUMENT: rt::DocumentInfo = rt::DocumentInfo { base_uri: ::core::option::Option::Some("ferres://FerroUI.Markup.Xaml.UnitTests/Handlers/TemplateEvent.xaml"), namespaces: XML_NAMESPACES_0 };

/// Generated from `Handlers/TemplateEvent.xaml`.
pub fn populate_handlers_templateevent_xaml(
    service_provider: ::core::option::Option<::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    root: &::ferroui_base::Ref<crate::support::xaml::event_tests::MyPanel>,
) -> ::core::result::Result<(), ::ferroui_markup_xaml::XamlLoadException> {
    let root = root.clone();
    let context = rt::populate_context(service_provider, &POPULATE_HANDLERS_TEMPLATEEVENT_XAML_DOCUMENT, rt::to_value(root.clone()));
    let name_scope = context.name_scope_field();
    root.begin_init();
    // Handlers/TemplateEvent.xaml(1,152) Children
    let children_collection_0 = ::ferroui_controls::Panel::__markup_get_Children(root.upcast_ref::<::ferroui_controls::Panel>());
    // Handlers/TemplateEvent.xaml(1,152) Button
    let button_0 = ::ferroui_controls::Button::new();
    button_0.begin_init();
    ::ferroui_controls::Controls::__markup_Add_0(&children_collection_0, ::core::clone::Clone::clone(&button_0).upcast::<::ferroui_controls::Control>());
    // Handlers/TemplateEvent.xaml(1,159) Name
    button_0.set_direct_value(::ferroui_base::StyledElement::name_property(), ::core::option::Option::Some(::std::string::String::from("target")));
    rt::register_name(name_scope.as_ref(), "target", ::core::clone::Clone::clone(&button_0).upcast::<::ferroui_base::FerroObject>(), 1, 159)?;
    // Handlers/TemplateEvent.xaml(1,191) Template
    let control_template_0 = ::ferroui_markup_xaml::templates::ControlTemplate::__markup_new_0();
    // Handlers/TemplateEvent.xaml(1,208) Content
    let deferred_0 = rt::defer(rt::class_handle(<::ferroui_controls::Control as ::ferroui_base::StaticType>::TYPE), &context, populate_handlers_templateevent_xaml_deferred_0, 1, 208)?;
    ::ferroui_markup_xaml::templates::ControlTemplate::__markup_set_Content(&control_template_0, rt::to_object(::core::clone::Clone::clone(&deferred_0)));
    button_0.set_value(::ferroui_controls::primitives::TemplatedControl::template_property(), ::core::option::Option::Some(::core::clone::Clone::clone(&control_template_0) as ::std::rc::Rc<dyn ::ferroui_controls::templates::IControlTemplate>));
    rt::invoked(button_0.try_end_init(), 1, 152)?;
    rt::invoked(root.try_end_init(), 1, 2)?;
    rt::complete_root_name_scope(::core::option::Option::Some(&root), name_scope.as_ref(), 1, 2)?;
    ::core::result::Result::Ok(())
}

/// Builds the deferred content at `Handlers/TemplateEvent.xaml(1,208)` (a template or a deferred resource).
fn populate_handlers_templateevent_xaml_deferred_0(
    service_provider: &::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>,
) -> ::core::result::Result<::ferroui_base::metadata::MarkupValue, ::ferroui_markup_xaml::XamlLoadException> {
    let context = rt::deferred_context(service_provider, &POPULATE_HANDLERS_TEMPLATEEVENT_XAML_DOCUMENT);
    let name_scope = context.name_scope_field();
    // Handlers/TemplateEvent.xaml(1,208) Border
    let border_0 = ::ferroui_controls::Border::new();
    context.set_intermediate_root_object(rt::to_value(border_0.clone()));
    border_0.begin_init();
    // Handlers/TemplateEvent.xaml(1,215) Name
    border_0.set_direct_value(::ferroui_base::StyledElement::name_property(), ::core::option::Option::Some(::std::string::String::from("part")));
    rt::register_name(name_scope.as_ref(), "part", ::core::clone::Clone::clone(&border_0).upcast::<::ferroui_base::FerroObject>(), 1, 215)?;
    // Handlers/TemplateEvent.xaml(1,208) Tapped
    rt::add_handler(&border_0, &::ferroui_base::input::InputElement::__markup_field_TappedEvent(), rt::method_delegate(&context, 2, |this, arguments| { crate::support::xaml::event_tests::MyPanel::__markup_OnTapped_1(this, arguments.next()?, arguments.next()?); ::core::result::Result::Ok(::core::option::Option::None) }));
    rt::invoked(border_0.try_end_init(), 1, 208)?;
    ::core::result::Result::Ok(rt::to_value(border_0.clone()))
}

/// The loader of the compiled documents of this file (`!XamlLoader.TryLoad`): the object of the
/// public document with the URI `uri` (compared as upstream's `OrdinalIgnoreCase`,
/// `rt::uri_equals`); `Ok(None)` if this file has no such document, the load error of the build
/// if it fails.
pub fn try_load(
    _service_provider: ::core::option::Option<&::std::rc::Rc<dyn ::ferroui_base::metadata::IServiceProvider>>,
    uri: &str,
) -> ::core::result::Result<::core::option::Option<::ferroui_base::BoxedValue>, ::ferroui_markup_xaml::XamlLoadException> {
    if rt::uri_equals(uri, "ferres://FerroUI.Markup.Xaml.UnitTests/Handlers/TemplateEvent.xaml", "") {
        return ::core::result::Result::Ok(::ferroui_base::metadata::into_markup_value(crate::support::xaml::event_tests::MyPanel::new()));
    }
    ::core::result::Result::Ok(::core::option::Option::None)
}
